### PR TITLE
Ansibilizes CoreOS bootstrapping process.

### PR DESCRIPTION
**Pull request by adamschaub**
Ansibilizes python bootstrapping process for CoreOS. 

Unpacks bootstrap.sh into a series of raw Ansible tasks, giving a more transparent view into the python bootstrapping process.

### CODE REVIEW

**Comment by adamschaub** [comment]
I've signed it!

**Comment by adamschaub** [comment]
I signed it!

**Comment by danehans** [comment]
@adamschaub I don't believe the PR can get merged when it's tagged as cla: no. Can you try closing and resubmitting to see if the cla gets updated?

**Comment by eparis** [comment]
correct, I won't merge it with CLA problems. Are you sure the e-mail address in the git author of the commit(s) is the one you used to sign the CLA? If not, that's what you need to fix.

**Pull request closed without merging**
