### PR TITLE
Add ca-certificates to prometheus-to-sd to make https requests

### PR DESCRIPTION
**Pull request by gaplyk**

### CODE REVIEW

**Comment by gaplyk** [comment]
//cc @piosz 
Is there any chance to include this to the new image alongside with #2597

**Comment by crassirostris** [comment]
@gaplyk Thanks! Do you have a strict requirement to use alpine? What about `gcr.io/google-containers/debian-base-amd64:0.1`? It's maintained by Kubernetes devs and contains most recent security patches.

You can install debian packages there using the following command:

```
RUN clean-install ca-certificates
```

**Comment by piosz** [comment]
@timstclair any thoughts?

**Comment by gaplyk** [comment]
no, I don't have any requirements. Updating pr

**Comment by timstclair** [comment]
I'm actually fine with using alpine or debian-base in this case, as there aren't any library dependencies. We have talked about making a "scratch + ca-certs" base image to solve this use case, but haven't gotten to it yet (Interested? :wink: )

**Comment by piosz** [comment]
LGTM, please squash commits before merge.

**Comment by crassirostris** [comment]
@gaplyk Sorry, I though it was merged already. Could you please also rebase and bump the image version to `v0.1.2` in the Makefile?

**Comment by gaplyk** [comment]
@crassirostris done

**Comment by crassirostris** [comment]
@gabrtv Thanks a lot! I'll check that container starts and is working and then will merge the pr & will push the image

/lgtm

**Comment by crassirostris** [comment]
@gaplyk Pushed `v0.1.2`. Thanks for your contribution!

**Comment by piosz** [comment]
Thanks @gaplyk and @crassirostris

**Pull request merged**
