### PR TITLE
Allow vrrp v2 to be specified as an argument in the container specification

### PR DESCRIPTION
**Pull request by dseeley-sky**
Add ability to specify VRRP V2 (as opposed to default of 3) in the keepalived template. Current and previous keepalived releases have a problem with VRRP V3 when there are more than 2 nodes (https://github.com/acassen/keepalived/issues/642).  This has been fixed in master, but not part of a release yet.  Using VRRP V2 bypasses the issue.

### CODE REVIEW

**Review by bowei — APPROVED** [review]

**Comment by bowei** [comment]
CI is failing

**Comment by dseeley-sky** [comment]
CI failure is due to lint failure in an unrelated project:

> /home/travis/gopath/src/k8s.io/contrib/kubeform/pkg/provider/provider.go:428:2: redundant if ...; err != nil check, just return error instead.

I'm not currently in a position to be able to text any fix I apply to this unfortunately (I don't understand how it got past CI in the first place) - it's also causing CI failure in a number of other PRs.

**Comment by bowei** [comment]
@madhusudancs -- hey looks like there is a CI failure in kubeforrm...

**Comment by dseeley-sky** [comment]
It looks like kubeform has been fixed - is there any way to trigger a CI retest?

**Comment by madhusudancs** [comment]
/approve

(for `hack/`)

**Pull request merged**
