### PR TITLE
Create Human/Bot interaction tools

### PR DESCRIPTION
**Pull request by apelisse**
This is defining what will be used to parse commands (message from human
to robot) and notifications (message from robot to human).

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1582)

### CODE REVIEW

**Comment by apelisse** [comment]
*[mungegithub/mungers/matchers/comment/interactions.go, line 78 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KP_Ccr-3zZ5PARnctak:-KP_Ccr-3zZ5PARnctal:bkiam3r) ([raw file](https://github.com/kubernetes/contrib/blob/52654e7e974fbb330ff725c2981f28935af066d2/mungegithub/mungers/matchers/comment/interactions.go#L78)):*
> ```Go
> }
> 
> func HumanActor() Matcher {
> ```

This is slightly broken. Not sure what we should do ....

What if the author is not set properly on the pull-request (because pr.Author is nil)? Should it be a human or a bot? or something else ..

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by apelisse** [comment]
*[mungegithub/mungers/matchers/comment/interactions.go, line 78 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KP_Ccr-3zZ5PARnctak:-KP_EmxOmPc09LUVaV_g:b-iem4it) ([raw file](https://github.com/kubernetes/contrib/blob/52654e7e974fbb330ff725c2981f28935af066d2/mungegithub/mungers/matchers/comment/interactions.go#L78)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> This is slightly broken. Not sure what we should do ....
> 
> What if the author is not set properly on the pull-request (because pr.Author is nil)? Should it be a human or a bot? or something else ..
</details>
Should be better now

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by pwittrock** [comment]
@apelisse  I probably won't have time to review this for a week+

**Comment by grodrigues3** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mungegithub/mungers/matchers/comment/command.go, line 35 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPoBD2kyqa8P9AUGG5S:-KPoBD2kyqa8P9AUGG5T:b-vq5bf8) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command.go#L35)):*
> ```Go
> var (
> 	commandRegex = regexp.MustCompile(`^/([^\s]+)\s?(.*)$`)
> )
> ```

include a short comment explaining the regex. Something like   // Looks for / followed by command followed by option arguments.  Also, can commands include nonalphanumeric chars?  What if someone included a C/C++/Java style comment in the body of the comment //why does this work?   

---

*[mungegithub/mungers/matchers/comment/command.go, line 51 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPoDoZd7r2SwpLyLJ-m:-KPoDoZd7r2SwpLyLJ-n:b362axk) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command.go#L51)):*
> ```Go
> 	return &Command{
> 		Name:      strings.ToUpper(match[1]),
> 		Arguments: strings.TrimSpace(match[2]),
> ```

what if match doesn't have 3 elements.  my understanding is FindStringSubmatch returns the regex match followed by the match of the subexpressions if any.  So what if there is no argument ?  Something like "/lgtm"?  Won't matches[2] cause an indexError

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by grodrigues3** [comment]
*[mungegithub/mungers/matchers/comment/command_test.go, line 28 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPoISprMvxFmKDCxaaa:-KPoISprMvxFmKDCxaab:bqdb4nq) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command_test.go#L28)):*
> ```Go
> func TestParseCommand(t *testing.T) {
> 	tests := []struct {
> 		command *Command
> ```

nit: rename to trueCommand or expectedCommand

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by grodrigues3** [comment]
*[mungegithub/mungers/matchers/comment/command.go, line 56 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPoJFm9d3Xid5jcyH3K:-KPoJFm9d3Xid5jcyH3L:b-n2w4qa) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command.go#L56)):*
> ```Go
> 
> func (n *Command) String() string {
> 	str := fmt.Sprintf("/%s %s", strings.ToUpper(n.Name), strings.TrimSpace(n.Arguments))
> ```

why the extra tmp variable :)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by apelisse** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[mungegithub/mungers/matchers/comment/command.go, line 51 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPoDoZd7r2SwpLyLJ-m:-KPoWlCwAwnrBLJOfXiz:bcld3zy) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command.go#L51)):*
<details><summary><i>Previously, grodrigues3 wrote…</i></summary>
> what if match doesn't have 3 elements.  my understanding is FindStringSubmatch returns the regex match followed by the match of the subexpressions if any.  So what if there is no argument ?  Something like "/lgtm"?  Won't matches[2] cause an indexError
</details>
It should work: https://play.golang.org/p/ODxpr9JdL1

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by pwittrock** [comment]
Reviewed 4 of 7 files at r1, 2 of 2 files at r2.
Review status: 2 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[mungegithub/mungers/matchers/comment/command_test.go, line 49 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPtD47QgFum3VjGLfk_:-KPtD47RUwDo4HM3KsuX:bs8dxdf) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command_test.go#L49)):*
> ```Go
> 		{
> 			command: &Command{Name: "COMMAND", Arguments: "Arguments is trimmed"},
> 			comment: "/COMMAND     Arguments is trimmed   ",
> ```

Add a case for no arguments.

---

*[mungegithub/mungers/matchers/comment/interactions.go, line 30 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPtELp9VhsPuTN39VsD:-KPtELpAGj78XwI0mP3I:b-xbwk76) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/interactions.go#L30)):*
> ```Go
> type NotificationName string
> 
> // Match returns true if the comment is a notification
> ```

Update the comment

---

*[mungegithub/mungers/matchers/comment/interactions.go, line 55 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPtHehn4w6WAgmrPty-:-KPtHehn4w6WAgmrPty0:b2dwni6) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/interactions.go#L55)):*
> ```Go
> type CommandArguments regexp.Regexp
> 
> func (c CommandArguments) Match(comment *github.IssueComment) bool {
> ```

Are there tests for this?

---

*[mungegithub/mungers/matchers/comment/notification.go, line 35 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPtEx9RP9Qwy60Hb4iD:-KPtEx9RP9Qwy60Hb4iE:b-a345ek) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/notification.go#L35)):*
> ```Go
> 
> var (
> 	notificationRegex = regexp.MustCompile(`^\[([^\]\s]+)\]\s?(.*)$`)
> ```

Leave a comment explaining the actual format for notifications

---

*[mungegithub/mungers/matchers/comment/notification_test.go, line 53 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPtFtIFBuYhwLbQh6C7:-KPtFtIFBuYhwLbQh6C8:bcul61j) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/notification_test.go#L53)):*
> ```Go
> 		{
> 			notif:   &Notification{Name: "NOTIF", Arguments: "Arguments is trimmed"},
> 			comment: "[notif]     Arguments is trimmed   ",
> ```

Add a notification without can args

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by pwittrock** [comment]
Reviewed 6 of 8 files at r3.
Review status: 7 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[mungegithub/mungers/matchers/comment/pinger.go, line 78 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPuYc_tNMrPSKsj-tUj:-KPuYc_tNMrPSKsj-tUk:bl9ekl6) ([raw file](https://github.com/kubernetes/contrib/blob/089230db98f79714836a1cac62ab7971dad94d38/mungegithub/mungers/matchers/comment/pinger.go#L78)):*
> ```Go
> 	// We have pinged too many times, it's time to try something else
> 	if p.isMaxReached(pings) {
> 		return nil
> ```

How do we know to act upon this since it returns the same value as shouldPingNow?  Do we need a second return value, or something else?

---

*[mungegithub/mungers/matchers/comment/pinger.go, line 107 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPuYRBU-IZfivoNS2Ka:-KPuYRBU-IZfivoNS2Kb:brm7bx) ([raw file](https://github.com/kubernetes/contrib/blob/089230db98f79714836a1cac62ab7971dad94d38/mungegithub/mungers/matchers/comment/pinger.go#L107)):*
> ```Go
> 
> func (p *Pinger) isMaxReached(pings FilteredComments) bool {
> 	return p.maxCount != 0 && len(pings) >= p.maxCount
> ```

Should this only count pings since the last ACK by the assignee?  WDYT?

---

*[mungegithub/mungers/matchers/comment/pinger.go, line 110 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPuWvLrXPTdXRx3zqPZ:-KPuWvLrXPTdXRx3zqP_:b1afjm7) ([raw file](https://github.com/kubernetes/contrib/blob/089230db98f79714836a1cac62ab7971dad94d38/mungegithub/mungers/matchers/comment/pinger.go#L110)):*
> ```Go
> }
> 
> func (p *Pinger) shouldPingNow(pings FilteredComments, startDate *time.Time) bool {
> ```

This is a good start, but we should probably have something more sophisticated that  only pings issues that don't have activity from the assignee in (time period) and allow contributors to ACK.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by apelisse** [comment]
Review status: 7 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[mungegithub/mungers/matchers/comment/command.go, line 35 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPoBD2kyqa8P9AUGG5S:-KPubElc0JqvC3kM9bxR:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command.go#L35)):*
<details><summary><i>Previously, grodrigues3 wrote…</i></summary>
> include a short comment explaining the regex. Something like   // Looks for / followed by command followed by option arguments.  Also, can commands include nonalphanumeric chars?  What if someone included a C/C++/Java style comment in the body of the comment //why does this work?   
</details>
Done.

---

*[mungegithub/mungers/matchers/comment/command.go, line 51 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPoDoZd7r2SwpLyLJ-m:-KPubGAyOqsz5VgXFWK7:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command.go#L51)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> It should work: https://play.golang.org/p/ODxpr9JdL1
</details>
Done.

---

*[mungegithub/mungers/matchers/comment/command.go, line 56 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPoJFm9d3Xid5jcyH3K:-KPubH3_Wg2vl_qGYw1w:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command.go#L56)):*
<details><summary><i>Previously, grodrigues3 wrote…</i></summary>
> why the extra tmp variable :)
</details>
Done.

---

*[mungegithub/mungers/matchers/comment/command_test.go, line 28 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPoISprMvxFmKDCxaaa:-KPubHpwhmQcQhOxR8Gq:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/command_test.go#L28)):*
<details><summary><i>Previously, grodrigues3 wrote…</i></summary>
> nit: rename to trueCommand or expectedCommand
</details>
Done.

---

*[mungegithub/mungers/matchers/comment/interactions.go, line 55 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPtHehn4w6WAgmrPty-:-KPubJCdo8795pDe2tCx:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/99c0e9bc59d2a683c75feeab5fb53f74198dc42f/mungegithub/mungers/matchers/comment/interactions.go#L55)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Are there tests for this?
</details>
Done.

---

*[mungegithub/mungers/matchers/comment/pinger.go, line 78 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPuYc_tNMrPSKsj-tUj:-KPubMFJDmvvORy5jaJE:b-9obkn2) ([raw file](https://github.com/kubernetes/contrib/blob/089230db98f79714836a1cac62ab7971dad94d38/mungegithub/mungers/matchers/comment/pinger.go#L78)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> How do we know to act upon this since it returns the same value as shouldPingNow?  Do we need a second return value, or something else?
</details>
Yeah, that has been my concern since the very beginning. I've decided to let the caller responsible of calling "MaxReached()" (which I made public for that purpose) to take action based on that.

---

*[mungegithub/mungers/matchers/comment/pinger.go, line 107 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPuYRBU-IZfivoNS2Ka:-KPubfhC88HmVf_lBenk:bokjgv9) ([raw file](https://github.com/kubernetes/contrib/blob/089230db98f79714836a1cac62ab7971dad94d38/mungegithub/mungers/matchers/comment/pinger.go#L107)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Should this only count pings since the last ACK by the assignee?  WDYT?
</details>
We could be fancy and had extra interactions with the pinger. But I think this should be the caller's responsibility (callers are usually going to be states, states know what should happen based on actual interactions. ack can have a very different meaning based on what we're trying to ping for). Also see next comment :-)

---

*[mungegithub/mungers/matchers/comment/pinger.go, line 110 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPuWvLrXPTdXRx3zqPZ:-KPubqSdFpBkwtt2gmEa:b-p2o3rl) ([raw file](https://github.com/kubernetes/contrib/blob/089230db98f79714836a1cac62ab7971dad94d38/mungegithub/mungers/matchers/comment/pinger.go#L110)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> This is a good start, but we should probably have something more sophisticated that  only pings issues that don't have activity from the assignee in (time period) and allow contributors to ACK.
</details>
Same, caller's responsibility (this is the point of "startDate"). If there are interactions and the pinger should be reset, then it should use the last activity date as startDate.

I'll try to explain one of the main usage of this class.

The close-stale-pr could be massively simplified:
```
startDate := findLastHumanInteraction()
pinger := NewPinger("CLOSE-STALE").SetMaxCount(3).SetTimePeriod(30*24*time.Hour)

if pinger.MaxReached(comments, startDate) { 
    obj.CloseIssue()
} else {
    obj.Post(pinger.PingerNotification(comments, MentionInvolvedUsers(), startDate).String())
}
```

No loop, a single if (which is the core of the actual logic anyway).

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by pwittrock** [comment]
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[mungegithub/mungers/matchers/comment/pinger.go, line 93 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-KPxHRyJaYcsbi4_h7Zl:-KPxHRyJaYcsbi4_h7Zm:b-88verv) ([raw file](https://github.com/kubernetes/contrib/blob/089230db98f79714836a1cac62ab7971dad94d38/mungegithub/mungers/matchers/comment/pinger.go#L93)):*
> ```Go
> 
> // MaxReached tells you if you've reached the limit yet
> func (p *Pinger) MaxReached(comments []*github.IssueComment, startDate *time.Time) bool {
> ```

How about calling it `IsMaxReached` to clarify that it is just checking the condition and not setting it

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by pwittrock** [comment]
Reviewed 2 of 8 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582)*

**Comment by pwittrock** [comment]
+lgtm 

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1582#-:-KPyBGC5xftip0DLpeMD:bgc0spy)*

**Comment by apelisse** [comment]
Changed a comment. Relgtm myself ...
/lgtm

**Pull request merged**
