### PR TITLE
Moving perfdash to kubernetes/perf-tests

### PR DESCRIPTION
**Pull request by krzysied**

### CODE REVIEW

**Comment by shyamjvs** [comment]
/hold
(Until we have the PR adding perf-dash to the other repo merged)

**Comment by wojtek-t** [comment]
> /hold
(Until we have the PR adding perf-dash to the other repo merge

We already have. And it's merged.

/lgtm

**Comment by shyamjvs** [comment]
Sorry, I didn't keep track of that.

/approve no-issue

**Comment by shyamjvs** [comment]
/hold cancel

:)

**Pull request merged**
