### PR TITLE
ignore failures that don't happen twice in a row

### PR DESCRIPTION
**Pull request by lavalamp**
Actually parse the junit result, allow merging to continue as long as we were able to get the list of failed tests and it doesn't intersect with the same list for the previous run.

### CODE REVIEW

**Comment by lavalamp** [comment]
Inspired by @david-mcmahon

**Comment by eparis** [comment]
@gmarek

**Comment by lavalamp** [comment]
This also stops reading from jenkins and solely relies on GCS.

**Comment by lavalamp** [comment]
@eparis any objections to turning this on? merge queue needs all the help it can get...

**Comment by eparis** [comment]
Other than I haven't really reviewed it, my only objection would be that it effectively doubles the time required to notice a bad commit. And it just lets us paper over the flakes.

But given the tradeoffs, I'm good with it.

**Comment by lavalamp** [comment]
@eparis gave an OK over chat. Going to merge & push.

**Comment by lavalamp** [comment]
I broke the UI a little bit, but I guess there's no fear of not noticing (if you're looking at the dashboard)

**Comment by gmarek** [comment]
LGTM. We probably can add the same logic to WeakStable.

**Pull request merged**
