### PR TITLE
Removing non-org members

### PR DESCRIPTION
**Pull request by foxish**
@aledbf
@danehans
@simonswine
@rutsky
@itayariel
@stephenrlouie
@mattthias
@jdavis7257

Please add yourself to the kubernetes org, so that PR assignments can be made.

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
All mentioned folks--happy to add you back here, but merging this now to reduce the number of failed github API requests our bot is making.

**Comment by eparis** [comment]
we need a better way to get people into the org. Doesn't seem like you can request, only someone can add you...

**Comment by lavalamp** [comment]
I'm pretty sure you can request, I've gotten emails saying people have requested to be in-- maybe you have to request at the group rather than the org level? If that's the case, I think there's a "collaborators" group.

**Comment by simonswine** [comment]
I think the request is only possible, if you are already a member of any other team in the organisation. Happy to join the org if someone with privileges to do hat is around...

**Comment by lavalamp** [comment]
I see. I'll invite all of the mentioned people, then. :)

**Comment by lavalamp** [comment]
Invites sent.

**Comment by simonswine** [comment]
@lavalamp thanks for the invite. Probably by tomorrow we can revert the PR

**Comment by aledbf** [comment]
@lavalamp thanks for the invite

**Pull request merged**
