### PR TITLE
ansible : load balance kubernetes api server

### PR DESCRIPTION
**Pull request by mkumatag**
This PR will enables load balancing across multiple kubernetes api servers.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/2033)

### CODE REVIEW

**Comment by mkumatag** [comment]
I signed it!

**Comment by mkumatag** [comment]
ping!

**Comment by ingvagabund** [comment]
As long as ``master_cluster_hostname`` is not set, this change is harmless. Though, I don't have CI to test the HA master.

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by mkumatag** [comment]
Thanks @ingvagabund

**Pull request merged**
