### PR TITLE
Add spiffxp as root OWNER

### PR DESCRIPTION
**Pull request by spiffxp**
I want to help remove things from this repo

### CODE REVIEW

**Comment by spiffxp** [comment]
/assign @eparis @foxish @lavalamp 
I want to help de-bottleneck you three here.  Let me know if there's anything else I should do

**Comment by spiffxp** [comment]
/retest
Not sure what's up with tide and Travis let's see if this refreshes things

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks

**Pull request merged**
