### PR TITLE
Introduce setting as to whether to run the kubelet on a master.

### PR DESCRIPTION
**Pull request by pedro-r-marques**
Kubelet should be an optional setting.

### CODE REVIEW

**Comment by eparis** [comment]
I also might be fine if we forced a kubelet on the master, assuming it was 'non-schedulable' unless the the master was also a node...

**Comment by pedro-r-marques** [comment]
@eparis The kubelet configuration has the option: "--register-node=false"; this makes it so that the kubelet doesn't register itself as a node. This is set in roles/master/templates/kubelet.j2.

**Comment by eparis** [comment]
ok, i'll wait to merge until we hear the actual problem @cgwalters to decide if we should merge this or just leave it as it is...

**Comment by eparis** [comment]
@pedro-r-marques I'm going to close this PR as it was a part of @cgwalters fix.  Will you please send another PR which installs kubernetes-node on the master if contrail is enabled?

**Comment by pedro-r-marques** [comment]
Will do.

On Oct 20, 2015, at 8:23 AM, Eric Paris <notifications@github.com<mailto:notifications@github.com>> wrote:


@pedro-r-marques<https://github.com/pedro-r-marques> I'm going to close this PR as it was a part of @cgwalters<https://github.com/cgwalters> fix. Will you please send another PR which installs kubernetes-node on the master if contrail is enabled?

**Pull request closed without merging**
