### PR TITLE
Add proxy environment settings in yum modules

### LINKED ISSUE #1728: missing proxy environment settings in ansible roles
missing proxy configuration for yum module in the following files:
ansible/roles/docker/tasks/install-rpms.yml
ansible/roles/master/tasks/install_rpms.yml
ansible/roles/master/tasks/pkgMgrInstallers/centos-install.yml
ansible/roles/node/tasks/install_rpms.yml
ansible/roles/node/tasks/pkgMgrInstallers/centos-install.yml

need to add the following lines for yum in files mentioned:
```
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
```

### PR DESCRIPTION
**Pull request by ingvagabund**
Fixes: #1728

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1729)

### CODE REVIEW

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by ingvagabund** [comment]
@k3vinha can you review?

**Comment by k3vinha** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1729)*

**Pull request merged**
