### PR TITLE
Don't comment "Labelling this PR as size/X", that's redundant.

### PR DESCRIPTION
**Pull request by spxtr**
I haven't tested this. The comment doesn't tell us anything new.  The only reason I can think of for it to exist is if you want an email notification or something, but that seems like a stretch.

### CODE REVIEW

**Comment by thockin** [comment]
Email is exactly why it comments.  Many of the project leads depend on
email.

**Comment by spxtr** [comment]
Why do project leads need an email telling them how big their PRs are?

Feel free to close this. It's not a big deal at all.

**Comment by thockin** [comment]
The fact that github sends me an email means I can label it in my inbox, which makes it easier for me to triage and review.  In other words, XL PRs turn red in my inbox, and don't get reviewed as readily :)

**Comment by thockin** [comment]
Thanks, though.  Appreciate the PR.

**Pull request closed without merging**
