### PR TITLE
[Ansible] #1407 sudo depreciation warning: sudo -> become

### PR DESCRIPTION
**Pull request by AdrianGPrado**
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

Usage example from Ansible documentation:

    - name: Ensure the httpd service is running
      service:
         name: httpd
        state: started
      become: true
   

Ansible [become module](http://docs.ansible.com/ansible/become.html#become) default user is `root`

Fixes: #1407

### CODE REVIEW

**Comment by AdrianGPrado** [comment]
@ingvagabund PR for issue #1407 `s/sudo/become`

**Comment by ingvagabund** [comment]
@stephenrlouie @danehans what version of ansible is currently available in CoreOS?

**Comment by danehans** [comment]
Ansible is not necessarily available in CoreOS. We have had success with 2.0.0.2. We experienced problems collecting OS facts with a later version.

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by ingvagabund** [comment]
Thanks a lot

**Comment by AdrianGPrado** [comment]
Thank you! :)

**Pull request merged**
