### PR TITLE
Get rid of 'ok-to-merge'

### PR DESCRIPTION
**Pull request by eparis**
https://github.com/kubernetes/kubernetes/issues/24228

### CODE REVIEW

**Comment by eparis** [comment]
@lavalamp @bgrant0607 @david-mcmahon @davidopp

**Comment by bgrant0607** [comment]
Thanks. I agree we should eliminate ok-to-merge

**Comment by lavalamp** [comment]
LGTM

The milestone system is better. ok-to-merge was a hold over from 1.0 code freeze, IMO. Thanks.

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
