### PR TITLE
Remove rebuild-request munger.

### PR DESCRIPTION
**Pull request by spxtr**
Rather than add k8s-merge-robot to the list of OK bot names, lets just delete this munger. We can get this behavior back properly this time by adding it to ciongke.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1781)

### CODE REVIEW

**Comment by spxtr** [comment]
I signed it!

**Comment by apelisse** [comment]
Can you elaborate on the following?

> We can get this behavior back properly this time by adding it to ciongke.

**Comment by spxtr** [comment]
Sure. This just checks for offending retest requests, deletes them, and chastises the author, but the build still runs. Because we now control the actual triggering, we can do it right. We can have it chastise the author and *not* run the build.

**Comment by spxtr** [comment]
Also, right now it seems like everybody just uses "k8s-bot test this issue: #IGNORE", which is terrible. We'll do it better next time.

**Pull request merged**
