### PR TITLE
Change owners

### PR DESCRIPTION
**Pull request by apelisse**
This is WIP.

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1627)

### CODE REVIEW

**Comment by eparis** [comment]
renaming stuff in vendor is a bad idea...

**Comment by apelisse** [comment]
I'm afraid this is true. I'll run a less lenient `find(1)` ..

**Comment by grodrigues3** [comment]
Is there backwards compatibility for repos that haven't been updated with the new OWNERs files updates?

**Comment by apelisse** [comment]
No, that should be added

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by grodrigues3** [comment]
@apelisse Can we delete this PR in favor of #1842  ?

**Comment by apelisse** [comment]
Sure

**Pull request closed without merging**
