### PR TITLE
Submit Queue: Merge on either 'cla: yes' or 'cla: human-approved'

### PR DESCRIPTION
**Pull request by eparis**
Stop paying attention to the github 'status' altogether (as it was
the same as the label, excluding races)

### CODE REVIEW

**Comment by eparis** [comment]
fixes #238

**Comment by eparis** [comment]
I'm testing against a private bot and https://github.com/kubernetes/kubernetes/pull/17235    will update when I know if it is working correctly....

**Comment by zmerlynn** [comment]
I think you mean #236. :)

**Comment by eparis** [comment]
well to be fair, it does also fix itself....

**Comment by brendandburns** [comment]
LGTM.  Travis looks like a flake, I kicked it.

**Comment by zmerlynn** [comment]
Can we merge this?

**Comment by eparis** [comment]
It's merged, but to be honest, I don't plan to build and start a now bot until things are running smoothly again...   I don't want to have to debug bot failures and general falkiness of the bot being able to make progress to the HUGE number of e2e failures at the same time...

I'd rather know if the bot isn't making progress it isn't the bot's fault.

**Pull request merged**
