### PR TITLE
Fix typo and grammatical error

### PR DESCRIPTION
**Pull request by mbssaiakhil**
Fix typo and grammatical error in Kubernetes ZooKeeper

### CODE REVIEW

**Comment by mbssaiakhil** [comment]
@foxish and @eparis , kindly review and merge this change

**Comment by mbssaiakhil** [comment]
@foxish, kindly review and merge the fix in README of zookeeper under statefulsets as well

**Comment by foxish** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
