### PR TITLE
Added scripts for Continuous Delivery using CircleCI and Jenkins

### PR DESCRIPTION
**Pull request by emaildanwilson**
Please review and consider adding this to the contrib repo for others to leverage. Several style choices where made here to make the scripts work well for different CI systems and without much customization to the example kubernetes spec schema provided.

### CODE REVIEW

**Comment by emaildanwilson** [comment]
I signed it!
concurkubecontributers@googlegroups.com

**Comment by emaildanwilson** [comment]
I signed it!

**Comment by emaildanwilson** [comment]
I signed it!

**Comment by emaildanwilson** [comment]
poke. who can I talk to about this to help move it forward?

**Comment by zmerlynn** [comment]
@emaildanwilson: I think it would help if you either tied this to an issue (either in contrib or the main repo) that described the problem you were trying to solve, or the main comment of the PR described more fully what your goals were. We already have a considerable investment already in Jenkins in https://github.com/kubernetes/kubernetes/tree/master/hack/jenkins, for both e2e tests and dockerized unit/integration tests, and it's not immediately obvious where this fits in.

cc @ixdy

**Comment by emaildanwilson** [comment]
Thank you for commenting! The Jenkins work looks great but is very specific to deploying and testing Kubernetes itself. The point of this isn't for that but instead for the use of kubernetes as a deployment target from github projects that are dockerized. For example, we have many different kubernetes clusters running and needed a mechanism to get containers built and deployed onto it for various projects. This provides a set of scripts that can do that, in a fully automated way, for our internal teams that are using circleCI or Jenkins with a common set of scripts. If the community wants to add in functionality to do the same with Travis/Drone/etc. this provides a starting point for them as well and they can contribute back updates. I'll continue to improve these scripts adding features like blue/green and canary testing. I'll add an issue that describes this use case. If I'm missing something and the Jenkins scripts in hack provide this functionality please let me know what I'm missing.
Thank you!

**Comment by stevesloka** [comment]
I did something similar (https://github.com/upmc-enterprises/emmie) to what you are doing @emaildanwilson but more focused around the dev pipeline. My implementation is more geared around the point you have a docker image. This is neat though! I'll dig into your scripts to see if maybe can add some pieces to assist maybe merging this together in the future. 

~ Steve

**Comment by emaildanwilson** [comment]
@brendandburns Thank you for the review. I added in the Author information & missing sudo that you pointed out along with some additional script hardening.

**Comment by emaildanwilson** [comment]
@stevesloka Emmie looks cool too! Thank you for sharing and do let me know if you find a great way to add onto what I'm trying to start here.

**Comment by brendandburns** [comment]
LGTM.  I'm happy to merge this and iterate on making it better.  Dan I'm happy to review future PRs.

**Pull request merged**
