### PR TITLE
Mungebot: Inactivity pinger

### PR DESCRIPTION
**Pull request by Quentin-M**
Hi,

That is a first draft intended to improve the mungebot by implementing two specific points from #869:

> - Ping the PR due to lack of inactivity, notifying either the PR author or the assignee, depending on who last touched the PR (keep track of whose court it's in)
> - Create a way to postpone the next ping for a fixed amount of time (day, week, month, next release cycle)

This new munger comments PRs when:
- No answer has been given for 2 weeks on the PR
- No answer has been given for 2 weeks on any review (code) comment that aren't outdated.

Depending on who commented last, the added comment will either mention (@) the PR assignee or the PR owner.

The next ping can be postponed or cancelled by commenting back:
- `@k8s-merge-robot ignore inactivity`
- `@k8s-merge-robot postpone by X day(s)/week(s)/month(s)`

### CODE REVIEW

**Comment by Quentin-M** [comment]
@bgrant0607 You might be interested in this PR.

**Comment by bgrant0607** [comment]
Thanks @Quentin-M !

Actually, my main motivation for this is to move PRs through the process more quickly. 2 weeks isn't going to help a lot with that.

PTAL at #869 if you haven't already.

Ideally, we'd check whether the comments within the last hour contained a notification and, if not, post a comment with a notification to the appropriate person that action is required. After that, perhaps a ping every day for the first week and a ping a week after that.

Also, we'll need to combine this with other automation eventually, such as to automatically assign PRs where the assignee never responded (maybe by just unassigning here) and automatically closing PRs where the author never responded.

cc @apelisse @fejta @eparis

**Comment by bgrant0607** [comment]
@Quentin-M are you still working on this?

Note that github doesn't send notifications when changes are pushed (which would be another good thing to add).

**Comment by apelisse** [comment]
Note that has many similarity with #891

**Comment by Quentin-M** [comment]
@bgrant0607 Hi! Thanks for the feedback. I am afraid I won't have time to get back on that PR for the next few weeks.

As @apelisse and you mentioned, I believe too it that it could be great to combine some mungers/features here eventually as this munger generates a good amount of API requests to load all the comments.

**Comment by bgrant0607** [comment]
@Quentin-M #891 was merged, so I'm going to close this PR. If you do have time to help, please join the contributor experience working group. https://groups.google.com/forum/#!forum/kubernetes-wg-contribex

**Pull request closed without merging**
