### PR TITLE
Don't file individual issues when big groups of tests fail.

### LINKED ISSUE #1071: Submit queue: don't file individual flake issues when groups of tests fail in a suite
It's too noisy.

Alternatively, file each issue but also file an issue for the group and cross-link.

### PR DESCRIPTION
**Pull request by lavalamp**
Fixes #1071

Builds on #1070. Only the last commit is new.

### CODE REVIEW

**Comment by eparis** [comment]
rebase :-(

**Comment by lavalamp** [comment]
Rebased! ...but this could use some manual testing soak time still.

**Comment by lavalamp** [comment]
Example: https://github.com/lavalamp/issue-testing/issues/107

**Comment by lavalamp** [comment]
This did good things to my test repo overnight so I think I'm OK with pushing it live.

**Comment by lavalamp** [comment]
Fixed lint error (don't use 'self'??? wtf!)

**Pull request merged**
