### PR TITLE
Mutiarch addon-resizer image

### PR DESCRIPTION
**Pull request by mkumatag**
This PR is for creating multi architecture image for addon-resizer

### CODE REVIEW

**Review by luxas — APPROVED** [review]
LGTM!
Thanks @mkumatag!

cc @MrHohn @ixdy @bowei

**Comment by piosz** [comment]
FYI the repo was migrated to https://github.com/kubernetes/autoscaler/tree/master/addon-resizer

**Comment by luxas** [comment]
@piosz Why wasn't the code moved over completely with a redirect link as the only thing here then?
No problem for @mkumatag to just change repo, but very confusing indeed for others.

**Comment by mkumatag** [comment]
@luxas I'll move the code.

**Comment by piosz** [comment]
see #2639

**Comment by mkumatag** [comment]
Opened PR in autoscaler - https://github.com/kubernetes/autoscaler/pull/182

**Pull request closed without merging**
