### PR TITLE
Remove /lgtm munger.

### PR DESCRIPTION
**Pull request by spxtr**
Should go in around the same time as https://github.com/kubernetes/test-infra/pull/985.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1987)

### CODE REVIEW

**Comment by apelisse** [comment]
You have no idea how happy I am to see this gone

**Comment by foxish** [comment]
Looks like this change doesn't compile.

> # k8s.io/contrib/mungegithub/mungers
> mungers/approval-handler.go:86: undefined: getCommentsAfterLastModified
> godep: go exit status 2

**Comment by apelisse** [comment]
Yeah, I've noticed. Still lgtm once it does (it removes a function used
somewhere else in the package)

**Comment by apelisse** [comment]
Still good, if not better :-)

**Comment by apelisse** [comment]
`prow` should go first. Both at the same time should still work.

**Comment by foxish** [comment]
and then let's run a test PR before merging this?

**Comment by spxtr** [comment]
:)

**Comment by foxish** [comment]
That's awesome :)

**Comment by foxish** [comment]
@apelisse let's see you try :)

**Comment by spxtr** [comment]
https://github.com/kubernetes/kubernetes/pull/34864#issuecomment-258288047

**Comment by spxtr** [comment]
(once we're gating on approval rather than lgtm we can get rid of that check)

**Pull request merged**
