### PR TITLE
[ubuntu-slim]: Remove sh sed replacement

### PR DESCRIPTION
**Pull request by aledbf**

### CODE REVIEW

**Comment by ixdy** [comment]
/lgtm

I guess I can just force-push over the published 0.6, since I don't think anyone is using it yet...

or just make an 0.7.

**Comment by aledbf** [comment]
> I guess I can just force-push over the published 0.6

👍

**Comment by ixdy** [comment]
Pushed a new 0.6.

**Comment by aledbf** [comment]
Awesome. Again thank you for the help!

**Pull request merged**
