### PR TITLE
Disable auto-scaling e2e in merge queue, its being flaky

### PR DESCRIPTION
**Pull request by brendandburns**
@fabioy @quinton-hoole

### CODE REVIEW

**Comment by fabioy** [comment]
LGTM.

**Comment by fabioy** [comment]
I'll file an issue to have this re-enabled. Thanks.

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
The reason we're removing this--

We added that test to the list while it was still not stable, and we never got it into the stable state. So it doesn't make sense to start blocking merges on it until it becomes stable again.

**Comment by quinton-hoole** [comment]
LGTM, but is there an issue to debug it and put put it back in this list once it's fixed?

**Comment by brendandburns** [comment]
@fabioy said he was filing one...

**Pull request merged**
