### PR TITLE
Add a 'kind/old-docs' label to PRs which touch files moving out of tree

### PR DESCRIPTION
**Pull request by eparis**
... as we split the docs to their own repo

### CODE REVIEW

**Comment by eparis** [comment]
@bgrant0607

**Comment by eparis** [comment]
@johndmulhausen

**Comment by bgrant0607** [comment]
Awesome! LGTM!

Side note: I noticed is that docs/proposals are labeled kind/design but docs/design are not so labeled. They probably should be.

**Comment by bgrant0607** [comment]
It doesn't look like Travis checks anything that this could break, so I'm going to merge.

**Comment by bgrant0607** [comment]
@eparis I assume someone on our side needs to rebuild, push, and deploy the munger?

**Comment by eparis** [comment]
I can do that too, let me fix docs/design first.

**Pull request merged**
