### PR TITLE
Remove all the things.

### PR DESCRIPTION
**Pull request by apelisse**
A PR to test approvers.  Ignore this

### CODE REVIEW

**Comment by bprashanth** [comment]
eh? I don't think we're actually ready to do this, are we? 
Plus it will probably break doc links so suggest leaving it for now, till the defragmentation propagates through the internet. Can we make it ro somehow?

**Comment by grodrigues3** [comment]
**TESTING**
[APPROVALNOTIFIER] Needs approval from someone in each of the following OWNERS Files:

/OWNERS
404-server/OWNERS
addon-resizer/OWNERS
We suggest the following people:
cc
You can indicate your approval by writing /approve in a comment
You can cancel your approval by writing /approve cancel in a comment

**Comment by lavalamp** [comment]
Let's make more innocuous test PRs just in case they exercise a bug and actually get merged...

**Pull request closed without merging**
