### PR TITLE
CoreOS Support: fix detection of CoreOS related tasks

### LINKED ISSUE #599: Ansible: CoreOS Support breaks RHEL Support
By introducing support for CoreOS, I can no longer run playbook on RHEL. 

```vim
05:37:33 TASK: [common | Set the bin directory path for CoreOS] ************************ 
05:37:33 fatal: [10.8.55.250] => error while evaluating conditional: ansible_lsb.id == "CoreOS"
```

When running

```
ansible --inventory-file=INVENTORY_FILE masters -m setup
```

ansible_lsb is not defined.

What about to use ``ansible_distribution`` instead of ``ansible_lsb``?

[1] https://github.com/kubernetes/contrib/pull/548

### PR DESCRIPTION
**Pull request by ingvagabund**
Currently, the playbook is broken on RHEL due to undefined facts:

* change ansible_lsb.id to ansible_distribution
* install flannel from github only on CoreOS

Fixes #599

### CODE REVIEW

**Comment by ingvagabund** [comment]
Fixes https://github.com/kubernetes/contrib/issues/599

**Comment by ingvagabund** [comment]
@eparis can you review? With this patch the playbook is running on RHEL again.

**Comment by ncdc** [comment]
@ingvagabund FYI you need to put the "fixes" text in the description, not in the 1st comment if you want it to close the issue automatically when this is merged.

**Comment by ingvagabund** [comment]
@ncdc did not know that, thanks.

**Comment by danehans** [comment]
@ingvagabund @eparis Sorry for the breakage of non-CoreOS systems. I will connect with @eparis to figure out a plan to avoid future patches from breaking non-CoreOS systems. Unfortunatly, your patch broke CoreOS :-)

Ansible is unable to obtain the distro information using the ansible_distribution fact. I have created the following issue with Ansible:

https://github.com/ansible/ansible/issues/15096

Until the above issue is resolved, we must use the ansible_lsb fact. I believe the root of the breakage was b/c I was not initializing the is_coreos = false fact. I will submit a new PR that reverts ansible_distribution to ansible_lsb for CoreOS conditionals.

**Comment by danehans** [comment]
Here is an example facts output that details the issue:

https://gist.github.com/danehans/dc7081b4ac5dfe857cfe#file-coreos_ansible_facts-L99-L102

**Pull request merged**
