### PR TITLE
Update controller.go

### LINKED ISSUE #1592: Nginx Ingress Controller not enabling TLS/HTTPS
Following https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/tls and other examples there I my Nginx Ingress works on HTTP but refuses to connect on port 443 even when I'm directly on that Pod. The generated `nginx.conf` does not contain any `443`, and my Ingress definition worked on GCE Ingress.

Another strange thing is that https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/tls describes the _standard_ `tls.key` and `tls.crt` (also used by GCE Ingress) but then https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/tls/dhparam.sh generates a `dhparam.pem` and I also get a matching warning from Nginx Ingress Controller:

```
ssl.go:132] no file dhparam.pem found in secrets
```

Possibly related to https://github.com/kubernetes/contrib/issues/1525

### PR DESCRIPTION
**Pull request by wernight**
Better error message when there is no secretName provided.

Fixes #1592

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1594)

### CODE REVIEW

**Comment by wernight** [comment]
I signed it! (I'm a Googler)

**Comment by aledbf** [comment]
LGTM

**Comment by bprashanth** [comment]
LGTM thanks

**Comment by bprashanth** [comment]
@wernight it didn't pick up your proclamation unfortunately, give it another shot without the suffix?

**Comment by wernight** [comment]
Rebased

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by wernight** [comment]
"I signed it!" (Googler)

**Comment by foxish** [comment]
@wernight Did you sign the CNCF CLA with your github account and Google credentials? It appears to think that you have not. If you have issues, please report them at https://github.com/kubernetes/kubernetes/issues/27796

**Comment by wernight** [comment]
As a Googler I cannot and shouldn't sign the CLA IMO.

**Comment by foxish** [comment]
@wernight Googlers do need to sign I think. 
@sarahnovotny, can you comment on this?

**Comment by bprashanth** [comment]
@wernight are you contributing as yourself or as an employee of google? you won't be recognized as a googler unless you use your @google.com address on github/git commits.

**Comment by wernight** [comment]
I don't use my @google in general for GitHub, but I also know that we're not supposed to sign CLA except a few ones. So I'm not sure how to proceed.

**Comment by bprashanth** [comment]
Ill ping you

**Comment by wernight** [comment]
Performed all the steps except changing the email in the commit.

**Comment by bprashanth** [comment]
i think you need to sign into the linuxfoundation thing at least once with your github account, sorry for the hoops

**Comment by bprashanth** [comment]
looks like you also need a rebase

**Comment by grodrigues3** [comment]
[APPROVALNOTIFIER] The Following OWNERS Files Need Approval:

- **ingress**

We suggest the following people:
cc @lavalamp 
 You can indicate your approval by writing `/approve` in a comment
 You can cancel your approval by writing `/approve cancel`in a comment

**Pull request closed without merging**
