### PR TITLE
pre-install python to work with ubuntu 16.04 or newer

### PR DESCRIPTION
**Pull request by tuannvm**

### CODE REVIEW

**Comment by tuannvm** [comment]
Hi, I signed it!
--
Tuan Nguyen
DevOps

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by tuannvm** [comment]
Hi, I've signed the Contributor License Agreement (CLA).

**Comment by ingvagabund** [comment]
@tuannvm  just ``I signed it!`` should do

**Comment by tuannvm** [comment]
I signed it!

**Comment by ingvagabund** [comment]
Let's see what the bot will do about doing that manually.

**Pull request merged**
