### PR TITLE
Remove gce-scalability from blockers list

### PR DESCRIPTION
**Pull request by gmarek**
cc @eparis @lavalamp

### CODE REVIEW

**Comment by lavalamp** [comment]
Why? Are we turning this job down?

**Comment by wojtek-t** [comment]
@lavalamp - I'm also not 100% convinced. But the rationale behind this is that we have kubemark500 that is blocking.

**Comment by lavalamp** [comment]
If we're confident in kubemark 500, then maybe we should also make
scalability a once-per-day thing, since it's expensive?

**Comment by gmarek** [comment]
We'll be running it twice daily, but we don't want to block on that.

**Comment by lavalamp** [comment]
OK, so you're running it less often. LGTM

**Pull request merged**
