### PR TITLE
Use ubuntu-slim image

### PR DESCRIPTION
**Pull request by aledbf**
This PR removes the use of `alpine` as base image in:
- keepalived
- haproxy image
- nginx-slim image
- nginx-third-party controller
- service-loadbalancer

### CODE REVIEW

**Comment by aledbf** [comment]
ping @bprashanth

**Comment by bprashanth** [comment]
You're using debian-slim not ubuntu? also what's the motivation behind the change? I know alpine has some caveats like dns search path, but is there something more going on?

**Comment by bprashanth** [comment]
I was looking at a stale commit, you're using ubuntu-slim indeed. Question about how ubuntu-slim > alpine:edge still stands.

**Comment by bprashanth** [comment]
LGTM when you fix the merge conflicts

**Comment by bprashanth** [comment]
Ah, turns out the dependency is between this make file whic produces the new nginx-slim based on ubuntu, and the controller Dockerfile which runs apt-get in the other pr. So can't push out nginx-third-party till this one goes in.

**Pull request merged**
