### PR TITLE
Redirect on x-forwarded-for=http in echoserver.

### PR DESCRIPTION
**Pull request by bprashanth**
Anyone sending x-forwarded-for probably cares about the protocol, @aledbf

### CODE REVIEW

**Comment by aledbf** [comment]
LGTM

**Comment by bprashanth** [comment]
Thanks merging

**Comment by carsonoid** [comment]
This commit broke the ingress example. Shouldn't we only redirect to https when `$http_x_forwarded_proto` is `https` **not** when it's `http` as is set by this commit. Currently it always redirects all http traffic to https which makes no sense when testing ingress.

**Comment by bprashanth** [comment]
Can you elaborate? the point is to redirect all http to https

**Comment by bprashanth** [comment]
You can use 1.2 to just get the old non-redirect

**Comment by carsonoid** [comment]
That's what I ended up doing. The ingress example docs should probably be
updated though.

**Pull request merged**
