### PR TITLE
add provision script inline settings to fix #190

### LINKED ISSUE #190: [vagrant openstack] 'run_provisioner': Catched Error: Catched Error: uninitialized constant
Vagrant Installed Version: 1.7.4

Running ansible vagrant with the openstack provider I hit the error below after doing vagrant up.  A quick google suggested a workaround but not sure if thats acceptable.  I'll submit a pr just in case it is.

```
/Users/jamesrawlings/.vagrant.d/gems/gems/vagrant-openstack-provider-0.7.0/lib/vagrant-openstack-provider/action/provision.rb:34:in `run_provisioner': Catched Error: Catched Error: uninitialized constant VagrantPlugins::Shell::Provisioner (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'	
```

Workaround came from..
https://github.com/ggiamarchi/vagrant-openstack-provider/issues/240#issuecomment-144511022

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
I signed it!

**Comment by eparis** [comment]
I don't understand vagrant what so ever.  But this does still all the running of the ansible provision playbooks correctly?

**Comment by rawlingsj** [comment]
I guess this is one of the drawbacks of Vagrant, unless there are automated tests setup then changes to the vagrantfile become very hard.  I dont have a dev environment set up for libvirt and I have conflicts with existing VMs when trying to run the virtualbox provider.  

FWIW I dont think the virtualbox provider even works because the base box it uses is no longer available, a little google about suggested it should should use `bento/centos-7.1` rather than `chef/centos-7.0`.

It kinda feels like there's a bit of overlap with https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/vagrant.md but there's no openstack provider example in that repo which I what I was looking for and I'm pretty sure it was close to working.

**Comment by eparis** [comment]
I'm assuming I've ignored this long enough that I can close it?
https://github.com/ggiamarchi/vagrant-openstack-provider/issues/240
Seems to indicate this has been fixed.

**Pull request closed without merging**
