### PR TITLE
Expose pprof handlers from healthz

### PR DESCRIPTION
**Pull request by bprashanth**

### CODE REVIEW

**Comment by girishkalele** [comment]
Looks correct - I have a similar patch for kube-dns.

Do we want this permanently in place or have an alternate debug container ?

**Comment by bprashanth** [comment]
This exposes running goroutines etc, it needs to be part of the same process

**Comment by girishkalele** [comment]
Ack, these hooks are process-private.

**Comment by bprashanth** [comment]
LGTM?

**Pull request merged**
