### PR TITLE
Use http://ci-test.k8s.io/ for links on SQ dashboard

### LINKED ISSUE #726: e2e links on submit queue dashboard are broken
Links on http://submit-queue.k8s.io/#/e2e are currently broken. 

/cc @spxtr

### PR DESCRIPTION
**Pull request by ixdy**
Fixes #726 once kubernetes/kubernetes#20161 is fixed.

@spxtr @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
lgtm

**Comment by eparis** [comment]
@ixdy so https://github.com/kubernetes/contrib/pull/699 should be closed?

**Comment by ixdy** [comment]
@eparis I didn't see that one, oops. #699 would work now, though I would like to use ci-test.k8s.io instead, so that we have fewer places to change should the URL change again.

**Comment by eparis** [comment]
I merged #699 so this will need a rebase when it is unblocked.  (I see #699 as a hack to get us working and this as the real fix)

**Comment by ixdy** [comment]
Rebased. ci-test.k8s.io should do the right thing now, e.g. http://ci-test.k8s.io/kubernetes-e2e-gce/15151/

At some point we may change ci-test.k8s.io to point to #810 instead.

**Comment by eparis** [comment]
if the links are live, click merge. LGTM.

**Comment by eparis** [comment]
I tested myself, and they work.

**Pull request merged**
