### PR TITLE
Add --api-override flag to allow overriding exporter's stackdriver endpoint

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref: https://github.com/kubernetes/contrib/pull/2414#issuecomment-285343716

cc @piosz @mwielgus

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by mwielgus** [comment]
register the flag in /hack/known-flags.

**Comment by shyamjvs** [comment]
Done.

**Comment by piosz** [comment]
```
'gofmt -s' needs to be run on the following files: 
./prometheus-to-sd/main.go
```

**Comment by shyamjvs** [comment]
Sorry for the blooper. PTAL now

**Pull request merged**
