### PR TITLE
fix bug in auto prioritization

### PR DESCRIPTION
**Pull request by freehan**

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM but I think a test broke

**Comment by eparis** [comment]
```
--- FAIL: TestAutoPrioritize (0.00s)
	flake-manager_test.go:151: Expected priority: 1, But got: 2
	flake-manager_test.go:151: Expected priority: 0, But got: 2
	flake-manager_test.go:151: Expected priority: 1, But got: 2
	flake-manager_test.go:151: Expected priority: 1, But got: 2
	flake-manager_test.go:151: Expected priority: 0, But got: 2
```

**Comment by freehan** [comment]
Test Fixed.

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
We'll get this in the next push.

**Pull request merged**
