### PR TITLE
[mungegithub] Only request 40px avatars.

### PR DESCRIPTION
**Pull request by rmmh**

### CODE REVIEW

**Comment by eparis** [comment]
would we rather do it on the server side, since it would be smaller easier?  maybe not...

**Comment by eparis** [comment]
by updating https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/submit-queue.go#L467 I think?

**Comment by ixdy** [comment]
I have no strong opinion. The image size is specified in CSS, which is pretty far away from the place we reference the URL already.

**Comment by rmmh** [comment]
Since the width:40px is in the CSS, I thought doing this in the JS keeps the modifications for display as localized to the presentation layer as possible.

**Pull request merged**
