### PR TITLE
Do Not Merge docs\design devel or proposal

### PR DESCRIPTION
**Pull request by grodrigues3**
Those have been moved to the community repository and the changes should be made there instead.

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/2101)

**Comment by bgrant0607** [comment]
LGTM

**Comment by ixdy** [comment]
Feedback - the message posted by the bot on affected PRs
> Adding label:do-not-merge because PR changes docs prohibited to auto merge
See http://kubernetes.io/editdocs/ for information about editing docs

was 100% unhelpful, since it made no reference to the devel docs moving to the community repository. I'm pretty sure this message dates back to when we moved user docs out of kubernetes/kubernetes, and I was really confused why it was posting on my PR which only affected devel docs.

Too late to do anything now, but worth considering for future changes.

**Comment by jbeda** [comment]
This caught me too. Totally unhelpful.

**Pull request merged**
