### PR TITLE
Remove kops from sq blockers

### PR DESCRIPTION
**Pull request by gmarek**
Somehow it just breaks after we start blocking on it...

### CODE REVIEW

**Comment by dims** [comment]
+1 LGTM 👍

**Comment by gmarek** [comment]
after this change SQ was panicking with an error that `stale-pending-ci` was not found. I removed it from munger list, to get it running. @kubernetes/test-infra-maintainers 

We should merge this ASAP, to have consistent configs in repo and in running instance.

**Comment by eparis** [comment]
Why did stale-pending-ci get removed as part of this change? Why do we keep trying to insert unrelated stuff into PRs? Please no.

**Comment by dims** [comment]
@eparis : context from slack

```
[08:28:58]  <dims>	@gmarek : lgtm-ed, waiting for the "Travis CI build in progress" to finish
[08:33:24]  <gmarek>	wait
[08:33:29]  <gmarek>	I restarted SQ
[08:33:33]  <gmarek>	and got an error
[08:34:18]  <dims>	ack waiting
[08:34:25]  <gmarek>	or rather panic
[08:34:34]  <gmarek>	that `stale-green-ci` munger is not found
[08:34:37]  <gmarek>	so I disabled it
[08:34:43]  <gmarek>	sory
[08:34:44]  <gmarek>	sorry
[08:34:52]  <gmarek>	`stale-pending-ci`
[08:34:56]  <gmarek>	not `green`
[08:35:27]  <gmarek>	SQ seems to be up now
```

**Comment by eparis** [comment]
What changed to cause this problem? Why couldn't that be in its own PR which would make sense to discuss it?

/me goes to try to reproduce.

**Comment by fejta** [comment]
@eparis please work with @rmmh and @spxtr on this. The feedback I have from them is that this munger is causing problems.

**Pull request merged**
