### PR TITLE
Support SSL bridge mode with HAProxy and ACLs per ServicePort

### PR DESCRIPTION
**Pull request by ravihansa3000**
This pull request adds support for SSL Bridge mode (re-encrypt client side traffic using LB cert) with HAProxy and ACLs per ServicePort.
Instructions are added to README. A test case is added with full regression checks.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1624)

### CODE REVIEW

**Comment by ravihansa3000** [comment]
I signed it!

**Comment by ravihansa3000** [comment]
@bprashanth would you be able to have a look at this please?

Basically it adds 2 things;
 - Support for end-to-end TLS/SSL (secured backends in HAProxy)
 - ACLs per ServicePort. Currently "lb.aclMatch" and "lb.host" annotations get applied globally for all ServicePorts. This PR keeps that behavior as it is but allows you to define ACL rules per ServicePort using annotations.

We are currently using this approach in our internal fork. Thought this might help a wider audience. Please let me know if there is a better way to do this.

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by ravihansa3000** [comment]
I signed it!

**Comment by grodrigues3** [comment]
[APPROVALNOTIFIER] The Following OWNERS Files Need Approval:

- **service-loadbalancer**

We suggest the following people:
cc @bprashanth 
 You can indicate your approval by writing `/approve` in a comment
 You can cancel your approval by writing `/approve cancel`in a comment

**Pull request closed without merging**
