### PR TITLE
Cluster-Autoscaler: remove all code - the project has moved to https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler

### PR DESCRIPTION
**Pull request by mwielgus**
Ref: #2533

cc: @MaciekPytel @piosz @jszczepkowski @fgrzadkowski @andrewsykim @mumoshu @Raffo

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@mwielgus maybe it would be also worth adding a "redirect" FAQ.md? I believe I've seen people send direct links to faq already.

**Comment by mwielgus** [comment]
@MaciekPytel  good point - fixed.

**Comment by fgrzadkowski** [comment]
Is anyone using cluster autoscaler? For example have you updated rescheduler?

**Comment by mwielgus** [comment]
Rescheduler has CA in vendor - it will have to be updated on the earliest convenience. 
The whole contrib compiled so I guess noone used CA directly.

**Comment by fgrzadkowski** [comment]
Great. Thanks for checking.

--
Filip

**Pull request merged**
