### PR TITLE
Reverting commit to README.md.

### PR DESCRIPTION
**Pull request by foxish**
Edited using the web UI :(

### CODE REVIEW

**Comment by lavalamp** [comment]
Web UI is dangerous for those of us with powers :)

**Comment by foxish** [comment]
Duly noted. Bad habits from when I didn't have powers. :)

**Comment by apelisse** [comment]
> Duly noted. Bad habits from when I didn't have powers. :)

That doesn't make any sense! Did you get the habit of clicking, changing the text and getting permissions denied? :-D

**Comment by foxish** [comment]
Oh, without powers, it creates a branch and makes a PR when I try to edit something if I recall correctly.

**Pull request merged**
