### PR TITLE
Allow new/changed scripts to run again

### PR DESCRIPTION
**Pull request by jayme-github**
Small change that allows to change scripts at node runtime and have
them run "again" without the need to manually change or remove $CHECKPOINT_PATH.

### CODE REVIEW

**Comment by jayme-github** [comment]
I signed it!

**Comment by tback** [comment]
CLA is signed now.

**Comment by jayme-github** [comment]
Is there anything I can do to get this reviewed?

**Comment by lavalamp** [comment]
Looks like @mikedanese knows something about this directory. (Mike, can you add an OWNERS file and a README here? I was only able to figure out what this was due to your initial commit comment :) )

**Comment by jayme-github** [comment]
Thanks! What's the process for actually updating the image? Should I have increased the version number in `Makefile`?

**Pull request merged**
