### PR TITLE
Remove serve_hostname

### LINKED ISSUE #2690: Remove serve_hostname code
serve_hostname is already present in https://github.com/kubernetes/kubernetes/tree/master/test/images/serve-hostname and maintained by test team for e2e tests, so no need to have duplicate code in contrib repo as well.

### PR DESCRIPTION
**Pull request by mkumatag**
Fixes #2690

### CODE REVIEW

**Comment by ixdy** [comment]
Is this used/referenced outside of e2e tests?

**Comment by mkumatag** [comment]
I see that this image used in couple of places in documentation, but we can modify the document with updated link to `gcr.io/kubernetes-e2e-test-images/serve-hostname-amd64` as this moved to `test/images` long back and maintained there!

IMO - maintaining these images in multiple places is always a headache..

**Comment by pwittrock** [comment]
@kubernetes/sig-testing-pr-reviews

**Comment by ixdy** [comment]
The travis failure looks legitimate.

**Comment by spiffxp** [comment]
/assign
closing to retrigger travis

**Comment by ixdy** [comment]
travis doesn't merge against the upstream head, it just uses the fork. if there were upstream changes, this PR will need to rebase to pull them in.

**Comment by spiffxp** [comment]
@mkumatag see @ixdy's comment above, you'll probably need to rebase for travis to pass 

I had my PR pass travis and get merged once I rebased to pull in https://github.com/kubernetes/contrib/pull/2707

**Comment by mkumatag** [comment]
@spiffxp rebased to upstream master, not really /retest will rerun the travis job or not!

**Comment by mkumatag** [comment]
Tests are still failing because of no tests found after removing this gocode from `for-demos` directory. As no more gocode present in `for-demos` directory, I'll have to delete Godep directory to pass the tests. Deleting the Godep directory to skip this folder while running `hack/for-go-proj.sh test`

**Comment by mkumatag** [comment]
@ixdy @spiffxp Tests are green now, can you please gimme lgtm to merge?

**Comment by spiffxp** [comment]
/lgtm
/assign @pwittrock @mikedanese 
for the /approve

**Comment by mkumatag** [comment]
ping @pwittrock @mikedanese

**Comment by spiffxp** [comment]
/unassign
I'm not an approver or reviewer here

**Pull request merged**
