### PR TITLE
Tidy up l7 controller

### PR DESCRIPTION
**Pull request by freehan**
https://github.com/kubernetes/contrib/issues/231

### CODE REVIEW

**Comment by bprashanth** [comment]
Thanks. Please do the following:
1. Remove 231 from title
2. Run `godep go test` in the `controller/` directory (travis should run this but it's red)
3. Please kick off an e2e run and make sure it passes:
  - Turn down any existing glbc pods (scale --replicas=0)
  - Use this yaml to create another rc 
  - run: `you-kubernetes-repo/hack/ginkgo-e2e.sh --ginkgo.focus=GCE.*L7.*`

Otherwise LGTM, will merge when you do those things.

**Comment by freehan** [comment]
Finish all the tests, everything looks good.

**Comment by freehan** [comment]
I have signed!

**Comment by bprashanth** [comment]
oh, please rebase I fixed the travis failure but you still have the old code

**Comment by bprashanth** [comment]
please run hack/verify-all.sh and fix whatever comes up

**Comment by freehan** [comment]
All verification passed.

**Comment by bprashanth** [comment]
Travis doesn't believe you:
```
Verifying hack/../hack/verify-flags-underscore.py
FAILED
The command "hack/verify-all.sh" exited with 1.
```

**Comment by bprashanth** [comment]
Can you also please fix 2 more tidyness things while you're here:
1. These example usage comments are wrong: https://github.com/kubernetes/contrib/blob/master/Ingress/controllers/gce/main.go#L36
2. This default is wrong: https://github.com/kubernetes/contrib/blob/master/Ingress/controllers/gce/main.go#L79 it should be the name of the default service (default-http-backend i think)

You can pick any right examples for the example usage lines (run glbc --running-in-cluster=false and see), if you don't know what to put there please let me know.

**Comment by freehan** [comment]
Is there any way to rerun Travis?

image

**Comment by bprashanth** [comment]
LGTM

**Pull request merged**
