### PR TITLE
unified Ansible syntax

### PR DESCRIPTION
**Pull request by knowhy**
- replace inline with block format
- fix incorrect `=` block indicator

### CODE REVIEW

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by ingvagabund** [comment]
```
04:51:18 ERROR! Syntax Error while loading YAML.
04:51:18 
04:51:18 
04:51:18 The error appears to have been in '/home/jenkins/workspace/ansible-github-pr-rhel-worker-2-2-runtest/contrib/ansible/roles/docker/handlers/main.yml': line 45, column 58, but may
04:51:18 be elsewhere in the file depending on the exact syntax problem.
04:51:18 
04:51:18 The offending line appears to be:
04:51:18 
04:51:18     dest: "{{ docker_config_dir }}/docker"
04:51:18     regexp: "^(OPTIONS=.*)(--selinux-enabled(?!=false)([^\s\"\']*))"
04:51:18                                                          ^ here
04:51:18 We could be wrong, but this one looks like it might be an issue with
04:51:18 unbalanced quotes.  If starting a value with a quote, make sure the
04:51:18 line ends with the same set of quotes.  For instance this arbitrary
04:51:18 example:
04:51:18 
04:51:18     foo: "bad" "wolf"
04:51:18 
04:51:18 Could be written as:
04:51:18 
04:51:18     foo: '"bad" "wolf"'
```

**Comment by knowhy** [comment]
sorry, my bad.

```
for file in $(ls playbooks/*.yml); do
ansible-playbook --syntax-check ${file}
done
```
runs trough now. I did a `push --force` on my fork. PR seems to have been updated by now.

The errors were in: `ansible/roles/docker/handlers/main.yml` and `ansible/roles/flannel/handlers/main.yml`.

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by ingvagabund** [comment]
```
10:53:50 RUNNING HANDLER [master : restart controller-manager] **************************
10:53:52 fatal: [10.8.172.224]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service kube-controller-managerd: cannot check nor set state"}
```

**Pull request closed without merging**
