### PR TITLE
Create container for mailing via remote smtp

### PR DESCRIPTION
**Pull request by krousey**
Note there is already a Makefile in this directory. This means that both

``` console
> APP=shame-mailer make
> APP=shame-mailer make push
```

work. I have not run `APP=shame-mailer make push` yet.

cc @lavalamp @ixdy @fejta

### CODE REVIEW

**Comment by krousey** [comment]
Meant to be run with environment variables bound like

```console
> docker run -e GITHUB_API_TOKEN=$GITHUB_API_TOKEN -e SHAME_FROM=$SHAME_FROM -e SHAME_REPLY_TO=$SHAME_REPLY_TO -e SHAME_CC=$SHAME_CC -e SMTP_SERVER=$SMTP_SERVER -e SMTP_USER=$SMTP_USER -e SMTP_PASS=$SMTP_PASS gcr.io/google_containers/shame-mailer:TAG
```

**Comment by ixdy** [comment]
@krousey can you put that in a comment or README somewhere?

**Comment by krousey** [comment]
@ixdy, comment in the Dockerfile ok?

**Comment by lavalamp** [comment]
LGTM - but need to make sure `APP=shame-mailer make push` doesn't do something awful before merging. :)

**Comment by ixdy** [comment]
@krousey Dockerfile sgtm

**Comment by krousey** [comment]
@lavalamp agreed, just didn't want to push a container that didn't get an initial review first. :smile:

I'll update the docker file with a comment, push, and update the PR.

**Comment by krousey** [comment]
Added comment. Fixed flag validation error. Pushed the image to `gcr.io/google_containers/shame-mailer:2016-03-25-d0e88f1`.

@ixdy you should be able to add the job now. Or if you want, you can give me some pointers on how to do it and I can look at it after lunch.

**Comment by eparis** [comment]
I wonder how 'deploy' falls down. Doesn't matter I guess, this is fine with me.

**Comment by ixdy** [comment]
Tested on Jenkins, everything seems to work.

**Pull request merged**
