### PR TITLE
Cluster Autoscaler: update AWS docs to include expansion options 

### PR DESCRIPTION
**Pull request by andrewsykim**
There seems to be some confusion among AWS users regarding how to setup cluster autoscaler with multiple node groups. 

/cc @mwielgus @osxi @mumoshu

### CODE REVIEW

**Comment by mwielgus** [comment]
lgtm

**Comment by mumoshu** [comment]
LGTM 👍

**Comment by andrewsykim** [comment]
actullay @mwielgus I may have made a mistake. does `gcr.io/google_containers/cluster-autoscaler:v0.4.0` support the new expansion options?

**Comment by andrewsykim** [comment]
Just verified that it does not, @mwielgus any chance we can get a alpha/beta image for cluster autoscaler out with the new expander options enabled?

**Pull request merged**
