### PR TITLE
Adding cla-munger.

### PR DESCRIPTION
**Pull request by foxish**
Adding the CLA munger to work with the linux foundation's CLA bot.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1646)

### CODE REVIEW

**Comment by lavalamp** [comment]
Is there a reason why we can't add this functionality to the cncf checker bot?

**Comment by foxish** [comment]
@lavalamp The goal here is to standardize interactions with the bot, which is why we want to add this functionality into the mungegithub bot. The CNCF bot does not notify the user(s) from whom action is required, for example. There is some discussion here in the comments: https://docs.google.com/document/d/1LIwyn5PDSYu8kh-7hH8688lt1cvwATkZmhec13nhp1c/edit#

**Comment by foxish** [comment]
cc @bgrant0607 @emsearcy

**Comment by apelisse** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[mungegithub/github/github.go, line 783 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646#-KQN-KtEJz0f6xKQTRUt:-KQN-KtEJz0f6xKQTRUu:b-9eflnc) ([raw file](https://github.com/kubernetes/contrib/blob/0fdfd0300627f6cdebd9c6c2cce2c9fcb34f38e6/mungegithub/github/github.go#L783)):*
> ```Go
> }
> 
> // AddLabelIfAbsent adds a single `label` to the issue, if it isn't present already.
> ```

I already said that, but I'm not a huge fan here

---

*[mungegithub/mungers/cla.go, line 125 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646#-KQN-mfcDw-SELErFMvb:-KQN-mfd3oQ2vk4WSRmg:b6e8eas) ([raw file](https://github.com/kubernetes/contrib/blob/0fdfd0300627f6cdebd9c6c2cce2c9fcb34f38e6/mungegithub/mungers/cla.go#L125)):*
> ```Go
> 	}
> 	obj.RemoveLabelIfPresent(cncfClaYesLabel)
> 	obj.AddLabelIfAbsent(cncfClaNoLabel)
> ```

It can't be absent because of the check above

---

*[mungegithub/mungers/cla_test.go, line 151 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646#-KQN3SAJvIIPlMnKYC-g:-KQN3SAJvIIPlMnKYC-h:bnk2d2h) ([raw file](https://github.com/kubernetes/contrib/blob/0fdfd0300627f6cdebd9c6c2cce2c9fcb34f38e6/mungegithub/mungers/cla_test.go#L151)):*
> ```Go
> 
> func setUpMockFunctions(mux *http.ServeMux, t *testing.T, issue *github.Issue) {
> 	path := fmt.Sprintf("/repos/o/r/issue/%d/labels", *issue.Number)
> ```

I think these should leave in `mungegithub/github/testing` (even if it's becoming more messy everytime ... :-/)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646)*

**Comment by apelisse** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646)*

**Comment by foxish** [comment]
*[mungegithub/mungers/cla_test.go, line 151 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646#-KQN3SAJvIIPlMnKYC-g:-KQNFkg1bqaJHLBuzXVk:b-bj3a77) ([raw file](https://github.com/kubernetes/contrib/blob/0fdfd0300627f6cdebd9c6c2cce2c9fcb34f38e6/mungegithub/mungers/cla_test.go#L151)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> I think these should leave in `mungegithub/github/testing` (even if it's becoming more messy everytime ... :-/)
</details>
Some of these cannot live within the testing because they depend on the issues and PRs which are created in the test itself. These two could move, but I'd like to fix the testing portion the right way. I've opened an issue https://github.com/kubernetes/contrib/issues/1654 to refactor it. 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646)*

**Comment by foxish** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mungegithub/mungers/cla.go, line 125 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646#-KQN-mfcDw-SELErFMvb:-KQNFE_zJfLd3iUmZ5CN:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/0fdfd0300627f6cdebd9c6c2cce2c9fcb34f38e6/mungegithub/mungers/cla.go#L125)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> It can't be absent because of the check above
</details>
Done.

---

*[mungegithub/github/github.go, line 783 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646#-KQN-KtEJz0f6xKQTRUt:-KQNFFFEDH1PNzG268t9:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/0fdfd0300627f6cdebd9c6c2cce2c9fcb34f38e6/mungegithub/github/github.go#L783)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> I already said that, but I'm not a huge fan here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646)*

**Comment by apelisse** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646)*

**Comment by apelisse** [comment]
/lgtm

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1646#-:-KQNUmtICOYUtevd6ufW:b-8ks5qa)*

**Pull request merged**
