### PR TITLE
Add fragment perma-links to the tabs in the merge-queue UI.

### PR DESCRIPTION
**Pull request by brendandburns**
Ref #462 

@roberthbailey @eparis

### CODE REVIEW

**Comment by roberthbailey** [comment]
lgtm.

**Comment by eparis** [comment]
I thought it wasn't working, then remembered I had to cntrl-f5 to get it to reread the javascript for some reason.

**Comment by eparis** [comment]
e2e tests were broken, so I pushed it live.

**Comment by roberthbailey** [comment]
Thanks... this is so much better. :smile:

**Pull request merged**
