### PR TITLE
Release version 0.6

### PR DESCRIPTION
**Pull request by aledbf**
Check https://quay.io/repository/aledbf/ubuntu-slim?tab=tags

### CODE REVIEW

**Comment by ixdy** [comment]
/lgtm

though I don't know if that's good enough anymore.

**Comment by grodrigues3** [comment]
@ixdy It should be good enough.  There's seems to be some problem with the approvers-handlers detecting its old comments, so turning it off for now.

**Comment by ixdy** [comment]
Pushed `gcr.io/google_containers/ubuntu-slim:0.6`.

**Comment by aledbf** [comment]
@ixdy thanks!

**Comment by ixdy** [comment]
though it occurs to me that you might not need `RUN sed -i 's/bash/sh/g' /etc/passwd` anymore.

**Comment by aledbf** [comment]
@ixdy you are right. PR #2267 fixes that

**Pull request merged**
