### PR TITLE
Ansible: Add network service tags

### PR DESCRIPTION
**Pull request by galthaus**
Addresses - #276

### CODE REVIEW

**Comment by eparis** [comment]
@pedro-r-marques your thoughts?

**Comment by pedro-r-marques** [comment]
@eparis If i understand correctly, Greg is trying to have the same install workflow independently of the network provider. Thus his workflow engine [https://github.com/digitalrebar] can invoke the same sequence of steps (in kubernetes ansible) regardless of provider. The workflow tool is most likely invoking plays as independent steps (which i believe makes sense); rather than the full playbook.

**Comment by eparis** [comment]
@pedro-r-marques and thus you are fine with this change?

**Comment by pedro-r-marques** [comment]
@eparis yes.

**Pull request merged**
