### PR TITLE
Cluster-autoscaler: readable status printing

### PR DESCRIPTION
**Pull request by MaciekPytel**
Example output (github seems to slightly mess up tabs):
```
Health:      Healthy (ready=0 unready=1 notStarted=0 longNotStarted=0 registered=1)
             LastProbeTime:      0001-01-01 00:00:00 +0000 UTC                     
             LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC                     
ScaleUp:     NoActivity (ready=0 registered=1)                                     
             LastProbeTime:      0001-01-01 00:00:00 +0000 UTC                     
             LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC                     
ScaleDown:   NoCandidates (candidates=0)                                           
             LastProbeTime:      0001-01-01 00:00:00 +0000 UTC                     
             LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC                     
                                                                                   
NodeGroups:                                                                        
  Name:        ng1                                                                 
  Health:      Unhealthy (ready=0 unready=1 notStarted=0 longNotStarted=0 registered=1 cloudProviderTarget=5 (min=5, max=5))
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC                   
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC                   
  ScaleUp:     NoActivity (ready=0 cloudProviderTarget=5)                          
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC                   
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC                   
  ScaleDown:   NoCandidates (candidates=0)                                         
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC                   
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
```

### CODE REVIEW

**Comment by mwielgus** [comment]
lgtm

**Comment by mwielgus** [comment]
Actually one more comment.
Add a header before clusterwide conditions.

**Comment by MaciekPytel** [comment]
@mwielgus done

**Pull request merged**
