### PR TITLE
Cluster-autoscaler: add stateful set support in drain.

### PR DESCRIPTION
**Pull request by mwielgus**
This change will have to be cherry-picked to 0.4.0 release of CA (and K8S 1.5).

cc: @fgrzadkowski @piosz @jszczepkowski

### CODE REVIEW

**Comment by jszczepkowski** [comment]
Please add a unit test for this case.

**Comment by mwielgus** [comment]
Done.

**Comment by jszczepkowski** [comment]
LGTM

**Comment by fgrzadkowski** [comment]
@mwielgus Meta comment - how about CC-ing @kubernetes/sig-autoscaling-misc on cluster autoscaler PRs? This will build awareness in the SIG.

**Pull request merged**
