### PR TITLE
add weights to blunderbuss; add missing files to .yml

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by lavalamp** [comment]
@brendandburns @thockin 

Some output, for example:

```
I0908 15:17:44.456235   11358 blunderbuss.go:118] Weights: pulls.weightMap{"thockin":67, "brendandburns":67, "davidopp":180, "lavalamp":117, "dchen1107":67}
Sum: 498
I0908 15:17:44.456296   11358 blunderbuss.go:129] would have assigned davidopp to PR 13555

```

**Comment by eparis** [comment]
Code LGTM, but I'm afraid it just means those people with their names the most places in the file are going to get all of the assignments...  This will make it a bit less blunderbussy and a bit more pinpointy. And I wonder if pinpointy is going to get @lavalamp (16 references) @thockin (10) and @davidopp (10) the worst. Maybe that's a good thing though, don't get me wrong....

**Comment by lavalamp** [comment]
Yeah I agree that file needs a bunch of tweaking. I'm messing with this because some people (@dchen1107) are complaining that they're rarely chosen. I think this is still an improvement over what's currently running?

Here's some output with what it would have done, compared to the current assignee.

```
I0908 16:05:18.041364    3184 blunderbuss.go:81] Loaded config from blunderbuss.yml
W0908 16:05:18.041470    3184 blunderbuss.go:105] Couldn't find an owner for: api/swagger-spec/v1.json
I0908 16:05:18.041821    3184 blunderbuss.go:118] Weights: pulls.weightMap{"smarterclayton":7152, "eparis":3251, "lavalamp":3294, "jlowdermilk":42, "davidopp":8, "thockin":5768, "brendandburns":3866, "bgrant0607":5810, "erictune":1944, "deads2k":688, "derekwaynecarr":8}
Sum: 31831
I0908 16:05:18.041937    3184 blunderbuss.go:122] Current assignee erictune has a 6.11% chance of having been chosen
I0908 16:05:18.041977    3184 blunderbuss.go:134] would have assigned lavalamp to PR 7893
I0908 16:05:18.042004    3184 pulls.go:105] -=-=-=-=8145-=-=-=-=-
I0908 16:05:26.787466    3184 blunderbuss.go:118] Weights: pulls.weightMap{"thockin":18, "brendandburns":18, "bgrant0607":18, "ixdy":179}
Sum: 233
I0908 16:05:26.787522    3184 blunderbuss.go:122] Current assignee quinton-hoole has a 0.00% chance of having been chosen
I0908 16:05:26.787541    3184 blunderbuss.go:134] would have assigned ixdy to PR 8145
I0908 16:05:26.787550    3184 pulls.go:105] -=-=-=-=8255-=-=-=-=-
I0908 16:05:38.778721    3184 blunderbuss.go:118] Weights: pulls.weightMap{"zmerlynn":28, "brendandburns":28, "eparis":28, "robertbailey":28, "davidopp":28}
Sum: 140
I0908 16:05:38.778778    3184 blunderbuss.go:122] Current assignee brendandburns has a 20.00% chance of having been chosen
I0908 16:05:38.778798    3184 blunderbuss.go:134] would have assigned eparis to PR 8255
I0908 16:05:38.778806    3184 pulls.go:105] -=-=-=-=8647-=-=-=-=-
I0908 16:05:52.791211    3184 blunderbuss.go:118] Weights: pulls.weightMap{"brendandburns":188, "vishh":376, "yujuhong":376, "dchen1107":404, "bgrant0607":160, "lavalamp":12760, "thockin":12920, "quinton-hoole":12732, "smarterclayton":160, "eparis":160, "davidopp":12760}
Sum: 52996
I0908 16:05:52.791379    3184 blunderbuss.go:122] Current assignee dchen1107 has a 0.76% chance of having been chosen
I0908 16:05:52.791451    3184 blunderbuss.go:134] would have assigned thockin to PR 8647
I0908 16:05:52.791482    3184 pulls.go:105] -=-=-=-=8659-=-=-=-=-
W0908 16:06:04.804432    3184 blunderbuss.go:105] Couldn't find an owner for: .travis.yml
W0908 16:06:04.804682    3184 blunderbuss.go:105] Couldn't find an owner for: www/master/components/dashboard/protractor/smoke.spec.js
W0908 16:06:04.804726    3184 blunderbuss.go:105] Couldn't find an owner for: www/master/package.json
W0908 16:06:04.804755    3184 blunderbuss.go:105] Couldn't find an owner for: www/master/protractor/chrome/smoke.spec.js
W0908 16:06:04.804783    3184 blunderbuss.go:105] Couldn't find an owner for: www/master/protractor/conf.js
W0908 16:06:04.804810    3184 blunderbuss.go:105] Couldn't find an owner for: www/test/e2e/protractor.conf.js
W0908 16:06:04.804838    3184 blunderbuss.go:105] Couldn't find an owner for: www/test/e2e/scenarios.js
W0908 16:06:04.804874    3184 blunderbuss.go:105] Couldn't find an owner for: shippable.yml
I0908 16:06:04.804901    3184 blunderbuss.go:118] Weights: pulls.weightMap{"ixdy":172, "eparis":172, "zmerlynn":172, "lavalamp":172}
Sum: 688
I0908 16:06:04.804963    3184 blunderbuss.go:122] Current assignee ixdy has a 25.00% chance of having been chosen
I0908 16:06:04.805002    3184 blunderbuss.go:134] would have assigned zmerlynn to PR 8659
I0908 16:06:04.805026    3184 pulls.go:105] -=-=-=-=8662-=-=-=-=-
W0908 16:06:20.782572    3184 blunderbuss.go:105] Couldn't find an owner for: contrib/completions/bash/kubectl
I0908 16:06:20.782759    3184 blunderbuss.go:118] Weights: pulls.weightMap{"thockin":573, "ixdy":3, "eparis":305, "zmerlynn":3, "deads2k":368, "smarterclayton":941, "brendandburns":941, "bgrant0607":941, "lavalamp":3, "jlowdermilk":368}
Sum: 4446
I0908 16:06:20.782851    3184 blunderbuss.go:122] Current assignee jlowdermilk has a 8.28% chance of having been chosen
I0908 16:06:20.782894    3184 blunderbuss.go:134] would have assigned thockin to PR 8662
I0908 16:06:20.782919    3184 pulls.go:105] -=-=-=-=8832-=-=-=-=-
W0908 16:06:32.790720    3184 blunderbuss.go:105] Couldn't find an owner for: _layouts/generic.html
W0908 16:06:32.790798    3184 blunderbuss.go:105] Couldn't find an owner for: _layouts/gettingstarted.html
W0908 16:06:32.790839    3184 blunderbuss.go:105] Couldn't find an owner for: _sass/_template.scss
W0908 16:06:32.790850    3184 blunderbuss.go:105] Couldn't find an owner for: gettingstarted.md
W0908 16:06:32.790860    3184 blunderbuss.go:105] Couldn't find an owner for: img/desktop/getting_started/k8s-mesos_integration.png
W0908 16:06:32.790871    3184 blunderbuss.go:105] Couldn't find an owner for: img/desktop/getting_started/k8s-on-dcos_arch_overview.png
W0908 16:06:32.790884    3184 blunderbuss.go:105] Couldn't find an owner for: solutions/mesosphere.md
W0908 16:06:32.790895    3184 blunderbuss.go:105] Couldn't find an owner for: Gemfile
E0908 16:06:32.790904    3184 blunderbuss.go:115] No owners found for PR 8832
I0908 16:06:32.790916    3184 pulls.go:105] -=-=-=-=8866-=-=-=-=-
I0908 16:06:42.784588    3184 blunderbuss.go:118] Weights: pulls.weightMap{"eparis":933, "lavalamp":1563, "dchen1107":28, "deads2k":42, "davidopp":98, "bgrant0607":2067, "ixdy":4, "derekwaynecarr":22, "erictune":1134, "zmerlynn":5, "brendandburns":965, "robertbailey":4, "thockin":2095, "smarterclayton":2401}
Sum: 11361
I0908 16:06:42.784721    3184 blunderbuss.go:122] Current assignee erictune has a 9.98% chance of having been chosen
I0908 16:06:42.784771    3184 blunderbuss.go:134] would have assigned lavalamp to PR 8866
```

**Comment by brendandburns** [comment]
this LGTM in general.  I suggested a logarithmic scale for file weights to @lavalamp

--brendan

**Comment by lavalamp** [comment]
I started judging the files on a quantized log scale.

Also added a flag to get the output I pasted above.

**Comment by lavalamp** [comment]
New sample:

```
I0908 16:25:33.438162   18276 pulls.go:105] -=-=-=-=6234-=-=-=-=-
I0908 16:25:33.834567   18276 pulls.go:122] Waiting for mergeability on Eliminate redundant code in network volume plugins. 6234
I0908 16:25:38.011420   18276 blunderbuss.go:82] Loaded config from blunderbuss.yml
I0908 16:25:38.011493   18276 blunderbuss.go:123] Weights: pulls.weightMap{"thockin":51, "saad-ali":34, "brendandburns":17, "bgrant0607":17, "smarterclayton":17, "eparis":17}
Sum: 153
I0908 16:25:38.011516   18276 blunderbuss.go:127] Current assignee ArtfulCoder has a 0.00% chance of having been chosen
I0908 16:25:38.011534   18276 blunderbuss.go:139] would have assigned thockin to PR 6234
I0908 16:25:38.011540   18276 pulls.go:105] -=-=-=-=6245-=-=-=-=-
I0908 16:25:38.388990   18276 pulls.go:122] Waiting for mergeability on Generic Config object and it's REST implementation 6245
I0908 16:25:42.455055   18276 blunderbuss.go:123] Weights: pulls.weightMap{"eparis":11, "deads2k":6, "bgrant0607":17, "thockin":17, "erictune":6, "lavalamp":22, "smarterclayton":33, "brendandburns":11}
Sum: 123
I0908 16:25:42.455130   18276 blunderbuss.go:127] Current assignee bgrant0607 has a 13.82% chance of having been chosen
I0908 16:25:42.455184   18276 blunderbuss.go:139] would have assigned bgrant0607 to PR 6245
I0908 16:25:42.455209   18276 pulls.go:105] -=-=-=-=6438-=-=-=-=-
I0908 16:25:43.816185   18276 pulls.go:122] Waiting for mergeability on Kube2sky exports IP:port pairs of all pods. 6438
I0908 16:25:55.794111   18276 blunderbuss.go:123] Weights: pulls.weightMap{"eparis":7, "thockin":21, "ArtfulCoder":21, "robertbailey":7, "davidopp":7, "zmerlynn":7, "brendandburns":7}
Sum: 77
I0908 16:25:55.794228   18276 blunderbuss.go:127] Current assignee thockin has a 27.27% chance of having been chosen
I0908 16:25:55.794279   18276 blunderbuss.go:139] would have assigned robertbailey to PR 6438
I0908 16:25:55.794294   18276 pulls.go:105] -=-=-=-=6477-=-=-=-=-
I0908 16:25:57.831732   18276 pulls.go:122] Waiting for mergeability on Config Resource Proposal 6477
I0908 16:26:17.842918   18276 blunderbuss.go:123] Weights: pulls.weightMap{"thockin":6, "smarterclayton":6, "brendandburns":6, "bgrant0607":6}
Sum: 24
I0908 16:26:17.843028   18276 blunderbuss.go:127] Current assignee pmorie has a 0.00% chance of having been chosen
I0908 16:26:17.843071   18276 blunderbuss.go:139] would have assigned brendandburns to PR 6477
I0908 16:26:17.843098   18276 pulls.go:105] -=-=-=-=6520-=-=-=-=-
I0908 16:26:19.833292   18276 pulls.go:122] Waiting for mergeability on WIP:  Controller Plugin framework 6520
I0908 16:26:39.792415   18276 blunderbuss.go:123] Weights: pulls.weightMap{"lavalamp":15, "dchen1107":5, "davidopp":59, "brendandburns":27, "bgrant0607":22, "thockin":27, "smarterclayton":22, "eparis":22, "derekwaynecarr":44}
Sum: 243
I0908 16:26:39.792604   18276 blunderbuss.go:127] Current assignee thockin has a 11.11% chance of having been chosen
I0908 16:26:39.792652   18276 blunderbuss.go:139] would have assigned derekwaynecarr to PR 6520
```

I think the blunderbuss.yaml file can use some real help.

**Comment by brendandburns** [comment]
LGTM, but I think we should considered some amount of quantization or low-pass filtering to weed out really poor fits before we select the assignee.

**Comment by lavalamp** [comment]
We can do that the next time someone complains. I'll go ahead and build and push this.

**Comment by lavalamp** [comment]
Built and started. Added new commit with updates to makefile and pod.

**Comment by lavalamp** [comment]
I guess this was never merged? Merging it now, since we're running it...

**Pull request merged**
