### PR TITLE
fix link for ingress controller gce

### PR DESCRIPTION
**Pull request by dwdraju**

### CODE REVIEW

**Comment by dwdraju** [comment]
Signed the CLA.

**Comment by venezia** [comment]
@dwdraju the system still does not think you've accepted the CLA.  Your email address used in your git commit has to match the one used to sign the CLA.  It may also need to be part of your public github profile, I actually am unsure on that part.  Please verify this so and possibly correct so the bot can agree the commit complies with the CLA.

Thanks

**Comment by dwdraju** [comment]
Signed the CLA.

**Comment by venezia** [comment]
Thanks - sorry the delay - everything should automerge now!

**Pull request merged**
