### PR TITLE
use alpine baseimage for glbc

### PR DESCRIPTION
**Pull request by MDrollette**
33mb image versus 225mb

### CODE REVIEW

**Comment by brendandburns** [comment]
Last time we tried Alpine it had problems w/ our DNS @thockin do we know if this is still true?

**Comment by thockin** [comment]
Alpine does have DNS problems.  Does this image need to do DNS lookups at
all?  Like does it use `kubernetes.default` as a DNS name, even?

**Comment by MDrollette** [comment]
Is there a preferred minimal baseimage that does DNS properly?

**Comment by thockin** [comment]
busybox is what we mostly use.  It's doesn't have a nice package manager
like Alpine, but it has a shell and basic utilities.

@bprashanth, I feel like there was a reason you didn't use busybox as a
base?

**Comment by bprashanth** [comment]
Sorry for the delay. I think it was because certificat trust stores came pre-installed in the ubuntu image (or it was easy enough to apt-get when I needed them). I'm planning to swap the base image for something smaller very soon. @MDrollette if you want to swap it for busybox now I can figure out the roots later (we might get away with mounting them from host, I'm open to ideas; IIRC go checks standard locations by default: https://code.google.com/p/go/issues/detail?id=6391).

**Comment by bprashanth** [comment]
Also we use a custom alpine image with certs for the service-loadbalancer (https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/Dockerfile), so I think that should be fine. I'll run this pr against E2Es and confirm.

**Comment by lleszczu** [comment]
alpine:edge is using new musl version, which supports `search` directive in resolv.conf.

**Pull request closed without merging**
