### PR TITLE
Requesting blunderbuss feature to read aliases.

### PR DESCRIPTION
**Pull request by foxish**
Turn on the aliases feature in the blunderbuss munger.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1617)

### CODE REVIEW

**Comment by apelisse** [comment]
What is the alias feature? What will it be used for?

**Comment by foxish** [comment]
@apelisse It reads aliases in OWNERS files. The original PR which added the functionality is https://github.com/kubernetes/contrib/pull/1536

**Comment by foxish** [comment]
ping @apelisse

**Comment by apelisse** [comment]
Shame on me for not LGTM'ing before ...

**Pull request merged**
