### PR TITLE
open for every milestone

### PR DESCRIPTION
**Pull request by lavalamp**
Pushing live now.

### CODE REVIEW

**Comment by lavalamp** [comment]
@eparis

**Comment by eparis** [comment]
we'll see if the cache keeps us from running out of tokens...

**Comment by eparis** [comment]
we also need a message on kubernetes-dev telling people to label PRs they want in 1.3 with cherrypick-candidate and make sure the 1.3 milestone is set.

**Comment by lavalamp** [comment]
Yeah, I'm working on the email right now.

**Comment by lavalamp** [comment]
Huh, this barfed on trying to put the empty string into that arg. Pushing again...

**Comment by eparis** [comment]
did I screw those up? probably should have unit tested :-(

**Pull request merged**
