### PR TITLE
Bump rescheduler version to v0.3.3

### PR DESCRIPTION
**Pull request by sebbonnet**
To release changes made in #2712 and #2802

### CODE REVIEW

**Comment by piosz** [comment]
@bsalamat could you plaese take a look?

**Comment by bsalamat** [comment]
@piosz You still need to approve. I don't have approval power in rescheduler directory.

**Comment by piosz** [comment]
/approve no-issue
@bsalamat feel free to send a PR adding yourself to owners

**Comment by sebbonnet** [comment]
@piosz @bsalamat thanks guys, but the v0.3.3 images are still not available in the repo.
Does the publishing need to be done manually?

I was expecting images to be available like that:
```
docker pull gcr.io/google-containers/rescheduler-amd64:v0.3.3
docker pull gcr.io/google-containers/rescheduler:v0.3.3
```

**Comment by bsalamat** [comment]
I am not really familiar with the release process of rescheduler. @piosz do you know the answer?

**Comment by sebbonnet** [comment]
@bsalamat According to the Makefile `make all all-push` should publish all images

**Comment by piosz** [comment]
@bsalamat it's regular procedure of pushing various components to gcr.io.

**Comment by bsalamat** [comment]
I haven't been able to push the images using this command:
gcloud docker -- push gcr.io/google-containers/rescheduler-amd64:v0.3.3

The error that I see is very vague: "Layer already exists".  I wonder if I get this error due to lack of permission to push images to this repo.

**Comment by sebbonnet** [comment]
@bsalamat @piosz do you have any update on this, please?

**Comment by jsravn** [comment]
Ping @piosz

**Comment by bsalamat** [comment]
I cannot get those images published. I think I need some permission that I don't have. The error message is quite vague.

**Pull request merged**
