### PR TITLE
Add support for a 'safe-to-merge' label

### PR DESCRIPTION
**Pull request by brendandburns**
@ixdy @lavalamp @quinton-hoole

### CODE REVIEW

**Comment by davidopp** [comment]
Will it be confusing if we have ok-to-merge and safe-to-merge?

**Comment by eparis** [comment]
yes  :)

**Comment by brendandburns** [comment]
I'm open to other names.  But I'd like a marker for PRs that can't possibly effect e2e (e.g. all Markdown PRs)

**Comment by brendandburns** [comment]
This is so that we can purge the queue and focus efforts on the PRs that really need it.

I can also add in heuristics (e.g. if all files end in `.md`) if that is preferable to an explicit label.

**Comment by thockin** [comment]
docs-only ?

no-e2e-required?

**Comment by quinton-hoole** [comment]
What thockin said.

**Comment by brendandburns** [comment]
switched to `e2e-not-required`

**Comment by thockin** [comment]
should we maybe flip the polarity and annotate any PR which does NOT match
this as "e2e-required: yes"?

**Comment by brendandburns** [comment]
There's no automated matching right now...  It requires manual reviewer intervention.

(but yes, if it was automatic, flipping the parity might make sense)

**Comment by quinton-hoole** [comment]
LGTM!  Thanks @brendandburns 
For what it's worth, I like the parity as it is ("don-require-e2e", rather than "require-e2e").  And I like the explicit label rather than implicit opaque heuristics.

**Comment by thockin** [comment]
I meant to imply that every PR might require exactly one of "e2e-required:
yes" or "e2e-required: no" eventually

**Comment by brendandburns** [comment]
Sure, that's fine, we can write a munger to ask the reviewer for a label...  (or attempt to heuristically add it's own)

--brendan

**Pull request merged**
