### PR TITLE
Refactoring kubelet-to-gcm and adding kube-controller.

### PR DESCRIPTION
**Pull request by Q-Lee**
This pulls the node evictions metric the kube-controller's prometheus endpoint, and pushes it to Stackdriver. I've repurposed the kubelet monitoring agent for this, and refactored it to make further extensions easy.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1755)

### CODE REVIEW

**Comment by Q-Lee** [comment]
@fgrzadkowski this is the change to begin monitoring kube-controller metrics as well.

https://github.com/kubernetes/kubernetes/pull/32270 (is there a better way for cross-repo references?)

**Comment by Q-Lee** [comment]
Pushed a new version - I forgot to run hack/verify-all.sh

**Comment by gmarek** [comment]
cc @piosz

**Comment by gmarek** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS67U9EaqVbkEbUbtJQ:-KS67U9EaqVbkEbUbtJR:bkzxaro) (no related file):*
I like it - just a few nits. The thing I'd like to have is some kind of e2e test, that starts a cluster and check if metrics are available somewhere. It's probably too big for this PR, but without more complex test this code will degrade quickly.

---

*[kubelet-to-gcm/monitor/poll.go, line 37 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS63PnaHkLvLMyYAe01:-KS63PnbVjAj4iv8X1qN:b-dfu4l3) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/poll.go#L37)):*
> ```Go
> // Stackdriver format, probably from a backend like the kubelet.
> type MetricsSource interface {
> 	GetTSReq() (*v3.CreateTimeSeriesRequest, error)
> ```

s/TS/TimeSeries/ - and generally try avoiding non-standard abbreviations.

---

*[kubelet-to-gcm/monitor/config/initialize.go, line 38 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS64CeaoWdmMdTd1rQH:-KS64CeaoWdmMdTd1rQI:b4b7lll) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/config/initialize.go#L38)):*
> ```Go
> func NewConfigs(zone, projectID, cluster, host string, kubeletPort, ctrlPort uint, resolution time.Duration) (*monitor.SourceConfig, *monitor.SourceConfig, error) {
> 	if val, err := getZone(zone); err != nil {
> 		zone = val
> ```

Why all those X = val lines?

---

*[kubelet-to-gcm/monitor/config/initialize.go, line 76 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS64hq2dHvaMtsIv_Lg:-KS64hq3W9w1UO_rHsAc:b72exum) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/config/initialize.go#L76)):*
> ```Go
> // metadataURI returns the full URI for the desired resource
> func metadataURI(resource string) string {
> 	return gceMDEndpoint + gceMDPrefix + resource
> ```

s/MD/Metadata/g

---

*[kubelet-to-gcm/monitor/config/initialize.go, line 80 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS64na97l2LojV_Vx8G:-KS64naBIufdUExHtM2c:b-ge1e0q) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/config/initialize.go#L80)):*
> ```Go
> 
> // getGCEMetaData hits the instance's MD server.
> func getGCEMetaData(uri string) ([]byte, error) {
> ```

s/MetaData/Metadata/g

---

*[kubelet-to-gcm/monitor/controller/client.go, line 50 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS65csn2Iz1qk4FuYxL:-KS65csn2Iz1qk4FuYxM:b-ayktml) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/controller/client.go#L50)):*
> ```Go
> 
> // NewMetrics creates a Metrics object from a Prometheus response body.
> func NewMetrics(body []byte) (*Metrics, error) {
> ```

Why don't you use Prometheus library for this. E.g. https://github.com/kubernetes/kubernetes/blob/master/pkg/metrics/generic_metrics.go#L77

---

*[kubelet-to-gcm/monitor/controller/source.go, line 69 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS66bmXR7DA1apf2Ptg:-KS66bmXR7DA1apf2Pth:bw641h3) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/controller/source.go#L69)):*
> ```Go
> // Name returns the name of the component being monitored.
> func (s *Source) Name() string {
> 	return "kube-controller"
> ```

kube-controller-manager

---

*[kubelet-to-gcm/monitor/main/daemon.go, line 49 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS67DA0pp6WYiSl8RY4:-KS67DA0pp6WYiSl8RY5:b-mg6sfn) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/main/daemon.go#L49)):*
> ```Go
> 	kubeletHost = pflag.String("kubelet-host", "use-gce", "The kubelet's host name.")
> 	kubeletPort = pflag.Uint("kubelet-port", 10255, "The kubelet's port.")
> 	ctrlPort    = pflag.Uint("controller-port", 10252, "The kube-controller's port.")
> ```

controller-manager-port

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755)*

**Comment by Q-Lee** [comment]
Review status: 0 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS67U9EaqVbkEbUbtJQ:-KS8XrLSv130OuE2kRXX:btc4raj) (no related file):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> I like it - just a few nits. The thing I'd like to have is some kind of e2e test, that starts a cluster and check if metrics are available somewhere. It's probably too big for this PR, but without more complex test this code will degrade quickly.
</details>
I agree - but e2e tests from contrib are awkward. This should be a GKE e2e test (just make sure metrics appear in Stackdriver), but the daemon is consumed as a container.

A lot of the refactoring makes this more unit testable. Perhaps that's sufficient for the immediate future while we wait for side repos to become better supported? (E.g., I could mock the GCE metadata server and test the configuration).

---

*[kubelet-to-gcm/monitor/config/initialize.go, line 38 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS64CeaoWdmMdTd1rQH:-KS8WziwZ6WlUktekQYu:bh2w75u) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/config/initialize.go#L38)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> Why all those X = val lines?
</details>
I was just experimenting with ways to keep err in the if scope. I've actually already removed this, but forgot to push it out last night :\

---

*[kubelet-to-gcm/monitor/controller/client.go, line 50 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS65csn2Iz1qk4FuYxL:-KS8Z1YwrJPbLktVxlFt:bfzx8su) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/controller/client.go#L50)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> Why don't you use Prometheus library for this. E.g. https://github.com/kubernetes/kubernetes/blob/master/pkg/metrics/generic_metrics.go#L77
</details>
Honestly? Because I didn't know it existed. Since there's exactly one right now, how about we leave this as is? In the near future I expect to parse multiple metrics from multiple components.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755)*

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by gmarek** [comment]
cc @fgrzadkowski - I was trying to do the review, but the internet here is just too poor for that. Do you think you can take over?

**Comment by fgrzadkowski** [comment]
I'm not sure I will have time. We have an event with some students today in the office where I have a presentation and help with the workshops. On Monday we have a business trip.

I'll try to take a look, but no promises :)

**Comment by gmarek** [comment]
Reviewed 3 of 17 files at r1, 16 of 17 files at r3.
Review status: 13 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[kubelet-to-gcm/monitor/controller/client.go, line 50 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS65csn2Iz1qk4FuYxL:-KSQrp3u3C1S2dtx7vmy:bs5l1j3) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/controller/client.go#L50)):*
<details><summary><i>Previously, Q-Lee wrote…</i></summary>
> Honestly? Because I didn't know it existed. Since there's exactly one right now, how about we leave this as is? In the near future I expect to parse multiple metrics from multiple components.
</details>
Parsing it by hand is volatile - can you please a library to parse prom metrics? https://github.com/prometheus/common/tree/master/expfmt

---

*[kubelet-to-gcm/monitor/controller/client.go, line 28 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KSHWwOrsgEM1-wVLCZ6:-KSHWwOrsgEM1-wVLCZ7:ba86s7q) ([raw file](https://github.com/kubernetes/contrib/blob/7ad641391944fbad730fdcd3c3f05dd2ce03c38b/kubelet-to-gcm/monitor/controller/client.go#L28)):*
> ```Go
> 	"strings"
> 
> 	log "github.com/golang/glog"
> ```

I don't think we alias glog anywhere else but I see that you're using it in this repo. I don't like it, but changing it everywhere would be an overkill. In future please try using the same conventions we use in main kubernetes repo.

---

*[kubelet-to-gcm/monitor/controller/client.go, line 91 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KSQtb3K6TFACk9dQ9NZ:-KSQtb3K6TFACk9dQ9N_:b-3rqelx) ([raw file](https://github.com/kubernetes/contrib/blob/7ad641391944fbad730fdcd3c3f05dd2ce03c38b/kubelet-to-gcm/monitor/controller/client.go#L91)):*
> ```Go
> // doRequest makes the request to the controller, and returns the body.
> func (c *Client) doRequestAndParse(req *http.Request) (*Metrics, error) {
> 	log.Infof("Preparing to perform request: %v", req)
> ```

We don't want to log this in every request.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755)*

**Comment by gmarek** [comment]
Reviewed 1 of 17 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755)*

**Comment by gmarek** [comment]
Ping @Q-Lee

**Comment by Q-Lee** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[kubelet-to-gcm/monitor/controller/client.go, line 50 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS65csn2Iz1qk4FuYxL:-KSnLt4to86Z2M8FGvsG:b-dt95jc) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/controller/client.go#L50)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> Parsing it by hand is volatile - can you please a library to parse prom metrics? https://github.com/prometheus/common/tree/master/expfmt
</details>
Sorry, I've been busy, and deprioritized this after we missed the weekly deployment.

I can't make head or tails of that library. They offer a packaged client, but it expects URIs that don't exist on the node controller (e.g., /api/v1 and /query), so I assume it's meant to hit some other kind of "prometheus server". The file you linked contains a "textDecoder" with a "Decode" method, but it doesn't smell right.

The Decode method "returns" a "MetricFamily", which contains a []*Metric. The Metric object contains a value, but nothing else. In fact, it's not a metric at all: it's a point. I can only assume the "MetricFamily" is actually a "Metric" with a misnamed "[]*Point".

So the "Decode" method actually returns several points in a metric space, but parses everything up front, and then returns them 1 at a time?

I'll keep at it a little, but ... do you want to do it? The code is well contained and only requires one new dependency.

---

*[kubelet-to-gcm/monitor/controller/client.go, line 28 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KSHWwOrsgEM1-wVLCZ6:-KSnQusNAu-FN6bo3pod:bmpulj2) ([raw file](https://github.com/kubernetes/contrib/blob/7ad641391944fbad730fdcd3c3f05dd2ce03c38b/kubelet-to-gcm/monitor/controller/client.go#L28)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> I don't think we alias glog anywhere else but I see that you're using it in this repo. I don't like it, but changing it everywhere would be an overkill. In future please try using the same conventions we use in main kubernetes repo.
</details>
I'll keep this in mind, and change it when I add the next component.

---

*[kubelet-to-gcm/monitor/controller/client.go, line 91 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KSQtb3K6TFACk9dQ9NZ:-KSeJWImCltbToteUbgo:bjkl7ht) ([raw file](https://github.com/kubernetes/contrib/blob/7ad641391944fbad730fdcd3c3f05dd2ce03c38b/kubelet-to-gcm/monitor/controller/client.go#L91)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> We don't want to log this in every request.
</details>
Whoops, printf debugging gone astray.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755)*

**Comment by gmarek** [comment]
Reviewed 3 of 17 files at r1, 3 of 17 files at r3, 16 of 17 files at r5.
Review status: 13 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[kubelet-to-gcm/monitor/controller/client.go, line 50 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS65csn2Iz1qk4FuYxL:-KSoqlAd0nyWmHV1H-Ws:bgc1h2r) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/controller/client.go#L50)):*
<details><summary><i>Previously, Q-Lee wrote…</i></summary>
> Sorry, I've been busy, and deprioritized this after we missed the weekly deployment.
> 
> I can't make head or tails of that library. They offer a packaged client, but it expects URIs that don't exist on the node controller (e.g., /api/v1 and /query), so I assume it's meant to hit some other kind of "prometheus server". The file you linked contains a "textDecoder" with a "Decode" method, but it doesn't smell right.
> 
> The Decode method "returns" a "MetricFamily", which contains a []*Metric. The Metric object contains a value, but nothing else. In fact, it's not a metric at all: it's a point. I can only assume the "MetricFamily" is actually a "Metric" with a misnamed "[]*Point".
> 
> So the "Decode" method actually returns several points in a metric space, but parses everything up front, and then returns them 1 at a time?
> 
> I'll keep at it a little, but ... do you want to do it? The code is well contained and only requires one new dependency.
</details>
I don't want to believe that they won't change the text format ever, so I want to avoid parsing metrics by hand. If they change the format and in the same time fail to update their parser, we'll have every right to scream very loudly.

You can see the usage of this library here: https://github.com/kubernetes/kubernetes/blob/master/pkg/metrics/generic_metrics.go#L77

Plus this is a generic method, so it'll be pretty easy to extend the list of scraped metrics.

---

*[kubelet-to-gcm/monitor/controller/client.go, line 91 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KSQtb3K6TFACk9dQ9NZ:-KSoqMddxEJf7dRfMQvi:b-gdojpi) ([raw file](https://github.com/kubernetes/contrib/blob/7ad641391944fbad730fdcd3c3f05dd2ce03c38b/kubelet-to-gcm/monitor/controller/client.go#L91)):*
<details><summary><i>Previously, Q-Lee wrote…</i></summary>
> Whoops, printf debugging gone astray.
</details>
I think you forgot to push the new version - it's still here.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755)*

**Comment by Q-Lee** [comment]
Review status: 10 of 645 files reviewed at latest revision, 3 unresolved discussions.

---

*[kubelet-to-gcm/monitor/controller/client.go, line 50 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS65csn2Iz1qk4FuYxL:-KSsOZ5RGJDGcu3O3zBH:bi2gk0p) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/controller/client.go#L50)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> I don't want to believe that they won't change the text format ever, so I want to avoid parsing metrics by hand. If they change the format and in the same time fail to update their parser, we'll have every right to scream very loudly.
> 
> You can see the usage of this library here: https://github.com/kubernetes/kubernetes/blob/master/pkg/metrics/generic_metrics.go#L77
> 
> Plus this is a generic method, so it'll be pretty easy to extend the list of scraped metrics.
</details>
They encourage others to write parsing libraries for unsupported languages, so I *would* be surprised if they change the text format. Nonetheless, I've used their library here (since it had to be done eventually anyway).

---

*[kubelet-to-gcm/monitor/controller/client.go, line 91 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KSQtb3K6TFACk9dQ9NZ:-KSsP8hrQawHax-_ZKDY:b-rcuhdq) ([raw file](https://github.com/kubernetes/contrib/blob/7ad641391944fbad730fdcd3c3f05dd2ce03c38b/kubelet-to-gcm/monitor/controller/client.go#L91)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> I think you forgot to push the new version - it's still here.
</details>
Well then.... How about now?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755)*

**Comment by gmarek** [comment]
Reviewed 1 of 17 files at r1, 1 of 17 files at r3, 1 of 17 files at r5, 32 of 643 files at r6.
Review status: 40 of 645 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[kubelet-to-gcm/monitor/convert.go, line 1 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KSu6ZcbHgkhD6evMrGq:-KSu6ZcbHgkhD6evMrGr:bhkj8g2) ([raw file](https://github.com/kubernetes/contrib/blob/5c91b8995290f82d7420447e22d4418e1db0e4d5/kubelet-to-gcm/monitor/convert.go#L1)):*
> ```Go
> package monitor
> ```

I'm not a huge fan of this approach, as it may cause problems (e.g. for i := range sth { Int64Ptr(i) }) is problematic. In other parts of code we just create a local variable and take a reference to it wherever we need this. If you want to keep those functions please do
copy := i; return &copy

---

*[kubelet-to-gcm/monitor/controller/client.go, line 50 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KS65csn2Iz1qk4FuYxL:-KSu5yzfI62ABizC9cyo:bknsz6a) ([raw file](https://github.com/kubernetes/contrib/blob/5329d8032f90b94464d9585b6ec2c348e13bebe1/kubelet-to-gcm/monitor/controller/client.go#L50)):*
<details><summary><i>Previously, Q-Lee wrote…</i></summary>
> They encourage others to write parsing libraries for unsupported languages, so I *would* be surprised if they change the text format. Nonetheless, I've used their library here (since it had to be done eventually anyway).
</details>
LG - great thanks for doing this!

---

*[kubelet-to-gcm/monitor/controller/client.go, line 91 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KSQtb3K6TFACk9dQ9NZ:-KSu5wB0ve27B40GryvH:b32vhw) ([raw file](https://github.com/kubernetes/contrib/blob/7ad641391944fbad730fdcd3c3f05dd2ce03c38b/kubelet-to-gcm/monitor/controller/client.go#L91)):*
<details><summary><i>Previously, Q-Lee wrote…</i></summary>
> Well then.... How about now?
</details>
:)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755)*

**Comment by gmarek** [comment]
Reviewed 611 of 643 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[kubelet-to-gcm/monitor/convert.go, line 1 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755#-KSu6ZcbHgkhD6evMrGq:-KSuByW-cwGdn07xhei5:byu87xa) ([raw file](https://github.com/kubernetes/contrib/blob/5c91b8995290f82d7420447e22d4418e1db0e4d5/kubelet-to-gcm/monitor/convert.go#L1)):*
<details><summary><i>Previously, gmarek (Marek Grabowski) wrote…</i></summary>
> I'm not a huge fan of this approach, as it may cause problems (e.g. for i := range sth { Int64Ptr(i) }) is problematic. In other parts of code we just create a local variable and take a reference to it wherever we need this. If you want to keep those functions please do
> copy := i; return &copy
</details>
Sorry, it's OK - switching languages is hard.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/1755)*

**Comment by gmarek** [comment]
LGTM, sans golint problem.

**Comment by Q-Lee** [comment]
Lint issues are fixed, so I've removed the donotmerge.

**Comment by Q-Lee** [comment]
Heh, the bots getting better. It removed the lgtm after I fixed the lint issues. I've added it back.

**Comment by Q-Lee** [comment]
Hrm, k8s-merge-robot is getting uppity. I'm thinking it might just be out of sync. Re-adding the label.

**Comment by Q-Lee** [comment]
I'm just going to do a rebase and merge (there's a fix for 1.1 in this PR and a 1.2 version, so I can't squash).

**Pull request merged**
