### PR TITLE
add nginx controller

### PR DESCRIPTION
**Pull request by RobinsChens**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1696)

### CODE REVIEW

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by grodrigues3** [comment]
[APPROVALNOTIFIER] The Following OWNERS Files Need Approval:

- **/**
- **404-server**
- **addon-resizer**

We suggest the following people:
cc @eparis 
 You can indicate your approval by writing `/approve` in a comment
 You can cancel your approval by writing `/approve cancel`in a comment

**Comment by piosz** [comment]
Something is wrong with this PR. Please fix.

**Comment by piosz** [comment]
Closing as obsolete. Please reopen if you want to continue working on it.

**Pull request closed without merging**
