### PR TITLE
Add nginx_upstream_check_module.

### PR DESCRIPTION
**Pull request by chrismoos**
This will be used by the NGINX ingress controller for performing upstream health checks.

### CODE REVIEW

**Comment by chrismoos** [comment]
@bprashanth Is this change something you are still interested in including?

**Comment by bprashanth** [comment]
@chrismoos can you give me some context? the nginx controller already health checks https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/custom-upstream-check, is this an improvement or an orthogonal feature. 
@aledbf fyi (I suppose we'll want it in the ingress repo anyway, but discussing if it should move)

**Comment by chrismoos** [comment]
@bprashanth This is completely separate than the current "checks" that nginx can do with `max_fails`, etc. This change is part of the larger change that I already sent a PR for on the ingress repo:

https://github.com/kubernetes/ingress/pull/146

Also, for reference, I did this a while back on this repository and you said I should rebase on ingress:

https://github.com/kubernetes/contrib/pull/2072

**Comment by bprashanth** [comment]
Ah, sorry, completely forgot. The nginx-slim image is also now in ingress: https://github.com/kubernetes/ingress/tree/master/images/nginx-slim so I'm closing this. Will review the ingress pr.

**Pull request closed without merging**
