### PR TITLE
three card poker game to demo n-tier/microservice architecture

### PR DESCRIPTION
**Pull request by suyogbarve**
This is an interesting n-tier/microservice based three-card-poker game. It also contains a demo-client application which dynamically creates a view of pods (in each layer) as they are deployed. 
This works as an interesting demo to showcase the ease of deploying a heterogenous application environment.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1744)

### CODE REVIEW

**Comment by suyogbarve** [comment]
I signed it!

**Comment by suyogbarve** [comment]
suyogbarve@gmail.com is the username used with Github and same email is used for signing CLA

**Comment by suyogbarve** [comment]
I signed it!

**Comment by suyogbarve** [comment]
Hi Mike Danese,
Did you get a chance to look into this?

**Comment by suyogbarve** [comment]
I signed it!

**Comment by mikedanese** [comment]
We are trying to get rid of this repo. I don't think this is the right place for this code. See https://github.com/kubernetes/contrib/issues/762

**Comment by suyogbarve** [comment]
thanks mike, can you suggest me any alternate repo? 
how about github.com/kubernetes/kubernetes/tree/master/examples/ ?

**Pull request closed without merging**
