### PR TITLE
original 1.1 docs

### PR DESCRIPTION
**Pull request by linfan**
Contents all files in original v1.1 docs, except for the man folder and warning.png image

### CODE REVIEW

**Comment by linfan** [comment]
CLA: I signed it!

**Comment by linfan** [comment]
CLA update mail: I signed it!

**Comment by hurf** [comment]
@linfan Thanks for initializing the work.

@dchen1107 - Hi Dawn, as I mentioned before, we're translating v1.1 docs into Chinese. Till now, we've finished most part of it. But just few of the translated docs are proofread. So we're going to submit the docs into this repo and hoping the github PR review process can help proofing the docs.

The work will be done in these steps:
1. Upload all original docs. This is what this PR do.
2. Upload docs already reviewed in next PR.
3. Upload docs haven't reviewed one by one in sepereated PRs. And later getting reviewed and merged.
4. Doing step 3 repeatedly until all original docs are replaced by translated docs.

Does that sounds reasonable to you?
For step3, can @caesarxuchao @Random-Liu @freehan @xiang90 @hongchaodeng and other Chinese speaking developers help with it, if you have time?

**Comment by eparis** [comment]
@david-mcmahon does this belong here?

**Comment by eparis** [comment]
I'm going to close. I believe the proper location is over in kubenretes.github.io

**Comment by david-mcmahon** [comment]
@eparis, I assume not.  cc @johndmulhausen

**Pull request closed without merging**
