### PR TITLE
remove global Godeps and create one per subproject

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by mikedanese** [comment]
cc @brendandburns @eparis @gmarek

**Comment by eparis** [comment]
Is there anything in the go 1.5 vendor experiment that could support this methodology?

**Comment by mikedanese** [comment]
@eparis I can refactor this to use Godeps/ with vendor experiment enabled. Same thing applies. Each subproject would have it's own vendor/ directory.

**Comment by gmarek** [comment]
Please, please, please - can we merge this ASAP?

**Comment by bprashanth** [comment]
Please write a readme about adding new projects to contrib, since we will now require a godep checkin as well that a lot of people will probably forget.

**Comment by bprashanth** [comment]
Also it would be really nice to share the kubernetes client api godep, when we break it out. Currently several projects in contrib use the common godep as a way to stay upto date with rebases.

**Comment by mikedanese** [comment]
I've updated the README. I think that sharing certain dependencies can be fixed up late. The main objective with this was to separate and demangle the dependencies of each subproject in contrib

**Comment by gmarek** [comment]
I don't know who should review this? @smarterclayton? @brendandburns?

**Comment by smarterclayton** [comment]
This only touches non core kube, correct?

**Comment by gmarek** [comment]
Yup

**Comment by smarterclayton** [comment]
I won't have time until mid next week - @soltysh or @ironcladlou for other
folks who deal with godeps a lot.

**Comment by brendandburns** [comment]
frankly, it builds and passes unit tests. that's good enough for me.

Unless anyone else objects, I'm in favor of just merging.

**Comment by bprashanth** [comment]
Yeah, should be fine IMO. Just run make in each subdir. If you feel like a good citized send something out to kubernetes-dev so anyone who has contributed also knows to come back and check on their project.

**Comment by mikedanese** [comment]
Ok I'm going to rebase this and merge on green.

**Pull request merged**
