### PR TITLE
Add namespace documentation to service loadbalancer

### PR DESCRIPTION
**Pull request by bprashanth**
Clarify documentation around cross namespace loadbalancing.

### CODE REVIEW

**Comment by bprashanth** [comment]
https://github.com/kubernetes/contrib/issues/103

**Comment by bprashanth** [comment]
@aledbf fyi, since you've been playing aroud with the service_loadbalancer lately

**Comment by brendandburns** [comment]
@bprashanth needs rease

**Comment by aledbf** [comment]
lgtm

**Comment by bprashanth** [comment]
Only docs changed so self-merging

**Pull request merged**
