### PR TITLE
Fix typo in doc

### PR DESCRIPTION
**Pull request by kenden**

### CODE REVIEW

**Comment by mumoshu** [comment]
@kenden @fgrzadkowski Just happened to take a look into this by chance but can we close this as the typo seems to be already fixed in master?
https://github.com/kubernetes/contrib/blame/1957bf5/cluster-autoscaler/FAQ.md#L74

**Comment by kenden** [comment]
@mumoshu Yes, this got fixed in master in the meantime. Closing.

**Comment by mumoshu** [comment]
@kenden Thanks for the confirmation 👍

**Pull request closed without merging**
