### PR TITLE
ingress nginx: Should not interpret path as regex.

### PR DESCRIPTION
**Pull request by calebcase**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1944)

### CODE REVIEW

**Comment by calebcase** [comment]
I signed it!

**Comment by aledbf** [comment]
@calebcase can you elaborate why this change is required?

**Comment by calebcase** [comment]
Initially this resulted from one user having an ingress for `/a/b/c` while another user had `/myproject/a/b/c`. Because of the way the location lines are unanchored regex traffic that was expected to go to `/myproject/a/b/c` ended up going to `/a/b/c`.

The entire removal of the regex itself is motivated by two observations:
* You can't put a regex in the path spec for ingress - it will only accept a "plain" string.
* The regex chosen is case-insensitive meaning it will surprisingly match `/A/b/C` for `/a/b/c`.

I had a different patch for just anchoring the regex, but decided to propose removal first as that seems the better option.

**Comment by calebcase** [comment]
Tests cleaned up.

**Pull request closed without merging**
