### PR TITLE
[WIP] remove multiple ok-to-test comments as well

### PR DESCRIPTION
**Pull request by eparis**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1358)

### CODE REVIEW

**Comment by eparis** [comment]
@99BenGardner

**Comment by apelisse** [comment]
@eparis This needs rebase (I'll add the munger to the list)

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by ingvagabund** [comment]
@eparis can the CLA be verified for entire company?

**Comment by eparis** [comment]
@ingvagabund I thought I had that set up correctly. Apparently it isn't working. I'm not sure who to talk to...

**Comment by eparis** [comment]
maybe if I post something the cla bot will love me...

**Comment by grodrigues3** [comment]
[APPROVALNOTIFIER] The Following OWNERS Files Need Approval:

- **mungegithub**

We suggest the following people:
cc @bprashanth 
 You can indicate your approval by writing `/approve` in a comment
 You can cancel your approval by writing `/approve cancel`in a comment

**Comment by apelisse** [comment]
@spxtr Does this still make sense? or is this handled somewhat by prow? Or did the format change?

**Comment by apelisse** [comment]
I honestly believe this doesn't make any sense. Mungebot is not in this repo anymore, and this is handled by prow anyway.

**Comment by spxtr** [comment]
Oh right, this is from when every PR Jenkins job made its own "ok to test" comment.

**Pull request closed without merging**
