### PR TITLE
Fix StatefulSets: Zookeeper pod affinity

### PR DESCRIPTION
**Pull request by dminkovsky**
According to docs, `requiredDuringSchedulingRequiredDuringExecution`
not yet implemented. Not working in 1.5.1.

### CODE REVIEW

**Comment by dminkovsky** [comment]
https://github.com/kubernetes/contrib/pull/2269 was missing this.

**Comment by dminkovsky** [comment]
May be want to update the code here, too http://kubernetes.io/docs/tutorials/stateful-application/zookeeper/

**Comment by janetkuo** [comment]
LGTM

**Comment by kow3ns** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2273#-:-KarknN6iFD5jMnPy4XN:bnfp4nl)*

**Pull request merged**
