### PR TITLE
Move *-serial to nonblocking.

### PR DESCRIPTION
**Pull request by lavalamp**
Also remove the -subnet test which is apparently not useful. (per @gmarek)

### CODE REVIEW

**Comment by lavalamp** [comment]
Pushing this live right now.

**Comment by gmarek** [comment]
The problem with `-subnet`, if I understand the suite correctly is that it runs on 1.2 release branch. @roberthbailey 

Another discussion we probably should have is do we really need to run tests of old release branches. We don't make a lot of changes in them, and they are separate from changes to the master, so I don't think it's useful for them to be blockers. @lavalamp @fejta

**Comment by fejta** [comment]
-subnet shouldn't be queue blocking? And/or if it is it should be listed at http://submit-queue.k8s.io/#/e2e

**Comment by lavalamp** [comment]
it wasn't blocking, but it also wasn't useful. More noise than signal.

**Pull request merged**
