### PR TITLE
Add ci- prefix for kops-aws jobs

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/test-infra/pull/1209

Also fix the renamed garbagecollector job

@fejta @zmerlynn 

btw does this configmap change require a deployment of SQ or it's automatic?

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/2094)

**Comment by krzyzacy** [comment]
is this k8s-oncall not mapping to the right alias?

**Comment by zmerlynn** [comment]
/lgtm

@krzyzacy: It has to be restarted to take effect.

**Comment by lavalamp** [comment]
I (oncall) am getting these notifications. I'm just way behind :)

**Pull request merged**
