### PR TITLE
Add a container & job spec to check metadata concealment correctness

### PR DESCRIPTION
**Pull request by ikehz**
This checks for some of the fixes made in https://github.com/kubernetes/kubernetes/pull/51302.  Ref #8867.

I'm unsure of where this should live, but this seems like as good a place as any?  @spxtr We discussed, and I'd rather just check it in here now.

### CODE REVIEW

**Comment by ihmccreery** [comment]
Ping @lavalamp @eparis.

**Comment by ihmccreery** [comment]
Ref #8867.

**Comment by lavalamp** [comment]
I don't know what this is, and AFAIK contrib is not accepting new code. I would consider approving a change adding someone to the OWNERs file of this metadata-proxy thing if you can find someone who can convince me they will feed and water this thing and find it a new home.

**Comment by ihmccreery** [comment]
@lavalamp Done, see #2751.  Please assign #2750 to me.  I'll make sure this gets moved out of kubernetes/contrib, but in the meantime, can I check in these tests?

**Comment by ihmccreery** [comment]
@lavalamp with #2751 merged, are you comfortable lgtm-ing this?  What else can I do to get this merged?

**Comment by ihmccreery** [comment]
Ping @lavalamp

**Pull request merged**
