### PR TITLE
[ansible] update fedora vagrant box version

### PR DESCRIPTION
**Pull request by jasonbrooks**

### CODE REVIEW

**Comment by jasonbrooks** [comment]
cc @ingvagabund

**Comment by ingvagabund** [comment]
This actually breaks the deployment on f25 cloud. Docker version detection does not work anymore.

**Comment by jasonbrooks** [comment]
I'll look into that.

**Comment by ingvagabund** [comment]
https://github.com/kubernetes/contrib/blob/master/ansible/roles/docker/tasks/main.yml#L82

**Comment by ingvagabund** [comment]
So far only in Vagrant, OpenStack deployment is ok.

**Comment by jasonbrooks** [comment]
@ingvagabund Do you mean virtualbox? It's working for me w/ libvirt.

**Comment by ingvagabund** [comment]
My bad, I misremembered the failure. Rerunning again:

```
TASK [docker : Detected version] ***********************************************
ok: [kube-node-1] => {}

MSG:

1.12.6

ok: [kube-master-1] => {}

MSG:

1.12.6

ok: [kube-node-2] => {}

MSG:

1.12.6


TASK [docker : Write docker daemon.conf file] **********************************
changed: [kube-master-1]
changed: [kube-node-1]
changed: [kube-node-2]

TASK [docker : Enable Docker] **************************************************
changed: [kube-master-1]
changed: [kube-node-1]
changed: [kube-node-2]

RUNNING HANDLER [docker : reload docker] ***************************************
fatal: [kube-node-1]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Unable to reload service docker: docker.service is not active, cannot reload.


fatal: [kube-node-2]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Unable to reload service docker: docker.service is not active, cannot reload.


fatal: [kube-master-1]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Unable to reload service docker: docker.service is not active, cannot reload.



RUNNING HANDLER [docker : restart docker] **************************************

RUNNING HANDLER [docker : start docker] ****************************************
	to retry, use: --limit @/home/jchaloup/Projects/src/github.com/kubernetes/contrib/ansible/playbooks/deploy-cluster.retry

PLAY RECAP *********************************************************************
kube-master-1              : ok=44   changed=17   unreachable=0    failed=1   
kube-node-1                : ok=25   changed=11   unreachable=0    failed=1   
kube-node-2                : ok=25   changed=11   unreachable=0    failed=1  
```

**Comment by ingvagabund** [comment]
docker-1.12.6-6.gitae7d637.fc25.x86_64
ansible-2.2.0.0-3.fc24.noarch

**Pull request merged**
