### PR TITLE
Fix bug in scale-demo loader port specification

### PR DESCRIPTION
**Pull request by verb**
The port argument isn't being dereferenced

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/2110)

**Comment by verb** [comment]
Can I approve that? Let's see.

/approve

**Comment by verb** [comment]
rebased

**Comment by verb** [comment]
FYI, this is a 1 character bugfix to deference the flag pointer rather than using its memory address in a URL.

**Comment by sarahnovotny** [comment]
@brendandburns @eparis can one of you take a look at this?  it's a one character change.

**Comment by cblecker** [comment]
@verb if this PR is still needed, it needs a rebase

**Comment by verb** [comment]
rebased!

**Comment by roberthbailey** [comment]
@verb - please rebase

**Comment by verb** [comment]
rebased

**Comment by cblecker** [comment]
pinging @roberthbailey by name to ensure he sees it :)

**Pull request merged**
