### PR TITLE
ingress: use POD_NAMESPACE as a namespace in cli parameters

### PR DESCRIPTION
**Pull request by kayrus**
When you deploy ingress not into `default` namespace, ingress RC fails with the `no service with name default/default-http-backend found: services "default-http-backend" not found` error message.

This fix uses `POD_NAMESPACE` which we already pass into the pod ENV.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1571)

### CODE REVIEW

**Comment by bprashanth** [comment]
makes sense to me, will wait for Manuel to lgtm

**Comment by aledbf** [comment]
@kayrus just a comment: in all the examples the default backend service is created in the default namespace ([default-backend.yaml](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/default-backend.yaml)). Is up to the user to specify the correct service. 
From the docs: `--default-backend-service: Service used to serve a 404 page for the default backend. Takes the form namespace/name. The controller uses the first node port of this Service for the default backend.`
If @bprashanth is ok with this change then is lgtm.

**Comment by aledbf** [comment]
@kayrus please do not change the content of the `ingress/vendor/` directory. The content of that directory is generated by `godep`.

**Comment by kayrus** [comment]
@aledbf made this vendor change by script. restored.

as for the default backend, I know that.

**Comment by bprashanth** [comment]
LGTM thanks

**Pull request merged**
