### PR TITLE
[nginx ingress controller] possibility to specify nginx timeout via annotations for each namespace

### PR DESCRIPTION
**Pull request by micheleorsi**
relates to this #1717

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1957)

### CODE REVIEW

**Comment by aledbf** [comment]
@micheleorsi already implemented [here](https://github.com/aledbf/ingress-controller/blob/master/pkg/ingress/annotations/proxy/main.go)

**Comment by micheleorsi** [comment]
@aledbf: that's great! so how should we proceed?

**Comment by aledbf** [comment]
@micheleorsi please wait until the ingress controller is moved out of contrib (I hope this week)

**Comment by micheleorsi** [comment]
ok thanks! So I'll close also this pull request since it's not anymore useful!

**Pull request closed without merging**
