### PR TITLE
Handle salt templated monitoring definitions

### LINKED ISSUE #337: Heapster Deployment Broken
The heapster deployment seems to be broken because in the Ansible playbooks because of a recent-ish change to the controller definition to allow for dynamic configurations. I suspect this is usually handled by Salt, but this does not occur during an Ansible based deployment. Here is the relevant commit that seems to introduce this issue:

https://github.com/kubernetes/kubernetes/commit/eee87558e06e07ee62362c61c3d0b49e29de4fdf

Removing the templating from the top of the service file seems to allow for creation as expected.

### PR DESCRIPTION
**Pull request by eparis**
Which were added https://github.com/kubernetes/kubernetes/commit/eee87558e06e07ee62362c61c3d0b49e29de4fdf

And fixes #337

### CODE REVIEW

**Comment by eparis** [comment]
@rsmitty Can you test this? I have not.

**Comment by rsmitty** [comment]
Sure, I can try this out today.

**Comment by rsmitty** [comment]
Looks almost perfect. There's a rogue `with_items:` on line 10 of cluster-monitoring.yml. Once I removed that, it seems to deploy as expected. 

Unsure about the Travis CI check failing though. Maybe it's the same reason? I'm not familiar with what's happening on the build side.

**Comment by rsmitty** [comment]
I believe this is good to go now.

**Pull request merged**
