### PR TITLE
Introduce domain flag for non standard cluster domains

### PR DESCRIPTION
**Pull request by SchwarzM**
This would address #2011 added this to facilitate discussion.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/2013)

### CODE REVIEW

**Comment by SchwarzM** [comment]
I signed it!

**Comment by SchwarzM** [comment]
anything I can do to help this along ?

**Comment by BugRoger** [comment]
Ping @bprashanth. Would you please take a look at this? Thanks!

**Comment by bprashanth** [comment]
Sorry for the delay LGTM. If you'd like a new image, please send a follow up pr bumping up the image in the Makefile.

**Pull request merged**
