### PR TITLE
Update kubernetes godep

### PR DESCRIPTION
**Pull request by janetkuo**
cc @bprashanth

### CODE REVIEW

**Comment by eparis** [comment]
How was this generated?

**Comment by eparis** [comment]
(and I guess why?)

**Comment by bprashanth** [comment]
@eparis pretty much https://github.com/kubernetes/contrib i think
To pull in some changes to Ingress resource, but also ends up pulling a few other changes to related packages apparently. Would you prefer keeping the other packages as they were? I figured always keeping kube and contrib in sync with every roll makes sense?

**Comment by bprashanth** [comment]
LGTM. Will wait for @eparis before merging.

**Pull request merged**
