### PR TITLE
addon-resizer: migrated to kubernetes client in version 1.3

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by piosz** [comment]
cc @mwielgus @Q-Lee

**Comment by fgrzadkowski** [comment]
LGTM.

Please reference issue with the problem that this PR fixes.

Before merging please squash.

**Comment by piosz** [comment]
I'm not squashing commits because it would help to better understand historical changes in the future.

**Comment by piosz** [comment]
related issue https://github.com/kubernetes/kubernetes/issues/27178

**Comment by Q-Lee** [comment]
LGTM, and I agree w/not squashing.

**Pull request merged**
