### PR TITLE
Fix bug where paths were being url decoded during rewrites

### PR DESCRIPTION
**Pull request by kushmansingh**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1943)

### CODE REVIEW

**Comment by kushmansingh** [comment]
I signed it!

**Comment by kushmansingh** [comment]
I signed it!

**Comment by aledbf** [comment]
@kushmansingh can you provide an example to test this change?

**Comment by kushmansingh** [comment]
@aledbf This is an example deployment using the rewrite rules and my public docker simple server image  https://gist.github.com/kushmansingh/47644ef4db96f11b1ea450ae19072552.

Deploying that and then hitting it with something like `curl -H "Host: test-ingress" http://{ip}/myserver/%2B123` and then `curl -H "Host: test-ingress"  http://{ip}/myserver/+123` will give you logs from the pod that look like 
```
  2016/10/28 16:06:08 Starting server on port 80
  2016/10/28 16:08:56  /+123
  2016/10/28 16:09:13  /+123
```
With my fix they should look like
```
```
  2016/10/28 16:18:23  /%2B123
  2016/10/28 16:18:45  /+123
```

**Comment by kushmansingh** [comment]
Any feedback @aledbf ?

**Comment by aledbf** [comment]
@kushmansingh I'm sorry for the delay. Right now I'm creating the e2e tests for the ingress controller in order to tests changes like this one.  No excuses, just I've been really busy with other stuff. 
Please let me finish the tests to see how affects other apps with rewrites. Having e2e tests also will help to improve the response time in the PRs

**Comment by kushmansingh** [comment]
Ingress has moved to its own project

**Comment by lcharkiewicz** [comment]
@kushmansingh are you going to open another PR with your changes in a proper ingress repo?

**Pull request closed without merging**
