### PR TITLE
Remove kubemark-scale from monitored suites, as we use it for testing

### PR DESCRIPTION
**Pull request by gmarek**
cc @wojtek-t @fejta 

@apelisse - can you merge this and push the changes to the SubmitQueue? Thanks.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/2048)

### CODE REVIEW

**Comment by wojtek-t** [comment]
lgtm

**Comment by apelisse** [comment]
@gmarek @fejta redeployed

**Comment by gmarek** [comment]
@apelisse - thanks.

**Pull request merged**
