### PR TITLE
[Vagrant+VBox+Ansible] use static ip + explicitly set API Server bind address

### LINKED ISSUE #696: [Ansible+Vagrant+VirtualBox] use static IP instead of DHCP
Currently on Vagrant we rewrite `/etc/hosts` with public IPs of nodes that were received at the time of provision in [vagrant-ansible.yml](https://github.com/kubernetes/contrib/blob/master/ansible/vagrant/vagrant-ansible.yml#L17), e.g.:

```
$ cat /etc/hosts 
172.28.128.5 kube-master
172.28.128.3 kube-node-1
172.28.128.4 kube-node-2
```

this is OK for quick testing, but after some time IP addresses of nodes may change (for example if you shutdown host for weekend), which will lead to communication failures between different Kubernetes parts.

I suggest to use fixed IP addresses at least on VirtualBox, where VirtualBox software DHCP server is used.

The question is how to properly select IP addresses range to use?

/cc: @eparis @danehans

### PR DESCRIPTION
**Pull request by rutsky**
Fixes #696 and #700 .

/cc @danehans @eparis @adamschaub

### CODE REVIEW

**Comment by danehans** [comment]
@rutsky LGTM

Tested successfully on my vagrant/coreos setup

/cc @eparis

**Comment by rutsky** [comment]
@eparis can you please take a look at this PR, since @danehans tested these changes?

I'll rebase #724 after you merge this.

**Comment by eparis** [comment]
i broke it merging something else  :-(

**Comment by eparis** [comment]
I also just generally don't like it because we are doing vbox custom things. Can you please look for any reasonable way to solve this in ansible instead of with hard coding and vbox specifics.  If you tell me no, there is nothing better I'll take it, but I'm not in love.

**Comment by rutsky** [comment]
Rebased.

@eparis this PR includes two things:

1. It adds Ansible variable `kube_apiserver_bind_address` that allows to specify bind address of API server: https://github.com/kubernetes/contrib/pull/712/commits/a3aacd1b39d7c82361d72db98c90f6dbb8e961b3

2. Changes Vagrant configuration to use static IP addresses for VMs on VirtualBox (https://github.com/kubernetes/contrib/pull/712/commits/cecbf160e880d03bd0954deeb50902151d68264c) and explicitly uses master IP in `kube_apiserver_bind_address` (https://github.com/kubernetes/contrib/pull/712/commits/7648fbc3fd4de8a346434f8e3ab7109c8554b439).

@eparis 
> I also just generally don't like it because we are doing vbox custom things. Can you please look for any reasonable way to solve this in ansible instead of with hard coding and vbox specifics.

I'm not really following you here. Vagrant+VirtualBox is specific environment that in one or another way requires specific configuration.
It's not possible to treat all Vagrant+VirtualBox quirks only in Ansible, because some information should be explicitly specified for Ansible, either from `group_vars/all`, or from Vagrantfile.
I chose to write proper Ansible environment in Vagrantfile because in this way it simplifies K8s deployment on Vagrant (just `vagrant up`, not `edit group_vars/all; vagrant up`).

By switching to static IPs instead of DHCP in VirtualBox I make VirtualBox configuration closer to other configurations (i.e. bare metal).
Currently hostnames are managed in Vagrant-configuration by explicitly writing `/etc/hosts` file in [vagrant-ansible.yml](https://github.com/kubernetes/contrib/blob/master/ansible/vagrant/vagrant-ansible.yml), so we can't use DHCP.

In ideal world Vagrant+VirtualBox configuration should be identical to bare metal configuration, but due to issues like https://github.com/mitchellh/vagrant/issues/2779 it's far from being identical to real world configurations.
There is no need of additional "Vagrant+VirtualBox" configuration in ideal world, because Vagrant+VirtualBox is trying to emulate real world configuration, i.e. bare metal.

**Comment by rutsky** [comment]
Note that I changed VBox IPs range from `172.30.0.0/24` to `172.32.0.0/24` in the last commit: https://github.com/kubernetes/contrib/pull/712/commits/740d6af5c3e52f804c26250daff11dbda6e486e1

`172.30.0.0` intersects with Flannel default IPs range: `172.16.0.0/12`.
Note, that I previously used not just random range, but range that VirtualyBox is actually assigned on my local setup.
So technically this PR is also fixes potential collision between VBox VMs IPs and Flanneld virtual IPs.

**Pull request merged**
