### PR TITLE
link to the official CONTRIBUTING.md doc

### PR DESCRIPTION
**Pull request by jfchevrette**
Instead of duplicating the info (along with invalid links), refer the user to the official CONTRIBUTING.md doc

### CODE REVIEW

**Comment by eparis** [comment]
Shouldn't we be using `https://releases.k8s.io/HEAD/CONTRIBUTING.md` ?

**Comment by eparis** [comment]
If you update the PR with the link to releases.k8s.io i'll happily merge

**Comment by jfchevrette** [comment]
Done. I'm new to the project and trying to help here and there while learning in the process.

Thanks for the feedback @eparis !

**Comment by eparis** [comment]
prefer a single squashed commit. LGTM.  will merge once you squash (I know it's a pain, sorry, and thank you!)

**Comment by jfchevrette** [comment]
There you go. Thanks!

**Pull request merged**
