### PR TITLE
Consider .png files as doc and don't rerun tests

### LINKED ISSUE #1566: retest-not-required-docs-only should count images as docs
E.g. the label was removed from [this PR](https://github.com/kubernetes/kubernetes/pull/30840) since it includes several png's referenced in the docs.

### PR DESCRIPTION
**Pull request by apelisse**
Fixes #1566

### CODE REVIEW

**Comment by eparis** [comment]
does it have to be caps?
/LGTM

**Comment by apelisse** [comment]
It's case insensitive. But the munger is not set-up yet in contrib

**Comment by foxish** [comment]
@apelisse @eparis It would've worked if you were an assignee. I think after the approvers mechanism is in place, the approvers would also be able to lgtm, even if they're not assigned. The bot should have posted a message that it wasn't honoring the `/lgtm` as you weren't an assignee.

**Pull request merged**
