### PR TITLE
s/purgeInteval/purgeInterval

### PR DESCRIPTION
**Pull request by bjoernhaeuser**
Use correct name for purgeInterval

### CODE REVIEW

**Comment by bjoernhaeuser** [comment]
I signed it!

**Comment by bjoernhaeuser** [comment]
Should I rebase onto current master?

**Comment by kow3ns** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2281#-:-KaiNA43uCXFVZ5FDJiq:bnfp4nl)*

**Comment by bjoernhaeuser** [comment]
@kow3ns I rebased to master, what happens next?

**Comment by bjoernhaeuser** [comment]
@kow3ns I think somehow the bot does not recognize your review :(

**Pull request closed without merging**
