### PR TITLE
[nginx-ingress-controller]: Add support for dynamic TLS records and spdy

### PR DESCRIPTION
**Pull request by aledbf**
requires #1236

### CODE REVIEW

**Comment by aledbf** [comment]
ping @bprashanth

**Comment by bprashanth** [comment]
LGTM

**Comment by bprashanth** [comment]
Does this apply cleanly on top of the other change? i noticed you're changing the version in that one too and sometimes github is dumb

**Comment by aledbf** [comment]
@bprashanth yes. Please publish the nginx-slim image

**Comment by bprashanth** [comment]
gcr.io/google-containers/nginx-slim:0.8 pushed

**Comment by aledbf** [comment]
@bprashanth awesome. Thanks

**Pull request merged**
