### PR TITLE
Ingress: Updated ingress docs, avoid nginx-alpha use.

### PR DESCRIPTION
**Pull request by kayrus**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1310)

### CODE REVIEW

**Comment by kayrus** [comment]
I signed it!

**Comment by kayrus** [comment]
I signed it!

**Comment by aledbf** [comment]
@kayrus why this change? The code in `nginx-alpha` contains the most important pieces required to build an ingress controller. The other two implementations are too complex (if you are trying to build a custom one from)

**Comment by kayrus** [comment]
@aledbf nginx-alpha doesn't contain `proxy_set_header Host $host;` inside the template. And when you are trying to switch to nginx with more complex config - it doesn't work out of the box. My approach was to resolve both problems.

**Comment by aledbf** [comment]
> And when you are trying to switch to nginx with more complex config - it doesn't work out of the box

What do you mean?

**Comment by kayrus** [comment]
@aledbf the amount of `maps` inside default nginx [template](https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx.tmpl) (not alpha) doesn't allow to allocate memory for them. nginx even can not start, controller logs errors. then healthz after 60 sec timeout and pod is being recreated again and again. increasing the `map_hash_bucket_size` doesn't help.

**Comment by aledbf** [comment]
@kayrus can you describe what/how are you running the ingress nginx controller?
I'm using that controller with more than 300 ingress rules without issues.

**Comment by kayrus** [comment]
@aledbf simple k8s [webapp demo](https://github.com/kayrus/k8s-webapp). Here is the [ingress config](https://github.com/kayrus/k8s-webapp/blob/master/exposed_80_port.yaml) which I used.

**Comment by bprashanth** [comment]
This readme should contain the absolute simplest nginx controller which is the alpha controller. I'm fine forking off another doc to containe a better example, but I don't want to complicate the instructions for writing a controller. I'm also fine adding a "known issues" section to nginx-alpha (i'd hoped the name was enough to surface that there were known issues).

**Comment by test-foxish** [comment]
recomputing cla status...

**Pull request closed without merging**
