### PR TITLE
Add Terraform/AWS

### PR DESCRIPTION
**Pull request by aknuds1**
Add support for deploying on AWS through [Terraform](http://terraform.io/). _Please note that this is completely unfinished, and written specifically with CoreOS in mind at this stage_.

This is intended for a simple staging setup, with two EC2 instances: One for the master and one for the worker.

The way you use it is like this:
1. Create a file 'aws-variables.sh', containing the following variables
    \* `AWS_ACCESS_KEY_ID`: Your AWS access key ID
    \* `AWS_SECRET_ACCESS_KEY`: Your secret AWS access key
    \* `AWS_REGION`: The AWS region you wish to deploy to
    \* `AWS_MASTER_IP`: The private IP you wish to assign to your master EC2 instance
    \* `AWS_WORKER_IP`: The private IP you wish to assign to your worker EC2 instance
    \* `AWS_KEY_NAME`: The name of the SSH key pair (registered in AWS) you wish to use
2. Execute `apply-terraform.sh`

`apply-terraform.sh` will invoke terraform on the 'staging.tf' file, which I suggest you read in order to figure out what is taking place while setting up the AWS infrastructure.

I am basically creating this PR in order to seek help from others in finishing this setup, as it's not yet working and I'm finding it difficult to figure out what to do.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/557)

### CODE REVIEW

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by aknuds1** [comment]
I signed the CLA

**Comment by grodrigues3** [comment]
[APPROVALNOTIFIER] The Following OWNERS Files Need Approval:

- **/**

We suggest the following people:
cc @bprashanth 
 You can indicate your approval by writing `/approve` in a comment
 You can cancel your approval by writing `/approve cancel`in a comment

**Comment by grodrigues3** [comment]
@aknuds1 thanks for using the `/approve` mechanism.  We're having some technical issues with the approvers mechanism rollout, so I added the label for you.

**Comment by aknuds1** [comment]
@foxish Thanks, this PR is no longer relevant though, at least to me 🙂 Closing it.

**Pull request closed without merging**
