### PR TITLE
Fix to respect CLA ping timeperiod.

### PR DESCRIPTION
**Pull request by balajismaniam**
- Updated PingNotication call in CLA munger with the correct startDate.

cc @foxish See https://github.com/kubernetes-incubator/node-feature-discovery/pull/20 for details.

### CODE REVIEW

**Comment by foxish** [comment]
I'm not entirely sure that is the fix to the pinger logic. Also, we run the same code in kubernetes/kubernetes and kubernetes/contrib and don't have those issues of repeated pings. Can you show us how you're running your deployment (arguments, logs, etc)?

**Comment by balajismaniam** [comment]
@foxish I did some more testing. You are right. This doesn't fix the ping frequency. I should have tested more before opening this PR. Sorry for the trouble. If you want, I can open a issue and close this PR. 

Following are the details of the deployment:

Args (I used `--period=30s` for testing. Rest of the args are same as the vanilla deployment.yaml): 
```yaml
command:
        - /mungegithub
        - --dry-run=false
        - --stderrthreshold=INFO
        - --http-cache-dir=$(HTTP_CACHE_DIR)
        - --organization=$(ORGANIZATION)
        - --project=$(PROJECT)
        - --pr-mungers=$(PR_MUNGERS)
        - --state=$(STATE)
        - --token-file=$(TOKEN_FILE)
        - --required-retest-contexts=$(REQUIRED_RETEST_CONTEXTS)
        - --required-contexts=$(REQUIRED_CONTEXTS)
        - --nonblocking-jenkins-jobs=$(NONBLOCKING_JENKINS_JOBS)
        - --jenkins-jobs=$(JENKINS_JOBS)
        - --presubmit-jobs=$(PRESUBMIT_JOBS)
        - --weak-stable-jobs=$(WEAK_STABLE_JOBS)
        - --do-not-merge-milestones=$(DO_NOT_MERGE_MILESTONES)
        - --admin-port=$(ADMIN_PORT)
        - --gcs-bucket=$(GCS_BUCKET)
        - --gcs-logs-dir=$(GCS_LOGS_DIR)
        - --pull-logs-dir=$(PULL_LOGS_DIR)
        - --pull-key=$(PULL_KEY)
        - --path-label-config=$(PATH_LABEL_CONFIG)
        - --period=30s
        - --block-path-config=$(BLOCK_PATH_CONFIG)
        - --repo-dir=$(REPO_DIR)
        - --test-owners-csv=$(TEST_OWNERS_CSV)
        - --number-of-old-test-results=$(NUMBER_OF_OLD_TEST_RESULTS)
        - --fixes-issue-reassign=$(FIXES_ISSUE_REASSIGN)
        - --blunderbuss-reassign=$(BLUNDERBUSS_REASSIGN)
        - --generated-files-config=$(GENERATED_FILES_CONFIG)
        - --chart-url=$(CHART_URL)
        - --history-url=$(HISTORY_URL)
        - --enable-md-yaml=$(ENABLE_MD_YAML)
        - --label-file=$(LABEL_FILE)
        - --triager-url=$(TRIAGER_URL)
        - --cla-status-context=$(CLA_STATUS_CONTEXT)
```

Configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-feature-discovery-sq-config
data:
  # basic config options.
  config.http-cache-dir: /cache/httpcache
  config.organization: kubernetes-incubator
  config.project: node-feature-discovery
  config.pr-mungers: blunderbuss,cla,lgtm-after-commit,submit-queue,needs-rebase,lgtm-handler
  config.state: open
  config.token-file: /etc/secret-volume/token
  gitrepo.repo-dir: /gitrepos
  gitrepo.enable-md-yaml: "false"

  # test-options feature options.
  test-options.required-retest-contexts: "\"\""

  # submit-queue options.
  submit-queue.required-contexts: "continuous-integration/travis-ci/pr"
  submit-queue.nonblocking-jenkins-jobs: "\"\""
  submit-queue.jenkins-jobs: "\"\""
  submit-queue.presubmit-jobs: "\"\""
  submit-queue.weak-stable-jobs: "\"\""
  submit-queue.do-not-merge-milestones: "\"\""
  submit-queue.admin-port: "9999"
  submit-queue.chart-url: ""
  submit-queue.history-url: ""

  # options used by the GCS feature.
  gcs.gcs-bucket: ""
  gcs.gcs-logs-dir: ""
  gcs.pull-logs-dir: ""
  gcs.pull-key: ""

  # munger specific options.
  path-label.path-label-config: ""
  block-path.block-path-config: ""
  flake-manager.test-owners-csv: ""
  old-test-getter.number-of-old-test-results: "0"
  assign-fixes.fixes-issue-reassign: "false"
  blunderbuss.blunderbuss-reassign: "false"
  size.generated-files-config: ""
  check-labels.label-file: "/gitrepos/node-feature-discovery/labels.yaml"
  issue-categorizer.triager-url: ""
  cla.cla-status-context: "cla/linuxfoundation"
```

```sh
I1020 00:53:07.178157       1 mungegithub.go:100] {
  "Org": "kubernetes-incubator",
  "Project": "node-feature-discovery",
  "State": "open",
  "Labels": [],
  "TokenFile": "/etc/secret-volume/token",
  "Address": ":8080",
  "WWWRoot": "www",
  "HTTPCacheDir": "/cache/httpcache",
  "HTTPCacheSize": 1000,
  "MinPRNumber": 0,
  "MaxPRNumber": 9223372036854775807,
  "DryRun": false,
  "BaseWaitTime": 0,
  "MinIssueNumber": 0,
  "PRMungersList": [
    "blunderbuss",
    "lgtm-after-commit",
    "submit-queue",
    "needs-rebase",
    "lgtm-handler",
    "cla"
  ],
  "IssueReportsList": [],
  "Once": false,
  "Period": 30000000000,
  "StateMachineEnabled": false,
  "Aliases": null,
  "Repos": null,
  "GCSInfo": null,
  "TestOptions": null
}
I1020 00:53:07.178240       1 github.go:228] Made 0 API calls since the last Reset 0.000000 calls/sec
I1020 00:53:07.178346       1 features.go:55] Initializing feature: aliases
I1020 00:53:07.178360       1 features.go:55] Initializing feature: gitrepos
I1020 00:53:29.805781       1 repo-updates.go:187] Loaded config from /gitrepos/node-feature-discovery:31ec89474a5059212613f64920baea596930d954
I1020 00:53:29.805814       1 features.go:55] Initializing feature: google-cloud-storage
I1020 00:53:29.805820       1 features.go:55] Initializing feature: test-options
I1020 00:53:29.805841       1 mungers.go:92] {
  "BlunderbussReassign": false
}
I1020 00:53:29.805845       1 mungers.go:93] Initialized munger: blunderbuss
I1020 00:53:29.805862       1 mungers.go:92] {}
I1020 00:53:29.805870       1 mungers.go:93] Initialized munger: lgtm-after-commit
I1020 00:53:29.806039       1 mungers.go:92] {
  "BlockingJobNames": [],
  "NonBlockingJobNames": [],
  "PresubmitJobNames": [],
  "WeakStableJobNames": [],
  "FakeE2E": false,
  "Committers": "",
  "RequiredStatusContexts": [
    "continuous-integration/travis-ci/pr"
  ],
  "DoNotMergeMilestones": [],
  "RequiredRetestContexts": [],
  "RetestBody": "@k8s-bot test this [submit-queue is verifying that this PR is safe to merge]",
  "Metadata": {
    "ProjectName": "Node-Feature-Discovery",
    "ChartUrl": "",
    "HistoryUrl": "",
    "RepoPullUrl": "https://github.com/kubernetes-incubator/node-feature-discovery/pulls/"
  },
  "AdminPort": 9999
}
I1020 00:53:29.806052       1 mungers.go:93] Initialized munger: submit-queue
I1020 00:53:29.806061       1 mungers.go:92] {}
I1020 00:53:29.806064       1 mungers.go:93] Initialized munger: needs-rebase
I1020 00:53:29.806074       1 mungers.go:92] {}
I1020 00:53:29.806080       1 mungers.go:93] Initialized munger: lgtm-handler
I1020 00:53:29.806093       1 mungers.go:92] {
  "CLAStatusContext": "cla/linuxfoundation"
}
I1020 00:53:29.806099       1 mungers.go:93] Initialized munger: cla
I1020 00:53:29.806103       1 mungegithub.go:63] Running mungers
I1020 00:53:31.106615       1 repo-updates.go:187] Loaded config from /gitrepos/node-feature-discovery:31ec89474a5059212613f64920baea596930d954
I1020 00:53:33.042487       1 github.go:1635] For 20: supposedly there weren't more comments, but we asked anyway and found 39 more.
I1020 00:53:33.497563       1 github.go:1015] For 20: supposedly there weren't more events, but we asked anyway and found 100 more.
I1020 00:53:33.651705       1 github.go:1015] For 20: supposedly there weren't more events, but we asked anyway and found 94 more.
I1020 00:53:35.633354       1 github.go:1661] Commenting in 23: "[CLA-PING] @danielscottt\n\nThanks for your pull request.  It looks like this may be your first contribution to a CNCF open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).\n\n:memo: **Please visit <https://identity.linuxfoundation.org/projects/cncf> to sign.**\n\nOnce you've signed, please reply here (e.g. \"I signed it!\") and we'll verify.  Thanks.\n\n---\n\n- If you've already signed a CLA, it's possible we don't have your GitHub username or you're "
I1020 00:53:35.840099       1 github.go:228] Made 28 API calls since the last Reset 0.976912 calls/sec
I1020 00:53:35.840875       1 mungegithub.go:85] Sleeping for 23.965231806s
I1020 00:53:59.865677       1 mungegithub.go:63] Running mungers
I1020 00:54:01.305072       1 repo-updates.go:187] Loaded config from /gitrepos/node-feature-discovery:31ec89474a5059212613f64920baea596930d954
I1020 00:54:02.734924       1 github.go:1635] For 20: supposedly there weren't more comments, but we asked anyway and found 39 more.
I1020 00:54:03.102034       1 github.go:1015] For 20: supposedly there weren't more events, but we asked anyway and found 100 more.
I1020 00:54:03.400995       1 github.go:1015] For 20: supposedly there weren't more events, but we asked anyway and found 94 more.
I1020 00:54:05.311030       1 github.go:1661] Commenting in 23: "[CLA-PING] @danielscottt\n\nThanks for your pull request.  It looks like this may be your first contribution to a CNCF open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).\n\n:memo: **Please visit <https://identity.linuxfoundation.org/projects/cncf> to sign.**\n\nOnce you've signed, please reply here (e.g. \"I signed it!\") and we'll verify.  Thanks.\n\n---\n\n- If you've already signed a CLA, it's possible we don't have your GitHub username or you're "
I1020 00:54:05.573394       1 github.go:228] Made 28 API calls since the last Reset 0.941730 calls/sec
I1020 00:54:05.573490       1 mungegithub.go:85] Sleeping for 24.292178352s
```

**Comment by foxish** [comment]
@balajismaniam I think I know why this is happening. it's because within the notification code, it is looking for the bot to have authored the cla-ping (https://github.com/kubernetes/contrib/blob/b70447aa59ea14468f4cd349760e45b6a0a9b15d/mungegithub/mungers/matchers/comment/interactions.go#L91) but the bot is currently hardcoded to `k8s-merge-bot`. If you added your bot's name there, and made a new PR with the added matcher, I'd be glad to get that merged in.

**Comment by balajismaniam** [comment]
@foxish Thanks for working with me on this and opening the issue. I will submit a new PR with the appropriate changes. Closing this one.

**Comment by balajismaniam** [comment]
@foxish It seems like the bot name is hard-coded in couple more places and it affects the lgtm_handler and flake_manager mungers. See the following: 

https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/mungerutil/util.go#L29
https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/mungerutil/util.go#L112
https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/lgtm_handler.go#L137

https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/sync/issue-sync.go#L30
https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/flake-manager.go#L331

I will be using the lgtm_handler munger and as such I don't think it is a good idea to upstream the changes for making it work for the nfd-merge-bot. For now, I will run a forked version of mungegithub on our incubator repo. Let me know your thoughts on this. 

Parameterizing the bot name is better. Let me know if I can help with it.

**Comment by apelisse** [comment]
@foxish Do we still want to fix that?

**Pull request closed without merging**
