### PR TITLE
add myself to blunderbuss for pkg/client/leaderelection

### PR DESCRIPTION
**Pull request by mikedanese**
I'd like to field these initially

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
Won't take affect until we build & restart-- @eparis has been doing that, I think.

**Comment by mikedanese** [comment]
I can kick it once the PR goes in

**Comment by eparis** [comment]
That's fine, you should be able to 'make' from head, upload the image to gcr, and then do a rolling update to rc.yaml.

**Comment by eparis** [comment]
(rc.yaml in your local tree will be updated when you do the make)

**Pull request merged**
