### PR TITLE
mungegithub: Fix Godeps pointing to non-exisitng commit

### PR DESCRIPTION
**Pull request by apelisse**

### CODE REVIEW

**Comment by apelisse** [comment]
Ok, maybe this one will do it. :-)

**Comment by eparis** [comment]
self vendoring is pretty much terrible....

Can/should we move `vendor` back to the top level?

**Comment by apelisse** [comment]
I can not agree more. This is terribly  broken, and painful to maintain.

I can give it a try, I think it would be much much simpler.

**Comment by krzyzacy** [comment]
It works at least, although a lot of things still need to be manually done.. godep restore/save will delete a bunch of stuff :-(

**Comment by krzyzacy** [comment]
maybe still get this in

**Pull request merged**
