### PR TITLE
[startup-script] Don't cache apk update results

### PR DESCRIPTION
**Pull request by yuvipanda**
This makes the image smaller.

### CODE REVIEW

**Comment by yuvipanda** [comment]
/cc @eparis @foxish @lavalamp (from OWNERS file)

This snippet is great, am very glad I found it :)

I'd also love to pin the FROM to specific version of alpine so this is fully reproducible.

**Comment by yuvipanda** [comment]
ALthough I just realized that nsenter is in base alpine, so am unsure why these extra packages are here at all.

**Comment by yuvipanda** [comment]
For those wondering, bash seems to be required when passing the STARTUP_SCRIPT (which is multiline) to `bash -c`. With just sh that seems to not work very well.

**Comment by yuvipanda** [comment]
After a day of being very frustrated, it turns out util-linux is needed because even though alpine ships with an `nsenter`, it is from busybox and really old. I wish this had been documented, so will do so soon.

**Comment by yuvipanda** [comment]
Anyone? :)

**Comment by yuvipanda** [comment]
Anyone? :)

**Comment by tonglil** [comment]
I would like to see this approved as well

**Review by foxish — APPROVED** [review]

**Comment by foxish** [comment]
I don't think this code is maintained at this point. If it is useful, it should find a new home. 

/lgtm
/approve

**Pull request merged**
