### PR TITLE
matchers: make them more generic

### PR DESCRIPTION
**Pull request by apelisse**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1659)

### CODE REVIEW

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by foxish** [comment]
@apelisse this can be closed?

**Comment by apelisse** [comment]
Yeah, probably :-(

**Comment by grodrigues3** [comment]
[APPROVALNOTIFIER] The Following OWNERS Files Need Approval:

- **mungegithub**

We suggest the following people:
cc @bprashanth 
 You can indicate your approval by writing `/approve` in a comment
 You can cancel your approval by writing `/approve cancel`in a comment

**Pull request closed without merging**
