### PR TITLE
Add exclusion for HA.yaml files as they are part of core tests that need to be editable.

### PR DESCRIPTION
**Pull request by timothysc**
My regex is rusty, hopefully I got it right. 
/cc @eparis

### CODE REVIEW

**Comment by timothysc** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/30514

**Comment by apelisse** [comment]
Why do you have extra parenthesis around `yaml`?

**Comment by timothysc** [comment]
> Why do you have extra parenthesis around yaml?

I put it there in case I needed to ```|``` extensions but it's not needed. 
Happy to remove if desired.

**Comment by apelisse** [comment]
Yeah it doesn't make a difference,

**Comment by timothysc** [comment]
Hmm it does not look like the bot is respecting this rule?  Does the bot need to be reset?

**Comment by apelisse** [comment]
Yes, we would have to redeploy the bot, which may not have happened yet. 
Let me check ...

Image:	docker.io/foxish/submit-queue:2016-07-29-68fd252

It hasn't been deployed in quite some time. I'll try to let you know when it happens.

**Pull request merged**
