### PR TITLE
Fix configMaps

### PR DESCRIPTION
**Pull request by eparis**
contrib configMap was out of date.
some configMaps didn't have protected-branches
update some help text

### CODE REVIEW

**Comment by eparis** [comment]
@rmmh who did the approval-munger get turned on if the configmap wasn't updated?

**Comment by eparis** [comment]
@foxish     preference for /approve and /lgtm to make sure the bot is running ok....

**Comment by rmmh** [comment]
@grodrigues3 disabled the approval notifier because it was looping repeatedly, he should have more context.

**Comment by eparis** [comment]
it's back off. and if we merge this it is off in git too!, so it won't come back.

@grodrigues3 this is the reason not to make changes to config without merging them to git...

**Comment by eparis** [comment]
I'm an idiot. It was fixed int git, but not in production. So I put it back in git.  I'm an idiot.

**Comment by foxish** [comment]
@eparis, Is this fix to the configmap already in the running version of the SQ?

**Comment by eparis** [comment]
For contrib, yes.

**Pull request merged**
