### PR TITLE
[submit queue] Add jsafrane to submit queue whitelist

### PR DESCRIPTION
**Pull request by eparis**

### CODE REVIEW

**Comment by eparis** [comment]
@jsafrane

**Comment by eparis** [comment]
Jan works for RH on our storage team and having to add 'ok-to-merge' is just a PITA.

**Comment by bgrant0607** [comment]
@eparis Did you regenerate the list, or just add this by hand?

**Comment by eparis** [comment]
This one was by hand. the list is generated with a combination of those people whom have explicit read/write access to the repo and some people who are manually added to the list.

It would be a lot easier for us if we could give 'read' access to the main kube repo to certain teams, then we at Red Hat wouldn't have to manage as many places, and that might be a better solution than adding Jan manually....

Or maybe I should just add people to both the RH team and to the contributors team...

**Comment by bgrant0607** [comment]
I thought the list was generated from kubernetes-collaborators?

**Comment by bgrant0607** [comment]
BTW, we're moving towards eliminating the goog-* github teams, in favor of sig and component teams (e.g., kubectl).

**Pull request merged**
