### PR TITLE
Remove haproxy zombie processes left after a haproxy reload

### PR DESCRIPTION
**Pull request by aledbf**

### CODE REVIEW

**Comment by alex-mohr** [comment]
@aledbf do you know someone familiar with this code to review?

**Comment by bprashanth** [comment]
LGTM
@aledbf can you please move the godep to a separate commit as specified in the last line of https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md#using-godep ?

**Comment by bprashanth** [comment]
Thanks

**Comment by aledbf** [comment]
@bprashanth yes, sorry about that.

**Pull request merged**
