### PR TITLE
Update go-github for mungegithub

### PR DESCRIPTION
**Pull request by apelisse**
Update to a new version, that will allow us to use Assignee**s**.
Because go-github made breaking changes to their API, the diff is kind of ugly. I've tried to carefully replace everywhere (thanks to go compiler). `make test` is passing for me.

### CODE REVIEW

**Comment by apelisse** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
@apelisse For future reference, 2 separate commits, one to update the godep and one for the fixes to make it work, would have been much easier to review.

Looks pretty mechanical, but I don't know if any deep copies are needed.

Anyway, LGTM, AFAICT.

**Comment by apelisse** [comment]
Thanks for the review.
I can't convince myself that I should commit broken code ...

**Comment by bgrant0607** [comment]
@apelisse How is this broken? Or do you mean that the other PR is broken?

**Comment by apelisse** [comment]
Nothing is broken. I was referring to the "2 seperate commits". If I split the commit in two, one of the commits would be broken.

**Comment by bgrant0607** [comment]
@apelisse You could always squash before merging.

**Comment by apelisse** [comment]
@bgrant0607 OK I'll do it like this next time!

**Comment by lavalamp** [comment]
Please split this into two commits. It's OK that they won't compile independently. It's more important to enable reviewers to see the changes made in our code separate from the dep changes.

**Comment by apelisse** [comment]
@lavalamp done

**Comment by lavalamp** [comment]
Looks safe. LGTM

**Pull request merged**
