### PR TITLE
Fixes ipv4 address resolution of etcd peers in etcd config

### PR DESCRIPTION
**Pull request by adamschaub**
Simple fix to get static etcd cluster configuration working correctly.

### CODE REVIEW

**Comment by rutsky** [comment]
LGTM. Thought I would prefer `hostvars[host].ansible_default_ipv4.address` instead of `hostvars[host]['ansible_default_ipv4']['address']`

**Comment by eparis** [comment]
agreed, are you willing to use the @rutsky style?

**Comment by adamschaub** [comment]
@rutsky Agreed, definitely more attractive. @eparis Refactored accordingly.

**Comment by rutsky** [comment]
@adamschaub  BTW, since you touching this code, what about this approach for handling comma as separator?

```
{% for host in groups[etcd_peers_group] -%}
  {{ hostvars[host]['ansible_hostname'] }}={{ etcd_peer_url_scheme }}://{{ hostvars[host].ansible_default_ipv4.address }}:{{ etcd_peer_port }}
  {%- if not loop.last -%},{%- endif -%}
{%- endfor -%}
```

**Pull request merged**
