### PR TITLE
Block PRs on etcd3

### PR DESCRIPTION
**Pull request by wojtek-t**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1939)

### CODE REVIEW

**Comment by mml** [comment]
FYI @kubernetes/test-infra-admins

**Comment by wojtek-t** [comment]
@apelisse @fejta can someone push this change?

**Comment by fejta** [comment]
Yes, @spxtr will you show @ixdy how to do this tomorrow?

**Comment by wojtek-t** [comment]
Actually - is it about prow? This PR just changed submit-queue.

**Comment by apelisse** [comment]
Agreed, this is a change for the submit-queue. I'll try to do it, please remind me if I forgot (95% chances I will ... :-/)

**Comment by apelisse** [comment]
Should be done, finally

**Pull request merged**
