### PR TITLE
Test result comparator - main.

### PR DESCRIPTION
**Pull request by gmarek**
cc @wojtek-t @mikedanese @davidopp @fgrzadkowski @mwielgus @piosz 

I put godeps in this directory, assuming that @mikedanese refactor will go through. 

Originally I had this in few commits, but after fun with godeps I have only one now. If requested I'll split it for easier review. (I'll certainly split off godeps as a first commit).

I'm sending it now to figure out who can is willing to review this tool. Normally it'd be @wojtek-t, but he's out until Feb and I'd rather have it merged sooner - it's not strictly necessary, as it's a standalone tool, so I won't need to do any rebases and it'll be available as soon as some reasonable PR is created.

I think that @mwielgus is the second best candidate, but I'm not sure he'll have time.

### CODE REVIEW

**Comment by mwielgus** [comment]
LGTM

**Comment by mwielgus** [comment]
Verifying hack/../hack/verify-flags-underscore.py
FAILED

**Comment by mwielgus** [comment]
all green, merging

**Comment by eparis** [comment]
Is this the cause of: https://travis-ci.org/kubernetes/contrib/jobs/106259932 ?

**Comment by gmarek** [comment]
Yes, it seems it is. I'll fix it in few minutes.

**Pull request merged**
