### PR TITLE
use publicly available event-exporter image

### PR DESCRIPTION
**Pull request by gytisgreitai**
Change url in examples from private `google.com/vmik-k8s-testing-0` to public `gcr.io/google-containers`

### CODE REVIEW

**Comment by crassirostris** [comment]
Whoops. Thanks!

/lgtm
/approve no-issue

**Comment by gytisgreitai** [comment]
@crassirostris since you're here, could you explain where under SD those logs should appear?

**Comment by crassirostris** [comment]
@gytisgreitai Hm, I thought I documented it. Under GKE Cluster. I'll add this to the readme, thanks!

**Comment by gytisgreitai** [comment]
Ok, this seems to be working. The one thing that confused me is the buffer size is quite large if you are testing this on a small cluster. I had to do `-sink-opts="-max-buffer-size=5"` to make this more feasable for testing

**Comment by crassirostris** [comment]
@gytisgreitai What was problematic? 5 seconds of flush delay or memory usage?

**Comment by gytisgreitai** [comment]
ah ok, you are flushing after 5 seconds or 100 events by default whichever comes first? 
Initially I thought that you were flushing only after 100 events, so I decreased that to max-buffer-size=5 and started seeing events, but probably this was just some timing/lag issue. 

Sorry for the confusion. All working fine, thanks!

**Comment by crassirostris** [comment]
Thank you! :)

**Comment by piosz** [comment]
/lgtm
Thanks!

**Pull request merged**
