### PR TITLE
add opennebula provider to vagrantfile in ansible folder

### PR DESCRIPTION
**Pull request by rchicoli**
I guess the title and the changes are clear enough

### CODE REVIEW

**Comment by rchicoli** [comment]
I signed it!

**Comment by rchicoli** [comment]
cc @ingvagabund

**Comment by ingvagabund** [comment]
```sh
$ vagrant  up
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: <provider config: opennebula>
Line number: 193
Message: NameError: uninitialized constant TEMPLATE_ID
Did you mean?  Tempfile
```

**Comment by ingvagabund** [comment]
@rchicoli can you squash the commits?

**Comment by rchicoli** [comment]
@ingvagabund I've rebased the PR and change `TEMPLATE_ID` to an integer for better clarifications

A sample configuration would look like this:

```yaml
  config.ssh.username = "root"
  config.ssh.private_key_path = "/home/tester/.ssh/id_rsa"
 
  opennebula.endpoint = "http://one.example.com:2633/RPC2"
  opennebula.username = "tester"
  opennebula.password = "secret1234"
  opennebula.template_id = 15
  opennebula.title = n.vm.hostname
  opennebula.cpu = 8
  opennebula.memory = 4096
  opennebula.vcpu = 8
```

Please, let me know if I should change something else.

**Pull request merged**
