### PR TITLE
blunderbuss updates

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by dchen1107** [comment]
lgtm

**Comment by dchen1107** [comment]
Can you update by adding pkg/kubelet to include node team? Or I can handle it in a separate pr?

**Comment by lavalamp** [comment]
I don't think we can add teams, just individuals.

(I mean anything is possible given time, but as it works today...)

**Comment by dchen1107** [comment]
I mean everyone in node team. But I guess it should be ok now since they are routing to us all the time anyway.

**Pull request merged**
