### PR TITLE
Fix godeps

### PR DESCRIPTION
**Pull request by apelisse**

### CODE REVIEW

**Comment by krzyzacy** [comment]
so webhooks-publisher/hook.go will automatically updated? and I assume the vendor dir also need to be re-commit?

**Comment by apelisse** [comment]
I'll fix the pr, thanks :-)

**Comment by apelisse** [comment]
image
All the changes!

**Comment by krzyzacy** [comment]
I feel like since I'm not a maintainer I cannot give you lgtm labels...

**Comment by krzyzacy** [comment]
@k8s-bot GIVE ANTOINE LGTM NOW

**Comment by eparis** [comment]
/me needs to learn that new command `GIVE ANTOINE LGTM NOW`!!!

**Comment by apelisse** [comment]
Anyone can give lgtm with the command iff he's assigned :-)

**Comment by krzyzacy** [comment]
@k8s-bot good boy

**Comment by krzyzacy** [comment]
@apelisse ehmmm, seems I'm still get an error

senlu@senlu:~/work/src/k8s.io/contrib/mungegithub$ godep restore
# cd /usr/local/google/home/senlu/work/src/k8s.io/contrib; git checkout 4aaa75aed09fd919b82ee1cac8c6d47f8fd0e81c
fatal: reference is not a tree: 4aaa75aed09fd919b82ee1cac8c6d47f8fd0e81c
godep: error restoring dep (k8s.io/contrib/test-utils/utils): exit status 128
godep: Error restoring some deps. Aborting check.

**Comment by apelisse** [comment]
Yeah, I think I know. This is really painful ...

**Pull request merged**
