### PR TITLE
[cluster-autoscaler]: Add AWS Support

### PR DESCRIPTION
**Pull request by iterion**
Adding support for scaling AWS AutoScalingGroups. I've tested this in a test cluster on AWS (with a few more changes needed to allow this to work on Kubernetes v1.2) and everything seemed to function correctly.

It's currently a bit messy to use AWS. You must specify `--cloud-provider=aws` and provide the ASG name and zone in a GCE formatted url: `https://content.googleapis.com/compute/v1/projects/dummy/zones/us-east-1a/autoscalingGroupName`

PTAL and let me know how I can improve this to get it merged. I haven't yet tested this against a v1.3 cluster or against a GCE cluster.

### CODE REVIEW

**Comment by pbitty** [comment]
Hi @iterion, we are both working on the same problem.  :)  Would you be interested in joining efforts?

I took a slightly different approach with extracting the interface for the providers to implement, and I hid the `migConfig` implementation behind the provider.  The idea being that each provider has its own config with its own format.  This would help avoid having to share formats and fields between the two configs.

I was about to implement the AWS provider when I saw your PR.  Here's [my current progress](https://github.com/Wattpad/kubernetes-contrib/pull/4).

Are you interested in merging the approaches at all?

**Comment by davidopp** [comment]
@justinsb

**Comment by mwielgus** [comment]
cc: @piosz @jszczepkowski @fgrzadkowski

**Comment by mwielgus** [comment]
Great! Thank you for this contribution. We definitely want to have it merged fast. However due to tight schedule of 1.3 we took a little bit of technical debt here which we would like to pay back before we onboard other cloud providers. 
This will include an introduction of interfaces for other cloud providers and a bit of code refactoring. We hope to have it done around Wed-Thu next week. I will create an umbrella issue for this effort so you can track the progress. 
Should you have some questions about the code or would like a code/mechanics/logic walkthrough or ask about the future plans we can schedule a small video conference sometime late next week.

**Comment by pbitty** [comment]
Hi @mwielgus, I would be interested in having a video conference to talk about this.

I am compiling some questions.  I'll try to ask them here or in a GH issue first, if that helps.

**Comment by mwielgus** [comment]
@pbitty Cool, any preference regarding date/time?

**Comment by iterion** [comment]
@pbitty definitely interested in cooperating on this, no sense in duplicating work! I think your approach is a lot cleaner. I basically just hacked it until it worked, aiming to do the bare minimum refactor :)

@mwielgus I'd also like to join in on the conference call and am happy to help out with tech debt. As for late next week, my schedule is pretty open. I'm almost always available from 11am - 5pm CST. Please let me know if there is any way I can help out with the tech debt effort?

**Comment by pbitty** [comment]
I am generally available between 11am and 5pm EST.  Is there a day this week that works best for everyone?

**Comment by mwielgus** [comment]
Umbrella issue: https://github.com/kubernetes/contrib/issues/1311

Ok, then lets meet on Thursday, 2016/07/07, 12:00 EDT / 11:00 CDT / 18:00 CEST. Does it work for everyone?

**Comment by pbitty** [comment]
That time works for me.

**Comment by iterion** [comment]
That time also works for me, see you all then.

I'm also going to close this PR as we now have #1311 to track the related work.

**Comment by pbitty** [comment]
Thanks for the video call @mwielgus @iterion, @andrewsykim.

@iterion, feel free to ping myself and @andrewsykim to pair on this.  I'll be away next week but @andrewsykim is around.

**Comment by andrewsykim** [comment]
@iterion I've been taking a look into the AWS implementation for this interface https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/cloudprovider/cloud_provider.go. Is there a fork you have that I can follow so we don't duplicate the work? If you haven't started that implementation I wouldn't mind submitting a PR against your fork.

**Comment by iterion** [comment]
@andrewsykim thanks for checking in. I haven't gotten around to implementing the new interface yet. Feel free submitting a PR against my fork, I can definitely be available to review and/or help out.

I'm also @iterion on the Kubernetes slack channel, if you want more real time communication for questions.

**Pull request closed without merging**
