### PR TITLE
Move test-webserver to kubernetes/test/images

### LINKED ISSUE #2689: Remove test-webserver code
Part of https://github.com/kubernetes/kubernetes/pull/48494 test-webserver code has been moved to kubernetes/tests so the code needs to be remove from contrib project.

### PR DESCRIPTION
**Pull request by mkumatag**
PR https://github.com/kubernetes/kubernetes/pull/48494 has been created to move to kubernetes/test/images

Fixes #2689

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm

**Comment by ixdy** [comment]
Maybe leave a `README.md` in `for-demos/test-webserver` that points to the new location, similar to what we have for https://github.com/kubernetes/contrib/tree/master/ingress/controllers and others?

**Comment by mkumatag** [comment]
@ixdy added redirect notice in the README.md file, PTAL

**Comment by mkumatag** [comment]
Ping @mikedanese

**Pull request merged**
