### PR TITLE
ansible: use hostname instead of IP for flannel config

### LINKED ISSUE #243: ansible: failed load flannel config file if use IP in inventory
TASK: [flannel | Load the flannel config file into etcd] ********************** 
failed: [10.66.15.133 -> 10.66.15.133] => {"changed": true, "cmd": "/usr/bin/etcdctl --no-sync --peers=http://10.66.15.133:2379 set /cluster.local/network/config < /tmp/flannel-conf.json", "delta": "0:00:00.214135", "end": "2015-11-15 01:33:17.547932", "rc": 4, "start": "2015-11-15 01:33:17.333797", "warnings": []}
stderr: Error:  501: All the given peers are not reachable (failed to propose on members [http://10.66.15.133:2379] twice [last error: Put http://10.66.15.133:2379/v2/keys/cluster.local/network/config: dial tcp 10.66.15.133:2379: connection refused]) [0]

FATAL: all hosts have already failed -- aborting

### PR DESCRIPTION
**Pull request by gouyang**
fixes #243

Signed-off-by: Guohua Ouyang gouyang@redhat.com

### CODE REVIEW

**Comment by eparis** [comment]
I kinda hate ansible_fqdn, as it resolves to 'localhost.localdomain' in too many situations for people.

I think what I want to do to fix all of this non-sense it to make etcd stuff use `ansible_default_ipv4.address` most places, and set etcd listen_client and list_peer to 0.0.0.0

I keep meaning to send a PR for that, I'll try to do it today and see what you think.

**Comment by gouyang** [comment]
> I kinda hate ansible_fqdn, as it resolves to 'localhost.localdomain' in too many situations for people.

This is a problem, I have to add a host entry to /etc/hosts to make it work actually.

**Comment by danehans** [comment]
I agree with @eparis and ansible_fqdn does not work in my environment. I will be submitting a PR to change to ansible_default_ipv4.address

**Comment by eparis** [comment]
closing because fqdn doesn't work either. Will look for @danehans PR to set it to IP

**Comment by danehans** [comment]
@eparis here is the PR to address this issue: https://github.com/kubernetes/contrib/pull/596

**Pull request closed without merging**
