### PR TITLE
Add netperf tester tool

### PR DESCRIPTION
**Pull request by BenTheElder**
Adds a tool for running netperf tests on a k8s cluster.

### CODE REVIEW

**Comment by BenTheElder** [comment]
From the previous PR over at: https://github.com/kubernetes/kubernetes/pull/12838

Here are some example results from a GCE cluster for the iptables and userspace proxy.
- Raw CSV data: https://gist.github.com/BenTheElder/8ad343913fbe876e219a
- Histogram of mean latency:
gce-netperf-histogram

Tests were run with:
```
export KUBERNETES_PROVIDER=gce
export NUM_MINIONS=4
export KUBE_ENABLE_CLUSTER_MONITORING=google
export KUBE_ENABLE_CLUSTER_UI=false
cluster/kube-up.sh
go run netperf-tester/netperf_tester.go --output=$HOME/gce-netperf-userspace.csv
```

**Comment by thockin** [comment]
lgtm

**Comment by erictune** [comment]
X and y axis labels reversed.

**Comment by BenTheElder** [comment]
Huh, I thought I copied over the right one. Fixing, thanks. I mis-labeled
them when I made the histogram the first time on the issue over at k8s.
Swapping the image out now.

**Comment by BenTheElder** [comment]
Should be fixed now.

**Pull request merged**
