### PR TITLE
Add GoDoc Widget

### PR DESCRIPTION
**Pull request by asifdxtreme**

### CODE REVIEW

**Comment by asifdxtreme** [comment]
@foxish @eparis , can you please help me to see what went wrong in CI as I only changed the docs

**Comment by spiffxp** [comment]
/close
closing/reopening to retrigger travis

**Comment by asifdxtreme** [comment]
@spiffxp Can you please help me to merge this PR

**Comment by kevin-wangzefeng** [comment]
@asifdxtreme Thanks for your fix, I saw there are couple of similar changes to different repos, can you please create an umbrella issue (probably in kubernetes/contrib) and link all the PRs to it. That should be helpful to others understanding the changes, though they are small.

**Comment by lavalamp** [comment]
Do we really want to advertise the godoc for this repo? It's not really a cohesive package. Everything in this repo should get moved to a better home.

**Comment by lavalamp** [comment]
I'll let @foxish or @eparis, whoever shows up next, decide.

**Comment by foxish** [comment]
Looking at things that are in contrib now and corresponding docs in https://godoc.org/github.com/kubernetes/contrib, I don't think the godoc is really useful. 

/close

**Pull request closed without merging**
