### PR TITLE
update kube-addons scripts with upstream version

### PR DESCRIPTION
**Pull request by rutsky**
This fixes issues #626 and #667.

Now `kube-addon-update.sh` and `kube-addons.sh` downloaded from master
branch of Kubernetes project.

Also adds restart notification for kube-addons when scripts are updated.

Upstream version of these scripts uses custom Docker image with Python
when system Python is not available.
This image is built if Ansible runs on Core OS.

Tested on Vagrant+VirtualBox+Ansible+Core OS.

/cc: @danehans, @eparis

### CODE REVIEW

**Comment by danehans** [comment]
@rutsky @eparis this PR works for me in my coreos testbed. @ingvagabund if you have time, could you test this patch against your testbed?

**Comment by ingvagabund** [comment]
@danehans sorry for my later response. I have run my CI and nothing bad has happened so far.

**Comment by danehans** [comment]
@ingvagabund as always, thank you for testing. We're working on CI, so hopefully I'll stop asking you to test stuff... lol!

**Comment by danehans** [comment]
@rutsky Awesome work. I did not expect this to align with upstream so quickly. Thanks @mikedanese for   improving the addon scripts.

**Comment by ingvagabund** [comment]
@danehans Np. I will start complaining when the ansible stop working :).

**Pull request merged**
