### PR TITLE
Make http_proxy configuration work across both RedHat and Debian

### PR DESCRIPTION
**Pull request by pedro-r-marques**
The format for proxy variables is different across RedHat (existing) and Debian based systems (as tested with the apt repository provided by docker).
Make the docker install a separate play, rather than being a dependency so that it is easier to verify.

### CODE REVIEW

**Comment by eparis** [comment]
On debian, how does the $docker_config_dir/docker file get used? Sourced by some startup script? How does it get used if docker is launched with systemd? I'm admittedly a bit baffled that the docker daemon itself would be different and that I would want lower case env vars ever, but I didn't really look...

**Comment by pedro-r-marques** [comment]
@eparis 
snippet of the upstart script used by the docker package:
```
script
        # modify these in /etc/default/$UPSTART_JOB (/etc/default/docker)
        DOCKER=/usr/bin/$UPSTART_JOB
        DOCKER_OPTS=
        if [ -f /etc/default/$UPSTART_JOB ]; then
                . /etc/default/$UPSTART_JOB
        fi
        exec "$DOCKER" daemon $DOCKER_OPTS
end script
```
It sources the config file; while systemd uses EnvironmentFile.

**Comment by eparis** [comment]
@pedro-r-marques thank you so much!  Sadly, I'm still a little dense.

Sourcing this file means that docker is going to launch with an env var `http_proxy=1.2.3.4`. On the non-debian side it will get launched with an env var `HTTP_PROXY=1.2.3.4`.

Does docker pay attention to `http_proxy` instead of `HTTP_PROXY`?

**Comment by pedro-r-marques** [comment]
@eparis lowercase "http_proxy" is the canonical variable that all unix utils tend to use (e.g. curl); the golang  HTTP code for instance respects that. I typically config this var on /etc/environment.
I'm not sure how docker handles capital HTTP_PROXY on systemd systems... i wouldn't be surprised if this ends up being treated the same way as lowercase http_proxy by docker/golang http code.

**Comment by cgwalters** [comment]
```
$ git describe --tags --always
go1.5beta3-1054-g6bf794a
golang/go [git master]
$ git grep HTTP_PROXY
src/net/http/proxy_test.go:     for _, v := range []string{"HTTP_PROXY", "http_proxy", "NO_PROXY", "no_proxy"} {
src/net/http/transport.go:// as directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and
src/net/http/transport.go:// HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions
src/net/http/transport.go:// thereof). HTTPS_PROXY takes precedence over HTTP_PROXY for https
src/net/http/transport.go:              names: []string{"HTTP_PROXY", "http_proxy"},
src/net/http/transport_test.go: env      string // HTTP_PROXY
src/net/http/transport_test.go:         os.Setenv("HTTP_PROXY", tt.env)
```

In other words, yes, golang special cases this.  Agreed that `http_proxy` lowercase is canonical, and we could switch the other parts of the playbook to it.

**Comment by eparis** [comment]
I have seen the light! I guess I'd like to see a switch from HTTP_PROXY to http_proxy across the code base if the old way was the wrong way.

Now enlighten me about the docker as it's own play. You didn't remove the dependency that I see, so if it getting run twice?

**Comment by pedro-r-marques** [comment]
@eparis Having something as an independent play make it easier to test and verify. And while dependencies where supposed to run only once per playbook (according to docs); they run multiple times on my setup. I think the right way to do this is to remove the docker dependencies from the existing plays... but my grasp of ansible is very limited.

**Comment by eparis** [comment]
I'm good/fine making it explicit, but lets pull out the dependencies. So   change the HTTP_PROXY to http_proxy and remove the dependancies from roles/node/meta/main.yml and roles/opencontrail/meta/main.yml and I'll commit.

**Comment by pedro-r-marques** [comment]
@eparis done.

**Pull request merged**
