### PR TITLE
Update service-loadbalance api with upstream

### PR DESCRIPTION
**Pull request by aledbf**

### CODE REVIEW

**Comment by aledbf** [comment]
Closing. Is not required to update the api. I need to use `godep go build` instead of `go build`

**Comment by lavalamp** [comment]
Actually this looks quite reasonable. godep go build probably works for you because the dependency is old.

**Comment by lavalamp** [comment]
So we should probably update the dependency.

**Comment by aledbf** [comment]
@lavalamp is there a rule/directive on how the dependencies can be updated?

**Comment by lavalamp** [comment]
@aledbf I think this is still up to date: https://github.com/kubernetes/kubernetes/blob/b3bce3aa6088345f57c9ae8c6be5802b114a181d/docs/devel/development.md#godep-and-dependency-management

**Comment by bprashanth** [comment]
I think @eparis (thanks!) is doing this https://github.com/kubernetes/contrib/pull/94

**Comment by aledbf** [comment]
@lavalamp sorry for not read the development guide by complete.

Closing. #94 is merged.

**Pull request closed without merging**
