### PR TITLE
Update dnsmasq to 1.3; fix the multiarch build and remove tiny-glibc

### PR DESCRIPTION
**Pull request by luxas**
@thockin @girishkalele @bprashanth

### CODE REVIEW

**Comment by girishkalele** [comment]
@luxas 

Just keeping note of the housekeeping needed from our side - we need to delete the multiple arch glibc images from gcr.io/google_containers reverted here.

Trackback to the reverted changes in https://github.com/kubernetes/contrib/pull/1146

**Comment by luxas** [comment]
@girishkalele Please push ASAP

**Comment by girishkalele** [comment]
@luxas 

I've pushed the dnsmasq:1.3 containers - please test hyperkube for the cross-compiled architectures.

**Comment by luxas** [comment]
@girishkalele Turns out you've only pushed 1.2... or am I missing something?
https://gcr.io/v2/google_containers/kube-dnsmasq-arm64/tags/list

**Comment by girishkalele** [comment]
@luxas 

Hmm, I was sure I had checked out your changes and built/pushed, sorry about that.
I have pulled in your latest branch changes and pushed now, check now.

**Comment by luxas** [comment]
Ah, sorry, one small fix had to be applied yet.
Please push again, thanks.

Verified now that it's working :)

**Comment by luxas** [comment]
@girishkalele Sorry to disturb you, but you have to re-push the `1.3` non-amd64 images, since there was a small bug in the ones you pushed a day ago...
Then we can merge this one

**Comment by girishkalele** [comment]
@luxas 

Pushed from your latest commit point.

**Comment by luxas** [comment]
Thanks, all good then. Let's get this in...

**Pull request merged**
