### PR TITLE
Remove addon resizer code after migrating it to kubernetes/autoscaler

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @Q-Lee @wojtek-t @gmarek @piosz @x13n @MaciekPytel

### CODE REVIEW

**Comment by mwielgus** [comment]
@Q-Lee  ping

**Comment by mwielgus** [comment]
Ping

**Comment by Q-Lee** [comment]
@crassirostris I think you just updated the code in contrib. It might need to go into the new repo instead.

**Comment by mwielgus** [comment]
Last @crassirostris in kubernetes/contrib/addon-resizer is from January. It was included in the code we moved to kubernetes/autoscaler.

**Comment by mwielgus** [comment]
ref: https://github.com/kubernetes/contrib/pull/2345

**Comment by luxas** [comment]
@mwielgus any update on this? Just caused some confusion in #2686

**Pull request merged**
