### PR TITLE
Add a utility for inspecting go import trees

### PR DESCRIPTION
**Pull request by timstclair**
I wrote this small utility for tracking down go dependency issues, and it seems like it could be useful to other people. There are alternatives (such as [godepgraph](https://github.com/kisielk/godepgraph) and [goviz](https://github.com/hirokidaichi/goviz)) but I couldn't find any that computed paths between packages.

/cc @lavalamp

### CODE REVIEW

**Comment by lavalamp** [comment]
Nifty-- will look more when I have more time.

Also note that I added import-boss to the main repo, which can be used to prevent unwanted imports :)

**Comment by nikhiljindal** [comment]
Not sure why you decided to close this but I just used this and it is awesome!
Thanks a lot for writing this :)

**Comment by timstclair** [comment]
I decided to put it in a separate repo. Unfortunately it's been stuck in internal OSS process, but I can try to move it along. Glad you found it useful!

**Comment by eparis** [comment]
How did you use it since github.com/timstclair/godepq doesn't exist?

**Comment by nikhiljindal** [comment]
Downloaded the files in this PR and used them :)
There are 4 files.

**Comment by eparis** [comment]
@nikhiljindal but https://github.com/kubernetes/contrib/pull/494/files#diff-bdaa96558ba7879c62c97a8ac1a69e29R27 ???

**Comment by timstclair** [comment]
You could put the files in `$GOPATH/src/github.com/timstclair/godepq`. I'll ping this PR once the official release is done (poked the issue).

**Comment by nikhiljindal** [comment]
@eparis Yes had to change that line to point to my location of godepq/pkg.

**Comment by timstclair** [comment]
FYI, this was released at https://github.com/google/godepq

**Pull request closed without merging**
