### PR TITLE
Merge queue: look up old test results in case of downtime

### PR DESCRIPTION
**Pull request by lavalamp**
First commit is in #1061

### CODE REVIEW

**Comment by lavalamp** [comment]
I just used this to dump the last 500 runs from each suite here: https://github.com/lavalamp/issue-testing/issues

**Comment by lavalamp** [comment]
Still to do: https://github.com/kubernetes/contrib/issues/1071

**Comment by eparis** [comment]
rebase :-(

**Comment by lavalamp** [comment]
Rebased!

**Comment by lavalamp** [comment]
Interpreting that as an LGTM.

**Pull request merged**
