### PR TITLE
Add my micro-demos to contrib

### PR DESCRIPTION
**Pull request by thockin**
These have been sitting in my own github for too long.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
The verify-boilerplate is failing. Does we require all the verification to pass before merging to the contrib repo?

**Comment by eparis** [comment]
yes. @thockin needs to fix it

**Comment by thockin** [comment]
Pushed with boilerplate

**Comment by caesarxuchao** [comment]
LGTM. I'll push my PRs after this one gets merged.

**Comment by caesarxuchao** [comment]
Manually merging.

**Pull request merged**
