### PR TITLE
Complete rework of submit-queue and submit-queue web page

### PR DESCRIPTION
**Pull request by eparis**
`e2e` and `jenkins` now check the status of the jobs and return the results. They have nothing to do with merging PRs. This the merge logic all live in the submit-queue.

Given the submit-queue now knows why every PR is (or more likely is not) being merged we can display that information. Doing so means throwing out completely the submit-queue web page and starting anew.

### CODE REVIEW

**Comment by eparis** [comment]
@mikedanese @lavalamp @brendandburns 

I think it's a huge improvement. A full run of the munger (which now includes the submit queue) takes about 2000 github API calls.  So we can only run every 30 minutes.

Before we said we wanted to run every 30 minutes, but the rate limit for the submit-queue and munger meant each one only ran about 1 time per hour!

We can see an example of the new web page at http://plnkr.co/edit/M9xY3oM8e9VChnPXJsFt?p=preview

**Comment by lavalamp** [comment]
I read the first few commits somewhat carefully and the rest not so carefully. I guess I'll have to build it and do a dry run...

One thing I'm concerned about is the pr merging munger blocking all the others?

**Comment by eparis** [comment]
The PR merging munger no longer sleep at least, it will never sleep because of Jenkins. If jenkins reports failure it just aborts that commit (all commits), instead of hanging like the old one.

I will still sleep during the second github e2e second run. That might be a deal breaker. I can probably spin that off to a go function, just need to be careful I don't get too many of those hanging around....

But yes, a --dry-run would be great. You also should be able to see the web page that way...

**Comment by lavalamp** [comment]
> I will still sleep during the second github e2e second run. That might be a deal breaker. I can probably spin that off to a go function, just need to be careful I don't get too many of those hanging around....

Yeah, that's what I'm concerned about. You could consider using the work queue from the main repo, or a channel or whatever with a single merging goroutine.

**Comment by eparis** [comment]
now with a (single) _test!

**Comment by eparis** [comment]
@lavalamp ready for review and maybe merge.  could use more tests, but having ANY is a huge improvement   :)

**Comment by lavalamp** [comment]
I will try to review this today.

**Comment by eparis** [comment]
awesome, I've got a bunch more test cases, trying to test every failure case (obviously that's the goal) but the code is good to go.

**Comment by eparis** [comment]
@lavalamp now with lots of tests!

**Comment by lavalamp** [comment]
Nothing stands out except for the merge order. I'll try to find time tomorrow to build this and do a dry run.

**Comment by lavalamp** [comment]
Giving this a dry run. The Dockerfile needs to be fixed for the run.sh change.

**Comment by lavalamp** [comment]
Dockerfile needs the whitelist added, too.

**Comment by lavalamp** [comment]
and committers...

**Comment by lavalamp** [comment]
I have it running in dry run mode. status would be visible at http://104.197.219.155/, but something seems to not work.

**Comment by lavalamp** [comment]
OK, so need to fix status page. The log looks pretty reasonable, I do see the following but that may not be new.

```
W1007 21:52:55.974880       1 blunderbuss.go:132] Couldn't find an owner for: .gitignore
 65 E1007 21:52:55.974942       1 blunderbuss.go:144] No owners found for PR 15199
 66 E1007 21:52:56.492639       1 submit-queue.go:258] PR# 15199 Github CI status is not success
 67 W1007 21:52:57.376825       1 blunderbuss.go:118] Skipping invalid commit for 15194: github.RepositoryCommit{SHA:(*string)(0xc208231b70), Commit:(*github.Commit)(0xc2082e2000), Author:(*github.User)(nil), Committer:(*github.User)(0xc2082ec3c0), Parents:[]github.Commit{gith    ub.Commit{SHA:(*string)(0xc208231ea0), Author:(*github.CommitAuthor)(nil), Committer:(*github.CommitAuthor)(nil), Message:(*string)(nil), Tree:(*github.Tree)(nil), Parents:[]github.Commit(nil), Stats:(*github.CommitStats)(nil), URL:(*string)(0xc208231f20), CommentCount:(*i    nt)(nil)}}, Message:(*string)(nil), HTMLURL:(*string)(0xc208231ca0), Stats:(*github.CommitStats)(0xc208213cc0), Files:[]github.CommitFile{github.CommitFile{SHA:(*string)(0xc208231fc0), Filename:(*string)(0xc208231fd0), Additions:(*int)(0xc208220010), Deletions:(*int)(0xc20    8220040), Changes:(*int)(0xc208220050), Status:(*string)(0xc208231fe0), Patch:(*string)(0xc208220170)}}}
 68 W1007 21:52:57.376972       1 blunderbuss.go:118] Skipping invalid commit for 15194: github.RepositoryCommit{SHA:(*string)(0xc2081fef80), Commit:(*github.Commit)(0xc2082e3380), Author:(*github.User)(nil), Committer:(*github.User)(0xc2082eca00), Parents:[]github.Commit{gith    ub.Commit{SHA:(*string)(0xc2081ff270), Author:(*github.CommitAuthor)(nil), Committer:(*github.CommitAuthor)(nil), Message:(*string)(nil), Tree:(*github.Tree)(nil), Parents:[]github.Commit(nil), Stats:(*github.CommitStats)(nil), URL:(*string)(0xc2081ff280), CommentCount:(*i    nt)(nil)}}, Message:(*string)(nil), HTMLURL:(*string)(0xc2081ff0a0), Stats:(*github.CommitStats)(0xc2081c0920), Files:[]github.CommitFile{github.CommitFile{SHA:(*string)(0xc2081ff2f0), Filename:(*string)(0xc2081ff300), Additions:(*int)(0xc2081ff328), Deletions:(*int)(0xc20    81ff358), Changes:(*int)(0xc2081ff368), Status:(*string)(0xc2081ff310), Patch:(*string)(0xc2081ff3f0)}, github.CommitFile{SHA:(*string)(0xc2081ff400), Filename:(*string)(0xc2081ff410), Additions:(*int)(0xc2081ff448), Deletions:(*int)(0xc2081ff458), Changes:(*int)(0xc2081ff    4f8), Status:(*string)(0xc2081ff430), Patch:(*string)(0xc2081ff590)}}}
 69 E1007 21:52:57.377136       1 blunderbuss.go:144] No owners found for PR 15194
```

Also in the /api page, I sure see a lot of "MERGED!" lines, is that right?

**Comment by lavalamp** [comment]
Oh I think www just needs to be added to the container.

**Comment by lavalamp** [comment]
Can we lose the ' in "PR'S"? ;)

**Comment by lavalamp** [comment]
(on the status page, that is)

**Comment by eparis** [comment]
We can drop the `'`. But I can not make the `s` lower case.  So it will be `PRS`, which, while technically more correct, just looks bad. I'll go either way you want.

**Comment by lavalamp** [comment]
I don't care about the ' that much, but it does make my eyes twitch ;)

**Comment by eparis** [comment]
should I merge commits and make this happen?

**Comment by lavalamp** [comment]
Yeah, why not squash what you want. I'll look at the logs, and try to merge
& start for real later today.

**Comment by lavalamp** [comment]
Building again...

**Comment by lavalamp** [comment]
This is running live now.

**Comment by lavalamp** [comment]
I'll have some makefile/pod/service file changes to push after this PR merges.

**Comment by lavalamp** [comment]
I see a "maybe increase pause time" message in the logs.

**Comment by lavalamp** [comment]
We should add a log message when it makes it through the list so I can tell if it's frozen or waiting for the next cycle...

**Comment by brendandburns** [comment]
The new UI looks great.  Thanks @eparis!

**Comment by lavalamp** [comment]
It seems to actually merge things now when it says it will, so that's good.

**Comment by lavalamp** [comment]
Yeah this looks great now. Thanks so much!

**Comment by lavalamp** [comment]
Can't tell from the logs why https://github.com/kubernetes/kubernetes/pull/14726 is ignored. (not a new problem)

**Comment by lavalamp** [comment]
Oh, I see, it's blocked in that channel. We should maybe report separately what is in that much shorter queue.

**Comment by lavalamp** [comment]
Alright well, it ran overnight. I'm gonna say this is LGTM :)

**Pull request merged**
