### PR TITLE
Added multimaster environment variable

### PR DESCRIPTION
**Pull request by andreamelloncelli**

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @eparis @mikedanese

**Comment by eparis** [comment]
how do you assign two people? is that a new thing?!

**Comment by eparis** [comment]
@redhat-k8s-bot test this

**Comment by mikedanese** [comment]
Yup https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests

**Comment by eparis** [comment]
@redhat-kube-bot test this

**Comment by eparis** [comment]
@rh-kube-bot test this

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by ingvagabund** [comment]
Unfortunately, there is no CI for vagrant. Would be worth to introduce one.

**Pull request merged**
