### PR TITLE
Test result comparator. First commit.

### PR DESCRIPTION
**Pull request by gmarek**
cc @mikedanese @davidopp

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by mikedanese** [comment]
@gmarek compare/ doesn't conatin any source code right now, only Godeps/ and a README. Was this intended? It's breaking CI for #374

**Comment by gmarek** [comment]
My goal was to make review of 'normal' code possible. If you add 3k files in godeps you github don't even list sources...

Can we revert it merge #374 and merge it again?

**Comment by mikedanese** [comment]
I think I can just put a placeholder go file in there for the time being. No worries

**Comment by gmarek** [comment]
Thanks and sorry for that.

**Pull request merged**
