### PR TITLE
Lift code freeze

### PR DESCRIPTION
**Pull request by saad-ali**
Lift code freeze as outlined in https://groups.google.com/forum/#!topic/kubernetes-dev/n-vqlX-HHSM

CC @foxish

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/2081)

### CODE REVIEW

**Comment by foxish** [comment]
Lgtm

**Comment by dims** [comment]
+1 LGTM 👍

**Comment by dims** [comment]
Merging based on ok from @saad-ali

**Comment by saad-ali** [comment]
Verified with @caesarxuchao that his and @smarterclayton's large PRs are stable:

> Yuju sent me a flake that's caused by https://github.com/kubernetes/kubernetes/pull/36673
> https://github.com/kubernetes/kubernetes/issues/37560
> otherwise so far so good
> I don't think it's enough to keep freezing the queue
> We can fix the flake

Restarting merge queue to pick up changes

**Pull request merged**
