### PR TITLE
[Ingress nginx-third-party] Allow using Ingress resources without host specified

### PR DESCRIPTION
**Pull request by codablock**

### CODE REVIEW

**Comment by ekozan** [comment]
it's can be useful for acme request of lets encrypt :) :+1:

**Comment by aledbf** [comment]
@codablock where are you setting `paths = config["_"]`?
If no host is found in the configuration it will return the default page 404 configured behind the mandatory flag `--default-backend-service`

**Comment by aledbf** [comment]
@codablock please check the latest version `gcr.io/google_containers/nginx-ingress-controller:0.61`. It allows Ingress rules without hosts.

**Comment by codablock** [comment]
@aledbf Not sure when I'll get some time to test, but if you believe my PR is obsolete with the new version, I'm happy to close it :)

**Pull request closed without merging**
