### PR TITLE
Fetch list of jobs from prow config.

### PR DESCRIPTION
**Pull request by porridge**
This is a step towards solving https://github.com/kubernetes/contrib/issues/2812
/hold
Needs https://github.com/kubernetes/test-infra/pull/6220 to be merged first.

### CODE REVIEW

**Comment by porridge** [comment]
/cc @shyamjvs 
I plan to add config reloading later.

**Comment by shyamjvs** [comment]
/lgtm

Though the presubmit failed with:

```
# k8s.io/test-infra/prow/github
Godeps/_workspace/src/k8s.io/test-infra/prow/github/client.go:52: undefined: time.Until
```

Could you fix it?

**Comment by porridge** [comment]
On Wed, Jan 10, 2018 at 7:26 PM, Shyam JVS <notifications@github.com> wrote:

> Though the presubmit failed with:
>
> # k8s.io/test-infra/prow/github
> Godeps/_workspace/src/k8s.io/test-infra/prow/github/client.go:52 <http://k8s.io/test-infra/prow/githubGodeps/_workspace/src/k8s.io/test-infra/prow/github/client.go:52>: undefined: time.Until
>
> Could you fix it?
>

I think this means we need to change the golang version in the travis
config, but I don't  know how to do it. Asked on slack, got no replies so
far.

**Comment by shyamjvs** [comment]
There should be a travis.yaml (I guess it's hidden) file at the root of this repo. You need to change it there.

**Comment by shyamjvs** [comment]
Here specifically - https://github.com/kubernetes/contrib/blob/master/.travis.yml#L10
But need to watch out for any other dependencies on the older go.

**Comment by porridge** [comment]
Finally it works, PTAL @shyamjvs 
/approve

**Comment by foxish** [comment]
Contrib has turned into a collection of things falling into disuse, so, separating perfdash out might be a good thing to consider.
It looks like it's actively used and maintained? We should try and find a new home for it then - maybe test-infra? @BenTheElder @krzyzacy @shyamjvs @porridge

**Comment by porridge** [comment]
I agree, but do you think it should block this change?

**Comment by foxish** [comment]
/approve
For the godeps changes.
Not a blocker for this particular PR - but would be good to file an issue if there's an intent to move this out at some point in the future.

**Comment by porridge** [comment]
The tags in prow config are checked in.
/hold cancel

**Pull request merged**
