### PR TITLE
Fix fluentd-gcp image

### PR DESCRIPTION
**Pull request by crassirostris**
To keep fluentd 0.12

### CODE REVIEW

**Comment by crassirostris** [comment]
@igorpeshansky Could you please take a look?

**Comment by igorpeshansky** [comment]
@crassirostris Looks fine, but I'm curious as to what didn't work with fluentd 0.14... Are you running into https://github.com/fluent/fluentd/issues/1555, or are there other issues?

**Comment by crassirostris** [comment]
@igorpeshansky `@type` and a change in one of the filter plugins broke our config and this patch is required for a cherry-pick into an old release

**Comment by igorpeshansky** [comment]
Ah, makes sense, thanks. LGTM, then. :shipit:

**Comment by crassirostris** [comment]
Thanks!

**Comment by crassirostris** [comment]
@igorpeshansky BTW, version with 0.14 has a larger memory footprint. Where 0.12 works without any issues, 0.14 gets OOM-killed

**Pull request merged**
