### PR TITLE
Revert "Revert "Block PR merge on kubemark presubmit and add kubemark-500 to blocking suites.""

### PR DESCRIPTION
**Pull request by apelisse**
Reverts kubernetes/contrib#1868

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1869)

### CODE REVIEW

**Comment by spxtr** [comment]
Should be good this time.

**Comment by wojtek-t** [comment]
LGTM - thanks!

@apelisse - will you push it this time too? (sorry for problems the previous time).

**Comment by apelisse** [comment]
Yeah I'll do it now and monitor closely

Thanks everyone for quickly addressing the problem,
Antoine

**Comment by apelisse** [comment]
Deployed and seems to be working fine now,

**Comment by eparis** [comment]
what went wrong last time?

**Comment by eparis** [comment]
No response? No explanation what went wrong last time? Why do we still have things like this?

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/27206/kubernetes-pull-build-test-kubemark-e2e-gce/3220/

**Comment by spxtr** [comment]
https://github.com/kubernetes/test-infra/issues/791

The kubemark presubmit was set to be blocking, but it wasn't triggered by `k8s-bot test this` and so the "ok to test" munger kept trying to rerun it.

**Pull request merged**
