### PR TITLE
[ubuntu-slim]: Remove locales

### PR DESCRIPTION
**Pull request by aledbf**
This update reduces the size of the image in 12MB

```
gcr.io/google_containers/ubuntu-slim  0.3   6e333e89d38c   9 hours ago 47.33 MB
gcr.io/google_containers/ubuntu-slim  0.2   010be51edff2   5 weeks ago 59.37 MB
```

### CODE REVIEW

**Comment by ingvagabund** [comment]
@aledbf do you have a CI or a bunch of tests that could be run on the image?

**Comment by aledbf** [comment]
@ingvagabund I don't have tests for this, the "checks" are from the places where is being used (nginx-slim, keepalived-vip, etc.)

**Comment by aledbf** [comment]
@bprashanth this one before the nginx update

**Comment by bprashanth** [comment]
LGTM

**Pull request merged**
