### PR TITLE
Switch to new batch URL in submit queue.

### PR DESCRIPTION
**Pull request by spxtr**

### CODE REVIEW

**Comment by rmmh** [comment]
This isn't equivalent. Previously, it would link to just the currently running batch. This shows all batch results.

**Comment by rmmh** [comment]
If you're going to make this change, you should remove the newly dead code that figured out what to link to.

**Comment by rmmh** [comment]
And probably put the link in "CURRENTLY RUNNING BATCH" instead of the specific PRs-- those PRs could then become Github links.

**Comment by spxtr** [comment]
Removed the dead code. I'm not sure that it's right to link anywhere else.

**Pull request merged**
