### PR TITLE
Updated the docs for custom configuration of nginx ingress controller…

### PR DESCRIPTION
**Pull request by christianhuening**
… to reflect changes in the argument name for configmap and "body-size" in the upcoming 0.9.0 release

### CODE REVIEW

**Comment by christianhuening** [comment]
I signed it!

**Comment by christianhuening** [comment]
I signed it!

**Comment by aledbf** [comment]
@christianhuening please do not open PRs to change Ingress code/docs in this repository.
The Ingress development is now located in https://github.com/kubernetes/ingress

**Comment by christianhuening** [comment]
@aledbf ok

**Pull request closed without merging**
