### PR TITLE
Push a new submit queue.

### PR DESCRIPTION
**Pull request by brendandburns**
@thockin @quinton-hoole @ixdy 

Update the submit queue, and add more jenkins-jobs to monitor.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Two of those Jenkins jobs are not currently green.  I assume that nothing will auto-merge until they're fixed?  Is this by design?

**Comment by quinton-hoole** [comment]
@brendandburns  ^^

**Comment by brendandburns** [comment]
Yep, that's by design...

**Comment by eparis** [comment]
closing just merged something else called 0.4.   crap.

**Comment by ixdy** [comment]
we lost the changes to `--jenkins-jobs` then...

**Pull request closed without merging**
