### PR TITLE
Do not counts Godeps changes in the sizer

### PR DESCRIPTION
**Pull request by eparis**
Github hides these in review, we typically don't review them closely, and hopefully the godep checker will tell us if someone isn't pushing what they say they are...

### CODE REVIEW

**Comment by eparis** [comment]
@thockin I can break this into 2 parts, one with all my unrelated changes and one with exactly those directed at making the size labeler ignore Godeps, if you like...   Should be easy to review per commit...

**Comment by derekwaynecarr** [comment]
@eparis - I need to think of other useful things I can randomly ask for that you just go ahead and do!

**Comment by eparis** [comment]
@derekwaynecarr all my PRs got labeled XXL (I also wrote a follow on PR to ignore autogenerated files like docs, deep-copy, conversions, and swagger). But waiting for this to merge first.

**Comment by eparis** [comment]
needs rebase after #37

**Comment by thockin** [comment]
I like it

**Comment by thockin** [comment]
LGTM

@brendandburns does this get auto-deployed or do we have to do something?

**Comment by thockin** [comment]
@k8s-oncall

I don't think this will get merge-botted, so please merge when you're comfortable with the answer from @brendandburns

**Pull request merged**
