### PR TITLE
[ansible] support installation via system containers

### PR DESCRIPTION
**Pull request by jasonbrooks**
This PR provides the option of installing flannel, etcd, the and the kube master and node components using system containers.

@ingvagabund

### CODE REVIEW

**Comment by ingvagabund** [comment]
@jasonbrooks the verifier does not like header of the `oc_atomic_container.py`. It needs to conform to `https://github.com/kubernetes/contrib/blob/master/hack/boilerplate/boilerplate.py.txt`. Can you update `oc_atomic_container.py`?

 Otherwise, it looks good.

**Comment by jasonbrooks** [comment]
@ashcrow @giuseppe I lifted the atomic container module [directly from](https://github.com/openshift/openshift-ansible/blob/master/roles/lib_openshift/library/oc_atomic_container.py) openshift ansible, is it all right if I change the header to match: https://github.com/kubernetes/contrib/blob/master/hack/boilerplate/boilerplate.py.txt

**Comment by ashcrow** [comment]
Travis error:

```
Skipping hack/../hack/verify-all.sh

Boilerplate header is wrong for: /home/travis/gopath/src/k8s.io/contrib/ansible/library/oc_atomic_container.py

!!! 'golint' problems: 

/home/travis/gopath/src/k8s.io/contrib/kubeform/pkg/provider/provider.go:428:2: redundant if ...; err != nil check, just return error instead.
```

**Comment by ashcrow** [comment]
@jasonbrooks I have no issue with that as it's Apache License header ➡️  Apache License header. In this case it will no longer be generated but copied in.

**Comment by ingvagabund** [comment]
The `golint` issue fixed here: https://github.com/kubernetes/contrib/pull/2767

**Comment by ingvagabund** [comment]
@jasonbrooks once you rebase and update the header, the CI should pass. Just fixed the golint stuff.

**Pull request merged**
