### PR TITLE
API Server opts use | for nil check

### PR DESCRIPTION
**Pull request by jayunit100**
@eparis I think this is what you had in mind for this? It also fixes the other screw up i made with the pyhton style `if nil` check on apiserver

### CODE REVIEW

**Comment by jayunit100** [comment]
NOT TESTED.  I'll test as soon as you confirm that this is the way you wanted the args to look.

**Comment by jayunit100** [comment]
fixes #329

**Comment by eparis** [comment]
I like it....

**Comment by jayunit100** [comment]
k ran a quick test  looks like its working to me

**Pull request merged**
