### PR TITLE
Ansible: fix typo

### PR DESCRIPTION
**Pull request by gouyang**
Signed-off-by: Guohua Ouyang <gouyang@redhat.com>

### CODE REVIEW

**Comment by eparis** [comment]
I'm shocked this ever worked, but i'm 99% sure it did/does.  Did you have a problem that this fixes?

**Comment by gouyang** [comment]
I didn't see any problem so far, it seems once "--service-account-private-key-file" is added in /etc/kubernetes/controller-manager, it will create the service account "default" automatically.

It should be a bug of k8s, right?

**Comment by eparis** [comment]
So I think this is correct, but maybe the flag names are terrible?  The controller manager gets the `private-key-file` and the apiserver gets the `key-file`. Which is really the public half of the private key. This is what we are doing...

**Comment by gouyang** [comment]
@eparis are you meaning using "server.crt" is correct?

**Comment by eparis** [comment]
Yes, I think so...

**Pull request closed without merging**
