### PR TITLE
Comparator for prometheus metrics.

### PR DESCRIPTION
**Pull request by gmarek**
cc @wojtek-t

### CODE REVIEW

**Comment by mwielgus** [comment]
LGTM

**Comment by mwielgus** [comment]
Actually half-LGTM, please attach test code coverage report for the files.

**Comment by gmarek** [comment]
```
ok  	k8s.io/contrib/compare/src	0.732s	coverage: 61.2% of statements
```

Note that we don't test print stmts.

**Comment by gmarek** [comment]
```
k8s.io/contrib/compare/src/compare-metrics.go:51:	Len				100.0%
k8s.io/contrib/compare/src/compare-metrics.go:52:	Swap				100.0%
k8s.io/contrib/compare/src/compare-metrics.go:53:	Less				100.0%
k8s.io/contrib/compare/src/compare-metrics.go:69:	PrintToStdout			0.0%
k8s.io/contrib/compare/src/compare-metrics.go:90:	uniformizeMetric		93.3%
k8s.io/contrib/compare/src/compare-metrics.go:115:	flattenSamples			88.9%
k8s.io/contrib/compare/src/compare-metrics.go:130:	computeKubeletAggregates	100.0%
k8s.io/contrib/compare/src/compare-metrics.go:148:	isSimpleMetricSimilarEnough	100.0%
k8s.io/contrib/compare/src/compare-metrics.go:160:	isKubeletMetricSimilarEnough	100.0%
k8s.io/contrib/compare/src/compare-metrics.go:178:	compareSamples			75.0%
k8s.io/contrib/compare/src/compare-metrics.go:211:	compareKubeletMetrics		71.4%
k8s.io/contrib/compare/src/compare-metrics.go:247:	compareSimpleMetrics		75.0%
k8s.io/contrib/compare/src/compare-metrics.go:264:	CompareMetrics			77.8%
```

**Comment by mwielgus** [comment]
LGTM

**Pull request merged**
