### PR TITLE
Munger: Don't lock while building users

### PR DESCRIPTION
**Pull request by justinsb**
If we don't have a github token, we never build the users, and thus we
can't develop the UI etc.

### CODE REVIEW

**Comment by justinsb** [comment]
I think this is important as otherwise development is hard, and I end up making mistakes like https://github.com/kubernetes/kubernetes/issues/22136

**Comment by eparis** [comment]
hack/verify-go-lint.sh failed...

**Comment by eparis** [comment]
and now submit-queue_test.go doesn't build...

**Comment by eparis** [comment]
Without any token, what does this enable? It gets the web site up?

**Comment by justinsb** [comment]
Exactly... All in service of bringing up a dev environment with no token.
Going to revisit all of these this afternoon..

**Comment by eparis** [comment]
May be superceeded by #1108

**Pull request closed without merging**
