### PR TITLE
add internal load balancer for GKE

### PR DESCRIPTION
**Pull request by rimusz**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/572)

### CODE REVIEW

**Comment by bprashanth** [comment]
Will try to do a first pass by monday

**Comment by eparis** [comment]
@bprashanth i think this one has been waiting on you for a bit.

**Comment by bprashanth** [comment]
Serviceloadbalancer will already run in a pod in your kubecluster and watch the master for endpoint changes (https://github.com/kubernetes/contrib/tree/master/service-loadbalancer). If the vm dies, it gets rescheduled. Can you clarify when one would prefer this setup over just a  pod in the cluster?

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by rimusz** [comment]
I signed it

**Comment by grodrigues3** [comment]
[APPROVALNOTIFIER] The Following OWNERS Files Need Approval:

- **/**

We suggest the following people:
cc @bprashanth 
 You can indicate your approval by writing `/approve` in a comment
 You can cancel your approval by writing `/approve cancel`in a comment

**Pull request closed without merging**
