### PR TITLE
Update kubectl to 1.3.6

### PR DESCRIPTION
**Pull request by gssbzn**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1713)

### CODE REVIEW

**Comment by gssbzn** [comment]
I signed it!

**Comment by foxish** [comment]
@emaildanwilson This PR needs your attention for review. The autoassigner is unable to assign reviews to you as you are not part of the kubernetes organization. I have sent you an invite.

**Comment by gssbzn** [comment]
@emaildanwilson it would be interesting to see those changes.
We were working close with ReactiveOps an so we move to their scripts (https://github.com/reactiveops/k8s-scripts)
I'm no longer working on that particular project but if I start using k8s again may need to do a quick update on best practices, k8s is changing a lot

**Comment by gssbzn** [comment]
It would be interesting to see that approach
I'm no longer working with k8s but we were close with ReactiveOps so we were using their scripts https://github.com/reactiveops/k8s-scripts

**Pull request closed without merging**
