### PR TITLE
Fixes #2234

### LINKED ISSUE #2234: [Election] In certain cases example code does not see changes
In a 3-pod election, when deleting leader, one of two other nodes becomes a leader. But the 3rd node, which was not a leader and did not become a leader, will still return old leader information:
```
(.venv) vagrant@node1:~/nextgen$ kubectl get pods -o wide
NAME                    READY     STATUS    RESTARTS   AGE       IP               NODE
etcd-4126467301-5frzt   1/3       Running   0          18s       10.233.68.234    node3
etcd-4126467301-fht8r   1/3       Running   0          18s       10.233.72.168    node2
etcd-4126467301-g3k5n   1/3       Running   0          18s       10.233.111.183   node1
(.venv) vagrant@node1:~/nextgen$ for pod in `kubectl get pods -o template --template='{{ range .items }}{{.metadata.name}} {{end}}'`; do kubectl exec -ti $pod -c etcd curl localhost:4040; done
{"name":"10.233.111.183"}{"name":"10.233.111.183"}{"name":"10.233.111.183"}
```

After delete:
```
vagrant@node1:~/nextgen$ kubectl delete pods etcd-4126467301-g3k5n
(.venv) vagrant@node1:~/nextgen$ for pod in `kubectl get pods -o template --template='{{ range .items }}{{.metadata.name}} {{end}}'`; do kubectl exec -ti $pod -c etcd curl localhost:4040; done
{"name":"10.233.111.183"}{"name":"10.233.72.168"}{"name":"10.233.72.168"}
```

### PR DESCRIPTION
**Pull request by amnk**

### CODE REVIEW

**Comment by amnk** [comment]
I signed it!

**Comment by amnk** [comment]
I signed it!

**Comment by amnk** [comment]
@brendandburns, could you please review it or let me know if I did something stupid? )

**Comment by amnk** [comment]
@mikedanese, can you please review this commit?

**Comment by brendandburns** [comment]
/lgtm

but needs rebase.

**Comment by amnk** [comment]
@brendandburns rebased, thanks!

**Comment by mikedanese** [comment]
This was already fixed. The diff is empty.

**Comment by amnk** [comment]
Oh yes, 20 days ago:
https://github.com/kubernetes/contrib/commit/980a92075d06b4e41da618a93bbe8402cf0dea91

this PR took to much time to get somebody's attention :(

thanks @mikedanese , I'll abandon it.

**Pull request closed without merging**
