### PR TITLE
[nginx-ingress-controller]: Add function helpers to nginx template

### LINKED ISSUE #1695: [Ingress] How to use regexp in nginx.tmpl?
Hi,

According to our application requirement, I need to add some lua code block in nginx.tmpl. To limit the impact of these lua code, I want to achieve some limitation: 
1. If the upstream name matches some specific string, add balancer_by_lua_block
2. If the location patch matches some specific string, add rewrite_by_lua_block and header_filter_by_lua_block.

How can I implement these 2 limitations in nginx.tmpl?

Thanks

### PR DESCRIPTION
**Pull request by aledbf**
fixes #1695

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1711)

### CODE REVIEW

**Comment by aledbf** [comment]
@bprashanth ping

**Comment by bprashanth** [comment]
For my own edification, can you elaboration how one leverages this, do we need a custom template (haven't parsed the entire issue)?

**Comment by aledbf** [comment]
>  do we need a custom template (haven't parsed the entire issue)?

Yes. This PR just add new helpers to the template to avoid compiling a custom controller like in #1695

**Review by tjliupeng — APPROVED** [review]
That's great to enable extra string operation in the template file.

**Comment by aledbf** [comment]
@bprashanth ping

**Comment by test-foxish** [comment]
recomputing cla status...

**Review by tjliupeng — APPROVED** [review]
LGTM.

**Comment by bprashanth** [comment]
LGTM, please document an example of how one uses it so the wider community can avail of the new functions (ok to do this in a follow up pr)

**Pull request merged**
