### PR TITLE
set live-restore only for docker => 1.12

### PR DESCRIPTION
**Pull request by ingvagabund**
Fix the cluster deployment for older version of docker.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/2042)

### CODE REVIEW

**Comment by ingvagabund** [comment]
still testing :)

**Comment by ingvagabund** [comment]
@akantak can you test the patch with your deployment?

@eparis I have just tested the deployment on Fedora, working as expected

**Comment by akantak** [comment]
@ingvagabund 

TASK: [docker | Detected version] *********************************************
fatal: [localhost] => Failed to template {{ docker_version.stdout | regex_replace('(\r\n)','') }}: Failed to template docker version -f '{{ .Client.Version }}' 2>/dev/null || exit 0: template error while templating string: unexpected '.'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/deploy-cluster.retry

localhost                  : ok=47   changed=8    unreachable=1    failed=0

make: *** [deploy_k8s_cluster] Error 3

**Comment by ingvagabund** [comment]
@akantak can you rerun the deployment again with the latest commit? It seems to me you have run the deployment with outdated commit. ``docker version -f '{{ .Client.Version }}'`` has been replaced with the correct form of the braces.

**Comment by akantak** [comment]
I was using commit with hash 3c098d7bd9124db5d8f88163e7e77b704dc2632d
maybe docker version looks different in earlier versions?

Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by ingvagabund** [comment]
Just run it on CentOS cluster. I am deploying the cluster via Vagrant. The same docker as you have:

```
$ docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

```
$ docker version -f {{.Client.Version}}
1.10.3
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by akantak** [comment]
so it is exactly the same. Did you try to run ansible?

**Comment by ingvagabund** [comment]
Yes I did, I picked the output from deployed cluster.

**Comment by ingvagabund** [comment]
@akantak looks like you are running the ansible on your localhost on CentOS. What is your ansible version? (rpm -q ansible)

**Comment by akantak** [comment]
I was installing ansible1.9

**Comment by akantak** [comment]
when I used newest possible ansible (ansible-2.2.0.0-3.el7.noarch) this docker version passed, but there was another issue:
```
TASK [master : Extend the list of kube master binaries with kubelet] ***********
skipping: [localhost]

TASK [master : Download Kubernetes binaries] ***********************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'kube_binaries' is undefined"}

RUNNING HANDLER [master : restart daemons] *************************************
        to retry, use: --limit @/home/centos/contrib/ansible/playbooks/deploy-cluster.retry

PLAY RECAP *********************************************************************
localhost                  : ok=110  changed=45   unreachable=0    failed=1
```
but ansible 1.9 is suggested [here](https://github.com/kubernetes/contrib/tree/master/ansible#before-starting)

**Comment by ingvagabund** [comment]
The new issue is exactly https://github.com/kubernetes/contrib/issues/2026

@akantak thanks, now it make sense.

**Comment by akantak** [comment]
You are right, but only in case when I used newest ansible. 
There's still issue connected with centos and ansible1.9 in my case, but it is probably something that was revealed by your fix.

**Comment by ingvagabund** [comment]
Deploying with ``ansible-1.9.4-2.fc24.noarch``. The error with braces reproduces. Seems there is no simple construct to express double braces.

**Comment by akantak** [comment]
there was similar issue:
https://github.com/ansible/ansible-modules-core/issues/1641

**Comment by ingvagabund** [comment]
@akantak now it should be fine. Tested with both ansible 1.9 and 2.2.*. Can you run the last round?

**Comment by akantak** [comment]
Beautiful, worked fine :) thank you

**Comment by ingvagabund** [comment]
Thanks for your patience :)

**Pull request merged**
