### PR TITLE
Add support for f5 BIG-IP

### PR DESCRIPTION
**Pull request by stevesloka**
This is still a little bit wip against #12. I wrote the infoblox piece a while back and just realized that I need to implement the response bodies to get the IP's to pass to f5. So I'll look at that and get it cleaned up soon. 

My question for everyone else is how are you managing IP's? At my company we're using Infoblox to implement DNS & IP addresses, but want to make sure it works for everyone. 

//cc @bprashanth @chrissnell @vipulsabhaya

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1030)

### CODE REVIEW

**Comment by stevesloka** [comment]
I think all my code should be working now. Do you think I should pull the Infoblox stuff out into it's own container? I chatted with @brendandburns a while back but not sure the thoughts now. I had it all together to make life easier in dev, but it breaks the model a bit of doing just one thing. 

I should also update the readme.

**Comment by aledbf** [comment]
@stevesloka can you remove the Infoblox code from the F5 integration and maybe use a sidecar for that?
Have you seen `https://github.com/scottdware/go-bigip`? (to simplify the code)

**Comment by stevesloka** [comment]
@aledbf yup I can do that. Let me get that worked out, will push some changes up soon. Thanks!

**Comment by test-foxish** [comment]
recomputing cla status...

**Comment by stevesloka** [comment]
I signed it

**Comment by grodrigues3** [comment]
[APPROVALNOTIFIER] The Following OWNERS Files Need Approval:

- **service-loadbalancer**

We suggest the following people:
cc @bprashanth 
 You can indicate your approval by writing `/approve` in a comment
 You can cancel your approval by writing `/approve cancel`in a comment

**Comment by cyberious** [comment]
Any update on this?

**Comment by myf5** [comment]
@stevesloka Is this done? Any new update?

**Comment by chrissnell** [comment]
I don't want to dump on @stevesloka's project but we were also desperately looking for a way to get automatic VIPs for ingress on our baremetal environment with F5s.  We ended up coming up with an alternate solution that's much more flexible:

1. Set up [Traefik](https://traefik.io/) running within your K8S cluster, configured to use the Kubernetes API for service discovery.  If you want HTTPS, get a wildcard cert and have Traefik use this
2.  Use a VIP on your F5s to proxy TCP to ports 80 and 443 to Traefik's NodePort
3.  Set up wildcard DNS to point to the VIP from step 2.  You could call it, for example, `*.svc.mycompany.com`.

With this solution, you get Traefik's auto-discovery of Kube services and auto-provisioning of their VIPs.  The F5s just act as load balancing TCP proxies (you could also use Linux or *BSD boxes for this.

**Comment by chen23** [comment]
@myf5 @stevesloka @chrissnell 
Another option is to use the F5 Container Connector.  This provides a controller (container) that runs in Kubernetes that can monitor for new services and create/update pool/vips on an F5 BIG-IP.  It also has support for Ingress routes as well.  It can route traffic directly to pods under appropriate network conditions (ability to route to the pod).

- https://github.com/F5Networks/k8s-bigip-ctlr 
- http://clouddocs.f5.com/containers/latest/kubernetes
- http://clouddocs.f5.com/containers/v1/kubernetes/kctlr-modes.html#kctlr-modes

**Comment by stevesloka** [comment]
Thanks @chen23! I stopped work a while back on this when the F5 folks had some better offerings as well as my internal needs changed (e.g. I moved my workloads off-prem to the cloud).

**Pull request closed without merging**
