### PR TITLE
unit tests take over an hour

### PR DESCRIPTION
**Pull request by lavalamp**
Submit queue just gave up on a good PR because of this.

### CODE REVIEW

**Comment by lavalamp** [comment]
Self-merging.

**Comment by lavalamp** [comment]
I will try to push this tonight, it got hit again.

**Comment by lavalamp** [comment]
should be pushed now.

**Comment by eparis** [comment]
@ixdy how do we fix the real problem here?

**Comment by eparis** [comment]
I should say, I found the PR daniel filed above...

**Pull request merged**
