### PR TITLE
Add ihmccreery and spxtr to blunderbuss config

### PR DESCRIPTION
**Pull request by ixdy**
@ihmccreery @spxtr

### CODE REVIEW

**Comment by ihmccreery** [comment]
LGTM; not sure why Travis is sad.

**Comment by ixdy** [comment]
The Go 1.5.1 build seems flaky/broken. Also, we should probably update that from 1.5.1 to 1.5.3.

**Comment by ixdy** [comment]
#391 for Travis

**Comment by spxtr** [comment]
LGTM

**Pull request merged**
