### PR TITLE
Add ci-cri-containerd-node-e2e-benchmark to node-perf-dash.

### PR DESCRIPTION
**Pull request by Random-Liu**
Add ci-cri-containerd-node-e2e-benchmark to node performance dashboard.

### CODE REVIEW

**Comment by foxish** [comment]
As per offline discussion, Lantao to file an issue to move this to
test-infra, akin to perfdash.

**Comment by Random-Liu** [comment]
Issue filed. https://github.com/kubernetes/kubernetes/issues/58891 :)

**Comment by Random-Liu** [comment]
The CI is broken. #2836

**Pull request merged**
