### PR TITLE
Ansible fixes

### PR DESCRIPTION
**Pull request by cgwalters**
See commits for detail.  /cc @pedro-r-marques for regressions.

### CODE REVIEW

**Comment by cgwalters** [comment]
@googlebot I'm a Red Hat employee.

**Comment by cgwalters** [comment]
This time with `@redhat.com` as author.

**Comment by cgwalters** [comment]
I signed it!

**Comment by eparis** [comment]
@googlebot he signed it.

**Comment by jayunit100** [comment]
Looks like maybe we should merge this..  I tested it, it seems to be a step forward ?  But not sure what opencontrail is really supposed to do.  At least this patch makes it **optional**...

- I  think right now as-is, opencontrail is installed no matter what, 
- Additionally, it seems like it might be a little buggy... 
-  this patch fixed this for me... now opencontrail isnt complainaing,  I think because the `:when` clause disables it ...  

In any case, the patch helped me

**Comment by eparis** [comment]
commits 1 and 2 I'm ready to merge now. commit #3 I'm going to wait for @pedro-r-marques 

What actual problem did you get @cgwalters ?

**Comment by pedro-r-marques** [comment]
@eparis @cgwalters Enabling kubelet on the master should have been conditional.
Can we have a var 'kube_master_run_kubelet' that would be set in order to enable this  ?

**Comment by pedro-r-marques** [comment]
Please see #184 as a proposal to address the issue as whether to run kubelet on the master node.

**Comment by cgwalters** [comment]
I pushed an alternative approach :arrow_up:  which just does it by default iff OpenContrail, replacing the last patch.

**Comment by eparis** [comment]
It's better, it's what @pedro-r-marques but I won't merge either until I hear what was actually wrong with running the kublet on the master. I actually LIKE having the kubelet on the master. It means you can use static pod manifests consistently...

**Comment by cgwalters** [comment]
Okay, I created another fresh environment without the tip commit here, and here's what I ran into:

```
TASK: [master | Enable kubelet] *********************************************** 
failed: [walters-os1priv-rhelah-kubetest-master] => {"failed": true}
msg: Error when trying to enable kubelet: rc=1 Failed to execute operation: Access denied


FATAL: all hosts have already failed -- aborting
```

It's simple, we're not installing the `kubernetes-kubelet` package.

**Comment by cgwalters** [comment]
I actually didn't know what static pods are, I found https://github.com/kubernetes/kubernetes/blob/master/docs/admin/static-pods.md  - this one is deprecated, is there another one?

**Comment by pedro-r-marques** [comment]
Colin,
The kubelet is being installed in the build from source option, but not the install from .rpms option.

  Pedro.

On Oct 19, 2015, at 2:53 PM, Colin Walters <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, I created another fresh environment without the tip commit here, and here's what I ran into:

TASK: [master | Enable kubelet] ***********************************************
failed: [walters-os1priv-rhelah-kubetest-master] => {"failed": true}
msg: Error when trying to enable kubelet: rc=1 Failed to execute operation: Access denied


FATAL: all hosts have already failed -- aborting


It's simple, we're not installing the kubernetes-kubelet package.

**Comment by eparis** [comment]
@cgwalters yes, that's the one. and while it's deprecated, its not going anywhere until the daemon controller is a first class citizen. So it's all we have.

**Comment by eparis** [comment]
@pedro-r-marques I'm going to merge this PR, and close yours. Will you please send another PR which installs kubernetes-node on the master if contrail is enabled?

**Comment by cgwalters** [comment]
I was working on that this morning - basically merging the master/node package bits into the `kubernetes/` role.  But ran into flannel failing, debugging that now.

**Comment by cgwalters** [comment]
@eparis Isn't that exactly what https://github.com/kubernetes/contrib/commit/401711b6afe75c269ba174435865e4968c61bbe5 that you merged does?

Anyways I followed up with https://github.com/kubernetes/contrib/pull/188 and after that, we can revert that commit.

**Pull request merged**
