### PR TITLE
Change namespace.yaml path to /opt

### LINKED ISSUE #944: [ansible] namespace kube-system is not created
namespace `kube-system` is not created because kube-addons.sh is expecting to find it at /opt/namespace.yaml.

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/kube-addons.sh#L68

### PR DESCRIPTION
**Pull request by gouyang**
Fixes #944

### CODE REVIEW

**Comment by eparis** [comment]
I think the script looking in `/opt` needs to be fixed to look somewhere else. In atomic you can't even create `/opt`...

**Comment by gouyang** [comment]
There is /opt exists on Atomic host.

```
$ ls -lsh / | grep opt
   0 lrwxrwxrwx.   1 root root    7 May  4 23:44 opt -> var/opt
```

It need to adjust on one side. Actually I don't see why it changes the path.

**Comment by gouyang** [comment]
Open kubernetes/kubernetes#25440 in kubernetes/kubernetes

**Comment by mikedanese** [comment]
/opt is a path inside the kube-addon-manager container.

**Comment by gouyang** [comment]
@mikedanese browsing files inhttps://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/, /etc/kubernetes and /etc/kubernetes/addons is used there. is it /opt must be used for namespace.yaml?

**Comment by jasonbrooks** [comment]
#797 is how I'm fixing this issue in my fork of the scripts.

**Pull request closed without merging**
