### PR TITLE
Wild guess at inability to find LGTM

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by lavalamp** [comment]
I did a small amount of debugging-- I can say that the Etag github returns doesn't change if you e.g. delete a comment from the PR.

**Comment by eparis** [comment]
Were you looking at the events api?  I doesn't show comments at all...  Labels, assignments, subscriptions...

**Comment by lavalamp** [comment]
I was running this in --dry-run mode and printing out the HTTP req/resp.

**Comment by lavalamp** [comment]
AFAICT, you still get a cache hit if you change something like e.g. deleting a comment.

**Comment by eparis** [comment]
On which API endpoint is my question. The etag is changing when I add/remove the label from this PR at https://api.github.com/repos/kubernetes/contrib/issues/996/events

**Comment by lavalamp** [comment]
Oh, it's the issues/PR#/events api.

**Comment by lavalamp** [comment]
hm, maybe it's only particular PRs. I'm no longer confident this change will help...

**Comment by eparis** [comment]
oh, i have little confidence this PR will help. But it'll definitely give us some more debugging info.

**Comment by lavalamp** [comment]
OK, yeah, adding/removing a label causes the Etag to change, but deleting a comment does not, and I observe a false cache hit in that case.

**Pull request merged**
