### PR TITLE
make some kubelet args configurable

### LINKED ISSUE #1788: [ansible] add variable to configure KUBELET_ARGS in kubelet.j2 template of node role
Currently it's not possible to provide custom options for `KUBELET_ARGS` in `/etc/kubernetes/kubelet` file. So for example, if I want my pods to run with host network (`KUBELET_ARGS="--host-network-sources=*"`), I have to manually edit `/etc/kubernetes/kubelet` file on every node.

### PR DESCRIPTION
**Pull request by ingvagabund**
Fixes: #1788

As long as user specified args does not conflict with automatically specified.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1812)

### CODE REVIEW

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by ingvagabund** [comment]
I signed it!

**Comment by ingvagabund** [comment]
Running locally via Vagrant on Fedora box. Tested both use cases when the ``kubelet_args`` is empty and set to ``--host-network-sources=*``. Cluster is deployed, nodes are registered.

**Comment by cheyang** [comment]
Hi, @ingvagabund. I also have an proposed change for it. 
https://github.com/cheyang/contrib/commit/662e124d7c7fe71d32544ab7171bb8b0b7f7ca8f

Then we can define kubelet_options as below. 

```
kubelet_options: 
  - "--pod-infra-container-image={{kube_regitry}}/google_containers/pause:2.0"
  - "--max-pods=3"
```

There are two benefits:
1.  It can handle long kubelet options elegant
2. It can avoid the space in the end of kubelet command if kubelet_args is empty.  

If you feel we can leverage my change, I can send merge request. If not, it's also fine.

**Comment by ingvagabund** [comment]
@cheyang it crossed my mind as well. Just did not have much time to extend the idea. I like yours, it is elegant. Be my guest :) I will review your PR.

**Comment by cheyang** [comment]
Thank you! @ingvagabund , I've submitted the changes, please review it.

**Review by cheyang — APPROVED** [review]
LGTM.

**Comment by ingvagabund** [comment]
Closing in favor of https://github.com/kubernetes/contrib/pull/1859

**Pull request closed without merging**
