### PR TITLE
Remove erroneous apostrophe from submit queue

### PR DESCRIPTION
**Pull request by pmorie**
@eparis

### CODE REVIEW

**Comment by eparis** [comment]
I grated on @lavalamp as well.  I like `PRs`, but some magic css stuff I don't understand at all causes it to display as `PRS`. Which I thought was worse than the bad `'`

**Comment by lavalamp** [comment]
PRs would be my preference, too, but I don't care enough to fight with CSS...

**Comment by eparis** [comment]
Paul said he was going to fight with CSS.  Talk about black magic to me!

**Comment by eparis** [comment]
closing, waiting for a CSS fix   :)

**Comment by pmorie** [comment]
@eparis My bad, I'll resubmit w/ CSS fix, been super-busy this and last week

**Pull request closed without merging**
