### PR TITLE
Update kubernetes role to deploy on Ubuntu-16.04

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1700)

### CODE REVIEW

**Comment by ingvagabund** [comment]
Tested with Ubuntu-16.04 with Vagrant, working. Addons are on as well (when applying https://github.com/kubernetes/contrib/pull/1660)

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by ingvagabund** [comment]
@sttts @valentin-krasontovitsch @kovvik feel free to review

**Comment by sttts** [comment]
Look good to me as far as I can judge.

**Comment by valentin-krasontovitsch** [comment]
I can just say that it works for me, am unfortunately not in deep enough to give more critical feedback.

**Comment by ingvagabund** [comment]
It works is enough for me :) Thanks guys.

**Pull request merged**
