### PR TITLE
[nginx-slim]: Release v0.12

### PR DESCRIPTION
**Pull request by aledbf**

### CODE REVIEW

**Comment by aledbf** [comment]
@lavalamp please assign this to @bprashanth

**Comment by bprashanth** [comment]
Any reason to not move this to the ingress repo?

**Comment by aledbf** [comment]
@bprashanth release history? I can try to do the same procedure when I migrated the ingress directory.

**Comment by aledbf** [comment]
@bprashanth I think kubernetes/ingress is not the right place for this. Right now exists a directory only for images here. If we move only this image or with ubuntu-slim then the other images in this repo will depend on a different repo

**Comment by ixdy** [comment]
`gcr.io/google_containers/nginx-slim:0.12` has been pushed.

**Comment by aledbf** [comment]
@ixdy thanks!

**Pull request merged**
