### PR TITLE
zk updates for helm integration

### PR DESCRIPTION
**Pull request by kow3ns**
Updates the configuration script to work off of the number of replicas instead of the ensemble membership 
Updates version to v2

### CODE REVIEW

**Comment by kow3ns** [comment]
@enisoc @foxish

**Comment by enisoc** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 77 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ42_C3dppTAPgsdThZ:-KZ42_C3dppTAPgsdTh_:b-uuwdo0) ([raw file](https://github.com/kubernetes/contrib/blob/b723d1a58b452f3eec390e563f740a5a00a45180/statefulsets/zookeeper/zkGenConfig.sh#L77)):*
> ```Shell
>     for (( i=1; i<=$ZK_REPLICAS; i++ ))
> 	do
> 		echo "server.$i=${HOST/$ORD/$((i-1))}.$DOMAIN:$ZK_SERVER_PORT:$ZK_ELECTION_PORT"
> ```

The pod name may contain numbers elsewhere besides the ordinal at the end. It would be safer to save the prefix as another capture group in the regex on HOST above, and append to it here.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 99 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ439HNTcfJqi9puxxr:-KZ439HOlItKIG5vNi-N:b-nlhr3i) ([raw file](https://github.com/kubernetes/contrib/blob/b723d1a58b452f3eec390e563f740a5a00a45180/statefulsets/zookeeper/zkGenConfig.sh#L99)):*
> ```Shell
>     
>     if [ $ZK_REPLICAS -gt 1 ]; then 
>     	for (( i=1; i<=$ZK_REPLICAS; i++ ))
> ```

This loop looks the same as above. Can you either pull it out into a function, or generate it once and save it in a variable?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Comment by kow3ns** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 77 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ42_C3dppTAPgsdThZ:-KZ82PAqQ3TmLALBBZJq:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/b723d1a58b452f3eec390e563f740a5a00a45180/statefulsets/zookeeper/zkGenConfig.sh#L77)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

The pod name may contain numbers elsewhere besides the ordinal at the end. It would be safer to save the prefix as another capture group in the regex on HOST above, and append to it here.
</blockquote></details>

Done.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 99 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ439HNTcfJqi9puxxr:-KZ82Q6BFfWqORs6L65s:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/b723d1a58b452f3eec390e563f740a5a00a45180/statefulsets/zookeeper/zkGenConfig.sh#L99)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

This loop looks the same as above. Can you either pull it out into a function, or generate it once and save it in a variable?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Comment by enisoc** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 44 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ8xQtsj2SSopS2gU3J:-KZ8xQtsj2SSopS2gU3K:b-dvdoar) ([raw file](https://github.com/kubernetes/contrib/blob/1ee557f80c45093728805e615e06bd404d65c96e/statefulsets/zookeeper/zkGenConfig.sh#L44)):*
> ```Shell
> 	 for (( i=1; i<=$ZK_REPLICAS; i++ ))
> 	do
> 		echo "server.$i=$NAME-$((i-1)).$DOMAIN:$ZK_SERVER_PORT:$ZK_ELECTION_PORT" >> $1
> ```

I think it's cleaner to leave off the `>> $1` and just call it differently depending on what you want:

```shell
# to stdout
print_servers

# to a file
print_servers > filename

# into a variable
variable=$(print_servers)
```

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 55 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ8wyBoGuRluP0zcCT4:-KZ8wyBoGuRluP0zcCT5:b-qv5g79) ([raw file](https://github.com/kubernetes/contrib/blob/1ee557f80c45093728805e615e06bd404d65c96e/statefulsets/zookeeper/zkGenConfig.sh#L55)):*
> ```Shell
> 	fi
>    
> 	if [[ $HOST =~ (.*?)-([0-9]+) ]]; then
> ```

Why did you remove the `$` anchor? If this matches somewhere other than at the end, you want it to fail since it isn't the expected format.

I would use something like `$HOST =~ ^(.*)-([0-9]+)$` to be most clear.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Comment by kow3ns** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 44 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ8xQtsj2SSopS2gU3J:-KZNayZ5LTr4SS42NHeN:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/1ee557f80c45093728805e615e06bd404d65c96e/statefulsets/zookeeper/zkGenConfig.sh#L44)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

I think it's cleaner to leave off the `>> $1` and just call it differently depending on what you want:

```shell
# to stdout
print_servers

# to a file
print_servers > filename

# into a variable
variable=$(print_servers)
```
</blockquote></details>

Done.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 55 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ8wyBoGuRluP0zcCT4:-KZNatVckJwZ6nfhZjO3:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/1ee557f80c45093728805e615e06bd404d65c96e/statefulsets/zookeeper/zkGenConfig.sh#L55)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

Why did you remove the `$` anchor? If this matches somewhere other than at the end, you want it to fail since it isn't the expected format.

I would use something like `$HOST =~ ^(.*)-([0-9]+)$` to be most clear.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Comment by kow3ns** [comment]
@foxish Can you approve the owners file?

**Comment by foxish** [comment]
@enisoc ok to merge?

**Comment by enisoc** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 55 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ8wyBoGuRluP0zcCT4:-KZNhSjVnffMXKaSMbZv:b-obomhc) ([raw file](https://github.com/kubernetes/contrib/blob/1ee557f80c45093728805e615e06bd404d65c96e/statefulsets/zookeeper/zkGenConfig.sh#L55)):*
<details><summary><i>Previously, kow3ns (Kenneth Owens) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Any reason not to anchor at the start as well, like the example I gave above? Also, doesn't `.*?` mean minimal match? I would think you'd want the default greedy match, especially without the `^` anchor.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 103 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZNiDfq_72WYGdEg_92:-KZNiDfrRaIO4WoHJBOk:b-d1cw18) ([raw file](https://github.com/kubernetes/contrib/blob/5ed8334afa63c34cee7ae6206b55feaeb59d259e/statefulsets/zookeeper/zkGenConfig.sh#L103)):*
> ```Shell
>     
>     if [ $ZK_REPLICAS -gt 1 ]; then 
>     	print_servers >> $ZK_CONFIG_FILE
> ```

This should be a single `>`. Previously it was appending for each line. Now `print_servers` generates all the lines together, so you want to replace rather than append to the file.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Comment by enisoc** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[statefulsets/zookeeper/zkGenConfig.sh, line 103 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZNiDfq_72WYGdEg_92:-KZNiill3l3fM4ti3I7q:bd1e7xm) ([raw file](https://github.com/kubernetes/contrib/blob/5ed8334afa63c34cee7ae6206b55feaeb59d259e/statefulsets/zookeeper/zkGenConfig.sh#L103)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

This should be a single `>`. Previously it was appending for each line. Now `print_servers` generates all the lines together, so you want to replace rather than append to the file.
</blockquote></details>

Oops no you're right. Don't know what I was thinking there. :)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Comment by kow3ns** [comment]
*[statefulsets/zookeeper/zkGenConfig.sh, line 55 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ8wyBoGuRluP0zcCT4:-KZNpi_XrQCCBjzMFN9b:boh74gf) ([raw file](https://github.com/kubernetes/contrib/blob/1ee557f80c45093728805e615e06bd404d65c96e/statefulsets/zookeeper/zkGenConfig.sh#L55)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

Any reason not to anchor at the start as well, like the example I gave above? Also, doesn't `.*?` mean minimal match? I would think you'd want the default greedy match, especially without the `^` anchor.
</blockquote></details>

I the above is correct. You are regexing a hostname with the suffix -[0-9]+. The (*.?) indicates to match any string, including the empty string, as the name portion of the <name>-<ordinal> hostname. By definition I want everything preceding the hyphen as the <name>, and, as the <name> is proceeded by a hyphen it can not be empty https://tools.ietf.org/html/rfc952.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Comment by kow3ns** [comment]
*[statefulsets/zookeeper/zkGenConfig.sh, line 103 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZNiDfq_72WYGdEg_92:-KZNulmDesIHXrS5TTql:b-896fix) ([raw file](https://github.com/kubernetes/contrib/blob/5ed8334afa63c34cee7ae6206b55feaeb59d259e/statefulsets/zookeeper/zkGenConfig.sh#L103)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary><blockquote>

Oops no you're right. Don't know what I was thinking there. :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Comment by kow3ns** [comment]
*[statefulsets/zookeeper/zkGenConfig.sh, line 55 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158#-KZ8wyBoGuRluP0zcCT4:-KZNzBjXJ6cKdnvlvAkP:b-qqwgxw) ([raw file](https://github.com/kubernetes/contrib/blob/1ee557f80c45093728805e615e06bd404d65c96e/statefulsets/zookeeper/zkGenConfig.sh#L55)):*
<details><summary><i>Previously, kow3ns (Kenneth Owens) wrote…</i></summary><blockquote>

I the above is correct. You are regexing a hostname with the suffix -[0-9]+. The (*.?) indicates to match any string, including the empty string, as the name portion of the <name>-<ordinal> hostname. By definition I want everything preceding the hyphen as the <name>, and, as the <name> is proceeded by a hyphen it can not be empty https://tools.ietf.org/html/rfc952.
</blockquote></details>

This time using a syntax that doesn't remove text 

I the above is correct. You are regexing a hostname with the suffix -[0-9]+. The (*.?) indicates to match any string, including the empty string, as the name portion of the name-ordinal hostname. By definition I want everything preceding the hyphen as the name, and, as the ordinal is proceeded by a hyphen it can not be empty https://tools.ietf.org/html/rfc952.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Comment by enisoc** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/contrib/2158)*

**Pull request merged**
