### PR TITLE
Delete ingress/controllers, images/{nginx,ubuntu}-slim, which are now in the kubernetes/ingress repo

### PR DESCRIPTION
**Pull request by ixdy**
Remove duplicated out-of-date code.

I left the `ingress/echoheaders` and `ingress/echoheaders-redirect` directories, since those don't seem to exist in kubernetes/ingress.

cc @bprashanth @aledbf

### CODE REVIEW

**Comment by ixdy** [comment]
x-ref https://github.com/kubernetes/ingress/pull/10

**Comment by ixdy** [comment]
There were some doc fixes since this was moved: https://github.com/kubernetes/contrib/commits/0f119d98ca85a82bfae13939af6bd3182798421e/ingress/controllers

Not sure if these were ever imported to kubernetes/ingress.

**Comment by ixdy** [comment]
Looks like nginx-slim and ubuntu-slim also moved (https://github.com/kubernetes/ingress/pull/193), so removing them too.

**Comment by bprashanth** [comment]
2 requests
1. Please retain the ingress/controllers/*/examples directories, since we're still porting them over
2. Please leave the other directories, remove the files and stick a README in them with a link to the new repo. 

The links are already all over the internet via SO/slack etc, so it'll take a while to propagate.

**Comment by ixdy** [comment]
I left pointer `README.md`s in `ingress/controllers`, `images/nginx-slim`, and `images/ubuntu-slim`, and added pointers in all example `README.md`s, along with leaving all `examples` intact. PTAL.

**Comment by aledbf** [comment]
@ixdy thanks for doing this!

**Comment by bprashanth** [comment]
Thanks, LGTM

**Comment by ixdy** [comment]
looks like I need approval too.

**Comment by bprashanth** [comment]
is that what you meant? i thought label wins and the SQ was just clogged or something

**Comment by ixdy** [comment]
I need an /approve too.

**Comment by ixdy** [comment]
Not sure why the bot didn't add the label. @apelisse @grodrigues3 what happened here?

Manually overriding for now.

**Pull request merged**
