### PR TITLE
Fix behavior in case process start metric is missing

### PR DESCRIPTION
**Pull request by crassirostris**

### CODE REVIEW

**Comment by piosz** [comment]
/lgtm
/approve
Thanks for the fix. Will you build the new image?

**Comment by crassirostris** [comment]
Thanks. Yup

**Comment by crassirostris** [comment]
Recalled I wanted to fix a problem here

**Comment by crassirostris** [comment]
@piosz PTAL

**Comment by crassirostris** [comment]
Waiting for https://github.com/kubernetes/contrib/pull/2588 to bump version

**Comment by piosz** [comment]
@crassirostris could you also please wait for #2601? Thanks!

**Pull request merged**
