### PR TITLE
Remove apparmor/loader

### PR DESCRIPTION
**Pull request by dims**
Moved this code to test/images/apparmor-loader/ in main k/k repository
as we need this in e2e tests.

Please see https://github.com/kubernetes/kubernetes/pull/67030

Change-Id: Ib805e676b9f2ddfc8648a080cef7a2ce9cf243d1

### CODE REVIEW

**Comment by dims** [comment]
/hold

until https://github.com/kubernetes/kubernetes/pull/67030 is merged

**Comment by spiffxp** [comment]
/lgtm
merged

**Comment by spiffxp** [comment]
/assign @eparis @lavalamp @foxish 
for the the /approve

**Pull request merged**
