### PR TITLE
Update nginx.tmpl

### PR DESCRIPTION
**Pull request by damiendurant**
Disable server_tokens (remove nginx version from error pages and headers)

### CODE REVIEW

**Comment by damiendurant** [comment]
I signed it!

**Comment by aledbf** [comment]
@damiendurant the development of ingress is now located in https://github.com/kubernetes/ingress.
This feature is already proposed https://github.com/kubernetes/ingress/pull/94

**Comment by aledbf** [comment]
@damiendurant please close this PR

**Comment by damiendurant** [comment]
Thanks.
I close so.

**Pull request closed without merging**
