### PR TITLE
Update godep and go code to fix compilation errors

### PR DESCRIPTION
**Pull request by aledbf**

### CODE REVIEW

**Comment by aledbf** [comment]
@bprashanth this update is required to use ConfigMap in nginx-third-party (not in this PR)

**Comment by aledbf** [comment]
From [go-github](https://github.com/google/go-github/commit/e5099d75375212809d7ccedb61fbbcb2976cff0c): Previously, concurrent calls to Client.Do would have data races writing Client.Rate. Protect it with a mutex.

**Comment by aledbf** [comment]
@brendandburns can you check this? (I see you are updating the dependencies in 353)

**Comment by bprashanth** [comment]
Thanks for the cleanup, lgtm except for the nits

**Comment by aledbf** [comment]
@bprashanth done.

> This is a strange edit

That's godep fault :) .I need to change that (manually)?

**Comment by bprashanth** [comment]
I think you'll need to rebase over Brendans pr (https://github.com/kubernetes/contrib/pull/358)

**Comment by aledbf** [comment]
Closing. Make no sense after 358.

**Pull request closed without merging**
