### PR TITLE
Add aws to allowed values on cluster autoscaler cloud-provider flag

### PR DESCRIPTION
**Pull request by crigor**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1856)

### CODE REVIEW

**Comment by crigor** [comment]
I signed it!

**Comment by mwielgus** [comment]
LGTM

**Comment by mwielgus** [comment]
@crigor Apparently you need to sign one more CLA https://cla.developers.google.com/.

**Comment by crigor** [comment]
@mwielgus I've now signed that too

**Pull request merged**
