### PR TITLE
Replace GoogleCloudPlatform with kubernetes

### PR DESCRIPTION
**Pull request by ingvagabund**
Replace `https://raw.githubusercontent.com/GoogleCloudPlatform` with `https://raw.githubusercontent.com/kubernetes` prefix

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/963)

### CODE REVIEW

**Comment by ingvagabund** [comment]
@eparis

**Comment by eparis** [comment]
rebase and i'll merge.

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by sttts** [comment]
lgtm

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Pull request merged**
