### PR TITLE
[nginx-ingress-controller] Initialize proxy_upstream_name variable

### LINKED ISSUE #1801: ingress: uninitialized "proxy_upstream_name" variable while logging request
I tried the latest nginx.tmpl with the  https://github.com/kubernetes/contrib/pull/1751 change and get lots of error logs in nginx pod:

```
2016/09/29 14:49:36 [warn] 24#24: *454 using uninitialized "proxy_upstream_name" variable while logging request, client: 1.2.3.4, server: example.com, request: "HEAD / HTTP/1.0", host: "example.com"
```

these logs relate to 	newrelic:

```
1.2.3.4 example.com [1.2.3.4] - - [29/Sep/2016:14:54:58 +0000] "HEAD / HTTP/1.0" 301 0 "-" "NewRelicPinger/1.0 (767762)" 219 0.000 [] - - - -
```

### PR DESCRIPTION
**Pull request by aledbf**
fixes #1801

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/contrib/1802)

### CODE REVIEW

**Comment by kayrus** [comment]
two notes:
* set empty value to `-`, otherwise log parsing will be broken
* please remove whitespaces

**Comment by aledbf** [comment]
> set empty value to -, otherwise log parsing will be broken

It's inside [`[]`](https://github.com/aledbf/contrib/blob/9e2b8d4ca9bbd2db4355b6bb24e1ca680c79505e/ingress/controllers/nginx/nginx.tmpl#L78)

**Comment by kayrus** [comment]
@aledbf true. LGTM then.

**Comment by bprashanth** [comment]
LGTM, please send the documentation pr that describs log format output so people can leverage it for greater good (and it keeps un honest about changing the format)

**Comment by kayrus** [comment]
Issue still exists:

```
2016/09/29 18:25:16 [warn] 25#25: *67 using uninitialized "proxy_upstream_name" variable while logging request, client: 1.2.3.4, server: example.com, request: "HEAD / HTTP/1.0", host: "example.com"
```

**Comment by aledbf** [comment]
@kayrus `example.com` is defined in an Ingress rule?

**Comment by kayrus** [comment]
@aledbf Yep

**Comment by kayrus** [comment]
It is reproducible within non-https request.

**Comment by aledbf** [comment]
@kayrus please change
```
            {{- buildProxyPass $location }}
            set $proxy_upstream_name "{{ $location.Upstream.Name }}";
```
to
```
            set $proxy_upstream_name "{{ $location.Upstream.Name }}";
            {{- buildProxyPass $location }}
```

**Comment by kayrus** [comment]
It is not easy without this fix :) https://github.com/kubernetes/contrib/pull/1498
just wonder whether it is reasonable to change these strings too:

```
         location / {
            set $proxy_upstream_name "upstream-default-backend";
             proxy_pass             http://upstream-default-backend;
         }
```

to

```
         set $proxy_upstream_name "upstream-default-backend";
         location / {
             proxy_pass             http://upstream-default-backend;
         }
```

**Comment by kayrus** [comment]
@aledbf no, your change doesn't resolve this issue. you can easily reproduce it using:

```sh
curl -v -X HEAD example.com
```

**Comment by aledbf** [comment]
@kayrus I cannot reproduce the error. Can you test with the mentioned image https://github.com/kubernetes/contrib/issues/1805#issuecomment-250560794

**Pull request merged**
